# Generated by Django 3.0.10 on 2021-05-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("properties", "0040_auto_20210409_1421")]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=128, verbose_name="Название аукциона"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Активный")),
                (
                    "start_price",
                    models.IntegerField(db_index=True, default=0, verbose_name="Стартовая цена"),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время начала аукциона"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время конца аукциона"
                    ),
                ),
                (
                    "property_object",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"type": "commercial"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.Property",
                        verbose_name="Объект собственности",
                    ),
                ),
            ],
            options={"verbose_name": "Аукцион", "verbose_name_plural": "Аукционы"},
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Добавлена")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Цена"),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auction.Auction",
                        verbose_name="Аукцион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ставка аукциона",
                "verbose_name_plural": "Ставки аукциона",
                "ordering": ("-created",),
            },
        ),
    ]
