# Generated by Django 3.0.10 on 2021-05-12 09:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("properties", "0040_auto_20210409_1421"), ("auction", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="link",
            field=models.CharField(blank=True, max_length=300, verbose_name="Ссылка аукциона"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="property_object",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "commercial"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.Property",
                verbose_name="Объект собственности",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Отправлено")),
                ("name", models.CharField(blank=True, max_length=64, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Адрес электронной почты"
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auction.Auction",
                        verbose_name="Аукцион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление о начале аукциона",
                "verbose_name_plural": "Уведомления о начале аукциона",
            },
        ),
    ]
