# Generated by Django 3.0.10 on 2021-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auction", "0003_auto_20210512_1251")]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="step",
            field=models.IntegerField(default=0, verbose_name="Шаг ставки"),
        )
    ]
