# Generated by Django 3.0.10 on 2021-05-13 08:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auction", "0004_auction_step")]

    operations = [
        migrations.CreateModel(
            name="AuctionRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="Текст правил")),
            ],
            options={"verbose_name": "Правила аукциона"},
        )
    ]
