# Generated by Django 3.0.10 on 2021-05-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("auction", "0006_auction_current_price")]

    operations = [migrations.RemoveField(model_name="auction", name="current_price")]
