# Generated by Django 3.0.10 on 2021-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auction", "0007_remove_auction_current_price")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="lot_link",
            field=models.URLField(blank=True, verbose_name="Ссылка лота"),
        )
    ]
