# Generated by Django 3.0.10 on 2021-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auction", "0008_notification_lot_link")]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="bet_count",
            field=models.IntegerField(default=0, verbose_name="Количество ставок"),
        ),
        migrations.DeleteModel(name="Bet"),
    ]
