# Generated by Django 3.0.14 on 2021-12-13 16:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20210517_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionrules',
            name='stages',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Этапы аукциона'),
        ),
    ]
