services:
  redis:
    container_name: messenger-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14-alpine
    container_name: messenger_db
    ports:
      - 5435:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_USER: user

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: messenger_rmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5680:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
