# Generated by Django 3.0.14 on 2022-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_manager", "0005_auto_20220217_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="agent_company",
            field=models.CharField(blank=True, max_length=200, verbose_name="Агенство"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="agent_fio",
            field=models.CharField(blank=True, max_length=300, verbose_name="Агенство ФИО"),
        ),
    ]
