# Generated by Django 3.0.14 on 2022-12-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_manager', '0008_auto_20221024_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='purchase_term',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Сроки покупки'),
        ),
        migrations.CreateModel(
            name='MeetingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mortgage_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='итоговая сумма ипотеки')),
                ('initial_payment', models.PositiveIntegerField(blank=True, default=0, verbose_name='первоначальный взнос')),
                ('has_other_approvals', models.BooleanField(verbose_name='есть-ли одобрения в других банках')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='panel_manager.Meeting', verbose_name='встреча')),
            ],
            options={
                'verbose_name': 'блок ипотеки',
                'verbose_name_plural': 'блоки ипотеки',
            },
        ),
    ]
