# Generated by Django 3.0.14 on 2022-12-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_manager', '0009_auto_20221215_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='purchase_term',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Сроки покупки'),
        ),
        migrations.AlterField(
            model_name='meetingdetails',
            name='has_other_approvals',
            field=models.BooleanField(blank=True, default=False, verbose_name='есть-ли одобрения в других банках'),
        ),
    ]
