# Generated by Django 3.0.14 on 2022-12-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0133_auto_20221212_1724'),
        ('panel_manager', '0010_auto_20221226_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='p/panel/brochures', verbose_name='файл брошюры')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='projects.Project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'брошюра проекта',
                'verbose_name_plural': 'брошюры проектов',
            },
        ),
    ]
