# Generated by Django 3.0.14 on 2023-01-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_manager', '0011_projectbrochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание роли')),
            ],
            options={
                'verbose_name': 'роль менеджера',
                'verbose_name_plural': 'роли менеджеров',
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='roles',
            field=models.ManyToManyField(blank=True, to='panel_manager.Role', verbose_name='роли'),
        ),
    ]
