# Generated by Django 3.0.10 on 2021-02-24 13:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0020_merge_20210128_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Менеджер фида',
                'verbose_name_plural': 'Менеджеры фидов',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('include_booked', models.BooleanField(default=False, verbose_name='Добавлять забронированные объекты')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Алиас')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('template_type', models.CharField(choices=[('yandex', 'Яндекс')], db_index=True, max_length=16, verbose_name='Шаблон фида')),
                ('property_type', models.CharField(choices=[('flat', 'Квартира'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение'), ('pantry', 'Кладовка')], max_length=20, verbose_name='Тип')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('buildings', models.ManyToManyField(blank=True, to='buildings.Building', verbose_name='Корпусы')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.FeedManager', verbose_name='Менеджер фида')),
            ],
            options={
                'verbose_name': 'Фид',
                'verbose_name_plural': 'Фиды',
            },
        ),
    ]
