# Generated by Django 3.0.10 on 2021-04-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmanager',
            name='organization',
            field=models.CharField(blank=True, max_length=150, verbose_name='Организация'),
        ),
    ]
