# Generated by Django 3.0.10 on 2021-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feeds", "0002_feedmanager_organization")]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                    ("commercial_apartment", "Аппартаменты коммерции"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        )
    ]
