# Generated by Django 3.0.14 on 2022-08-16 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20210528_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='template_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('yandex', 'Яндекс'), ('cian', 'Циан'), ('avito', 'Авито')], db_index=True, max_length=16, verbose_name='Шаблон фида'), size=None),
        ),
    ]
