# Generated by Django 3.0.14 on 2022-08-16 13:27

from django.db import migrations, models
import feeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20220816_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='template_type',
            field=feeds.models.ChoiceArrayField(base_field=models.CharField(choices=[('yandex', 'Яндекс'), ('cian', 'Циан'), ('avito', 'Авито')], db_index=True, max_length=16, verbose_name='Шаблон фида'), size=None),
        ),
    ]
