# Generated by Django 3.0.14 on 2021-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DvizhApiSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(default='https://gql.make.dvizh.io/gql', verbose_name='URL API')),
                ('user', models.EmailField(max_length=254, verbose_name='Email Пользователя')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('token', models.CharField(max_length=64, verbose_name='Токен авторизации')),
            ],
            options={
                'verbose_name': 'Настройки для API Движ.',
                'verbose_name_plural': 'Настройки для API Движ.',
            },
        ),
    ]
