# Generated by Django 3.0.14 on 2022-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('dvizh_api', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='dvizhapisettings',
            name='token',
            field=models.TextField(editable=False, null=True, verbose_name='Токен авторизации'),
        )
    ]
