image: tiangolo/docker-with-compose:2021-09-18

variables:
  PYTHON_ADMIN: 'itpro72.ru:5050/strana-artw/strana-backend/python-admin:latest'
  PYTHON_BACKEND: 'itpro72.ru:5050/strana-artw/strana-backend/python-backend:latest'
  PYTHON_CABINET: 'itpro72.ru:5050/strana-artw/strana-backend/python-cabinet:latest'
  DOCKER_DRIVER: overlay2
  CI_DEBUG_SERVICES: trace
  NPM_PACKAGES: $CI_REGISTRY_IMAGE/npm_packages:latest
  COMPOSE_FILES: docker-compose -f docker-compose.yml -f docker-compose.production.yml
  DOCKER_REGISTRY: itpro72.ru:5050/strana-artw/strana-backend/


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        SITE_REDIRECT_LK: lk.stranadev.com
        LK_SITE_HOST: lk.stranadev.com
        LK_REDIRECT: stranadev.com
        MAIN_SITE_HOST: stranadev.com
        CI_COMMIT_SHA: 'latest'
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_NEW_DEV
        TOP_HOST: stranadev.com
        TOKEN_DADATA: ${TOKEN_DADATA}
        ENV_FILE: $ENV_NEW_DEV_FULL_FILE
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SITE_REDIRECT_LK: lk.strana.com
        LK_SITE_HOST: lk.strana.com
        LK_REDIRECT: strana.com
        DEPLOY_USER: bb-idaproject
        DEPLOY_HOST: strana.com
        TOP_HOST: strana.com
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY_strana}
        TOKEN_DADATA: ${TOKEN_DADATA}
        ENV_FILE: $ENV_PROD_FULL_FILE
    - if: $CI_COMMIT_BRANCH == "pre-production"
      variables:
        SITE_REDIRECT_LK: lk.stage.strana.com
        LK_SITE_HOST: lk.stage.strana.com
        LK_REDIRECT: stage.strana.com
        DEPLOY_USER: bb-idaproject
        DEPLOY_HOST: stage.strana.com
        TOP_HOST: stage.strana.com
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY_strana}
        TOKEN_DADATA: ${TOKEN_DADATA}
        ENV_FILE: $ENV_STAGE_FULL_FILE
services:
    - name: docker:20.10.6-dind


before_script:
  #-  - docker login $DOCKER_REGISTRY -u strana_token -p $strana_token 
  #- echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin DOCKER_REGISTRY
  - cat $ENV_DEV_FULL_FILE > .env
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

stages:
  - install_packages
  - build
  - test
#  - release
  - deploy
  - deploy_prod

include:
  - local: '/gitlab/install-packages.yml'
  - local: '/gitlab/backend.yml'
  - local: '/gitlab/test.yml'
#  - local: '/gitlab/release.yml'
  - local: '/gitlab/deploy_backend.yml'


