version: '3.7'

x-app_environment: &app_environment
  environment:
    - DEBUG
    - LK_POSTGRES_PORT
    - LK_POSTGRES_USER
    - LK_POSTGRES_HOST
    - LK_POSTGRES_PASSWORD
    - LK_POSTGRES_DATABASE=postgres
    - LK_POSTGRES_DATABASE_TEST=cabinet_test
    - POSTGRES_PORT_TEST
    - POSTGRES_HOST_TEST
    - POSTGRES_USER_TEST
    - POSTGRES_PASSWORD_TEST
    - PORTAL_POSTGRES_HOST
    - PORTAL_POSTGRES_PORT
    - PORTAL_POSTGRES_USER
    - PORTAL_POSTGRES_DATABASE
    - PORTAL_POSTGRES_PASSWORD
    - LK_REDDIS_URL=redis://cabinet-redis-test:6379/0
    - LK_RESULT_BACKEND=redis://cabinet-redis-test:6379/0
    - LK_BROKER_URL=redis://cabinet-redis-test:6379/0
    - LK_SENTRY_DSN
    - LK_UNLEASH_URL
    - LK_UNLEASH_INSTANCE_ID
services:
  cabinet-pytest:
    image: ${CI_REGISTRY_IMAGE}/cabinet:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    <<: *app_environment
    entrypoint: "pytest"
    restart: "no"

  cabinet-redis-test:
    image: redis:6.0-alpine

