version: '3.7'

x-ftp_environment: &ftp_environment
  environment:
    - FTP_USER
    - FTP_PASS
    - PASV_ADDRESS

services:
  cabinet:
    restart: always
      #entrypoint: sh wait-for ${LK_POSTGRES_HOST:-db_cabinet}:${LK_POSTGRES_PORT:-5432} -- ./entrypoint.production.sh
    command: gunicorn config.asgi:application --preload -w ${GUNICORN_WORKERS:-15} -k uvicorn.workers.UvicornWorker --keep-alive 120 -b 0.0.0.0:1800 --access-logfile - --error-logfile -
    volumes:
      - cabinetlog:/app/logs/

  cabinet_migrations:
    command: sh -c "aerich upgrade"

  admin:
    restart: always
      #entrypoint: sh wait-for ${LK_POSTGRES_HOST:-db_cabinet}:${LK_POSTGRES_PORT:-5432} -- ./entrypoint.production.sh
    command: gunicorn config.wsgi:application -w 5 --keep-alive 120 --timeout 600 -b 0.0.0.0:2100 --access-logfile - --error-logfile -
    volumes:
      - cabinetlog:/app/logs/:ro
      - adminstatic:/app/static/:delegated

  redis:
    restart: always

  tasks:
    deploy:
      resources:
        limits:
          cpus: $CPU_NUM
volumes:
  cabinetlog:
    name: cabinetlog

