# Generated by Django 3.0.10 on 2020-09-24 06:07

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="color",
            field=colorful.fields.RGBColorField(default="#FFFFFF", verbose_name="Цвет"),
        ),
    ]
