# Generated by Django 3.0.10 on 2020-09-28 12:22

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_city_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("icon", models.ImageField(upload_to="", verbose_name="Иконка")),
            ],
            options={
                "verbose_name": "Способ передвижения",
                "verbose_name_plural": "Способы передвижения",
            },
        ),
        migrations.CreateModel(
            name="MetroLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "color",
                    colorful.fields.RGBColorField(
                        blank=True, default="#FF0000", verbose_name="Цвет"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cities.City"
                    ),
                ),
            ],
            options={"verbose_name": "Линия метро", "verbose_name_plural": "Линии метро",},
        ),
        migrations.CreateModel(
            name="Metro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.MetroLine",
                        verbose_name="Линия метро",
                    ),
                ),
            ],
            options={
                "verbose_name": "Станция метро",
                "verbose_name_plural": "Станции метро",
                "ordering": ("order",),
            },
        ),
    ]
