# Generated by Django 3.0.10 on 2020-10-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0004_city_local_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Активный"),
        ),
    ]
