# Generated by Django 3.0.10 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0005_city_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="icon_content",
            field=models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
        ),
        migrations.AlterField(
            model_name="transport",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to="c/t/i", verbose_name="Иконка"),
        ),
    ]
