# Generated by Django 3.0.10 on 2020-11-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0007_auto_20201102_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="commercial_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/c/ci", verbose_name="Коммерческое изображение"
            ),
        ),
    ]
