# Generated by Django 3.0.10 on 2020-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0008_city_commercial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Имя"),
                ),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Слаг")),
                (
                    "image_desktop",
                    models.ImageField(upload_to="m/m/id", verbose_name="Изображение десктоп"),
                ),
                (
                    "image_tablet",
                    models.ImageField(upload_to="m/m/it", verbose_name="Изображение десктоп"),
                ),
                (
                    "image_phone",
                    models.ImageField(upload_to="m/m/ip", verbose_name="Изображение десктоп"),
                ),
            ],
            options={"verbose_name": "Карта", "verbose_name_plural": "Карты",},
        ),
    ]
