# Generated by Django 3.0.10 on 2020-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0009_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="image_desktop",
            field=models.ImageField(
                blank=True, null=True, upload_to="m/m/id", verbose_name="Изображение десктоп"
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="image_phone",
            field=models.ImageField(
                blank=True, null=True, upload_to="m/m/ip", verbose_name="Изображение десктоп"
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="image_tablet",
            field=models.ImageField(
                blank=True, null=True, upload_to="m/m/it", verbose_name="Изображение десктоп"
            ),
        ),
    ]
