# Generated by Django 3.0.10 on 2020-11-11 17:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0010_auto_20201106_1353"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Адресс"),
        ),
        migrations.AddField(
            model_name="city",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="working_time",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Режим работы"
            ),
        ),
    ]
