# Generated by Django 3.0.10 on 2020-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0011_auto_20201111_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="app_store_link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка AppStore"),
        ),
        migrations.AddField(
            model_name="city",
            name="google_play_link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка GooglePlay"),
        ),
    ]
