# Generated by Django 3.0.10 on 2020-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0012_auto_20201117_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="image_phone",
            field=models.ImageField(
                blank=True, null=True, upload_to="m/m/ip", verbose_name="Изображение телефон"
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="image_tablet",
            field=models.ImageField(
                blank=True, null=True, upload_to="m/m/it", verbose_name="Изображение планшет"
            ),
        ),
    ]
