# Generated by Django 3.0.10 on 2020-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0013_auto_20201118_0734"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Главная"),
        ),
    ]
