# Generated by Django 3.0.10 on 2020-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0013_auto_20201118_0734"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=models.CharField(blank=True, max_length=100, verbose_name="Слаг"),
        ),
    ]
