# Generated by Django 3.0.10 on 2020-11-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0014_city_slug"),
        ("cities", "0014_map_is_main"),
    ]

    operations = []
