# Generated by Django 3.0.10 on 2020-11-23 09:06

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_merge_20201118_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Map', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='local_coords',
            field=common.fields.PpoiField(blank=True, max_length=50, null=True, source='map.image_desktop', verbose_name='Точка на генплане'),
        ),
    ]
