# Generated by Django 3.0.10 on 2020-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0016_auto_20201123_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Короткое название"
            ),
        ),
    ]
