# Generated by Django 3.0.10 on 2020-12-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0017_city_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="metroline",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cities.City", verbose_name="Город"
            ),
        ),
    ]
