# Generated by Django 3.0.10 on 2021-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_auto_20201211_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='min_mortgage_commercial',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин коммерческая ипотека'),
        ),
        migrations.AddField(
            model_name='city',
            name='min_mortgage_residential',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин жилая ипотека'),
        ),
    ]
