# Generated by Django 3.0.10 on 2021-01-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_auto_20210122_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='min_commercial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена коммерция'),
        ),
        migrations.AddField(
            model_name='city',
            name='min_commercial_price_divided',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена коммерция поделенная'),
        ),
    ]
