# Generated by Django 3.0.10 on 2021-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0021_auto_20210122_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='max_commercial_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Макс площадь коммерция'),
        ),
        migrations.AddField(
            model_name='city',
            name='min_commercial_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Мин площадь коммерция'),
        ),
    ]
