# Generated by Django 3.0.10 on 2021-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20210122_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='disable_site',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Деактивировать ссылку на сайт города'),
        ),
    ]
