# Generated by Django 3.0.14 on 2022-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_auto_20210922_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='min_mortgage_residential_family',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин жилая ипотека'),
        ),
        migrations.AddField(
            model_name='city',
            name='min_mortgage_residential_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин жилая ипотека(Стандартная программа)'),
        ),
        migrations.AddField(
            model_name='city',
            name='min_mortgage_residential_support',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин жилая ипотека(Гос)'),
        ),
    ]
