# Generated by Django 3.0.14 on 2022-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0026_auto_20220214_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='header_popup_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст верхнего баннера в шапке'),
        ),
        migrations.AddField(
            model_name='city',
            name='header_popup_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка верхнего баннера в шапке'),
        ),
        migrations.AlterField(
            model_name='city',
            name='min_mortgage_residential_family',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин жилая ипотека(Семейная ипотека)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='min_mortgage_residential_support',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин жилая ипотека(Господдержка)'),
        ),
    ]
