# Generated by Django 3.0.14 on 2022-04-21 10:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0027_auto_20220225_1126"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="При наступлении даты, слайд деактивируется",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "red_text",
                    models.CharField(blank=True, max_length=400, verbose_name="Красный текст"),
                ),
                (
                    "form_title",
                    models.CharField(
                        blank=True,
                        help_text="Если заполнен, на слайде появляется форма",
                        max_length=64,
                        verbose_name="Заголовок формы",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(blank=True, max_length=100, verbose_name="Текст кнопки"),
                ),
                (
                    "button_link",
                    models.CharField(blank=True, max_length=1000, verbose_name="Ссылка на кнопке"),
                ),
                (
                    "blank",
                    models.BooleanField(
                        default=False, verbose_name="Открывать ссылку в новой вкладке"
                    ),
                ),
                (
                    "image_desktop_big",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mp/mps/idb",
                        verbose_name="Изображение десктоп (большое)",
                    ),
                ),
                (
                    "image_desktop_small",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mp/mps/ids",
                        verbose_name="Изображение десктоп (маленькое)",
                    ),
                ),
                (
                    "image_tablet",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mp/mps/it",
                        verbose_name="Изображение планшет",
                    ),
                ),
                (
                    "image_phone",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mp/mps/ip",
                        verbose_name="Изображение телефон",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_slides",
                        to="cities.City",
                        verbose_name="Главная страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд на проектах",
                "verbose_name_plural": "Слайд на проектах",
                "ordering": ("order",),
            },
        ),
    ]
