# Generated by Django 3.0.14 on 2022-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='amocrm_enum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID города в AmoCRM'),
        ),
    ]
