# Generated by Django 3.0.14 on 2022-11-30 10:20

from django.db import migrations

def add_amocrm_enum_values(apps, schema_editor):
    City = apps.get_model("cities", "City")
    cities_enums = {
        "Тюмень": 1322598,
        "Санкт-Петербург": 1322602,
        "Москва": 1322604,
        "Eкатеринбург": 1322600
    }
    for name, enum in cities_enums.items():
        City.objects.filter(name=name).update(amocrm_enum=enum)


def remove_amocrm_enum(apps, schema_editor):
    City = apps.get_model("cities", "City")
    City.objects.filter(amocrm_enum__isnull=False).update(amocrm_enum=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0029_city_amocrm_enum'),
    ]

    operations = [
        migrations.RunPython(add_amocrm_enum_values, )
    ]
