# Generated by Django 3.0.7 on 2020-06-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, verbose_name="Алиас")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cian_id",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="ID в Cian"),
                ),
                (
                    "yandex_id",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="ID в Yandex"),
                ),
                (
                    "highway_cian_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID шоссе в Cian"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                (
                    "active",
                    models.BooleanField(db_index=True, default=False, verbose_name="Активен"),
                ),
                ("changed", models.DateField(auto_now=True, verbose_name="Изменено")),
                (
                    "hash",
                    models.BinaryField(blank=True, max_length=20, null=True, verbose_name="Хэш"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("order",),
            },
        ),
    ]
