# Generated by Django 3.0.8 on 2020-07-21 12:53

import ajaximage.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plan",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                validators=[django.core.validators.FileExtensionValidator(("jpg", "jpeg"))],
                verbose_name="Генплан",
            ),
        ),
    ]
