# Generated by Django 3.0.10 on 2020-09-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0003_metro_metroline_transport"),
        ("projects", "0002_project_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="metro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.Metro",
                verbose_name="Станция метро",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.Transport",
                verbose_name="Способ передвижения",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="transport_time",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Время в пути"
            ),
        ),
    ]
