# Generated by Django 3.0.10 on 2020-09-29 09:46

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectgalleryslide"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAdvantage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=200, verbose_name="Подзаголовок"),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст"),),
                (
                    "image",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Изображение"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage_slides",
                        to="projects.Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд преимуществ",
                "verbose_name_plural": "Слайды преимуществ",
                "ordering": ("order",),
            },
        ),
    ]
