# Generated by Django 3.0.10 on 2020-09-30 10:12

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_auto_20200929_1034"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=ajaximage.fields.AjaxImageField(
                blank=True, null=True, verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="project",
            name="seo_keywords",
            field=models.TextField(blank=True, verbose_name="SEO ключевые слова"),
        ),
        migrations.AddField(
            model_name="project",
            name="seo_title",
            field=models.TextField(blank=True, verbose_name="SEO заголовок"),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Заголовок"),
        ),
    ]
