# Generated by Django 3.0.10 on 2020-09-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_auto_20200930_1012"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectgalleryslide",
            options={
                "ordering": ("order",),
                "verbose_name": "Слайд галереи",
                "verbose_name_plural": "Слайды галереи",
            },
        ),
    ]
