# Generated by Django 3.0.10 on 2020-10-01 13:28

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_auto_20200930_1348"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="camera",
            field=models.URLField(blank=True, verbose_name="Ссылка on-line трансляции"),
        ),
        migrations.AddField(
            model_name="project",
            name="panorama_image",
            field=ajaximage.fields.AjaxImageField(
                blank=True, null=True, verbose_name="Изображение панорамы"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="panorama_link",
            field=models.URLField(blank=True, verbose_name="Ссылка для панорамы"),
        ),
        migrations.AddField(
            model_name="project",
            name="panorama_text",
            field=models.CharField(blank=True, max_length=200, verbose_name="Текст для панорамы"),
        ),
        migrations.AddField(
            model_name="project",
            name="panorama_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Заголовок для панорамы"
            ),
        ),
    ]
