# Generated by Django 3.0.10 on 2020-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_auto_20201001_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Срок сдачи"),
        ),
    ]
