# Generated by Django 3.0.10 on 2020-10-09 10:46

import ckeditor.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finishing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="p/f/i", verbose_name="Изображение"),),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Текст"),),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Отделка",
                "verbose_name_plural": "Отделки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="FinishingCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Категория отделки",
                "verbose_name_plural": "Категории отделки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="FinishingTab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Таб отделки",
                "verbose_name_plural": "Табы отделки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="FinishingPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    common.fields.PpoiField(
                        blank=True,
                        max_length=50,
                        null=True,
                        source="finishing.image",
                        verbose_name="Точка",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Текст"),),
                (
                    "finishing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Finishing",
                        verbose_name="Отделка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка на отделке",
                "verbose_name_plural": "Точки на отделке",
            },
        ),
        migrations.AddField(
            model_name="finishing",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.FinishingCategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="finishing",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AddField(
            model_name="finishing",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.FinishingTab",
                verbose_name="Таб",
            ),
        ),
    ]
