# Generated by Django 3.0.10 on 2020-10-14 09:10

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_auto_20201009_1046"),
    ]

    operations = [
        migrations.RemoveField(model_name="finishing", name="project",),
        migrations.AddField(
            model_name="project",
            name="finishing",
            field=models.ManyToManyField(
                blank=True, to="projects.Finishing", verbose_name="Отделка"
            ),
        ),
        migrations.AlterField(
            model_name="projectgalleryslide",
            name="image",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 1440, выс. - 595",
                null=True,
                verbose_name="Изображение",
            ),
        ),
    ]
