# Generated by Django 3.0.10 on 2020-10-22 07:43

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_auto_20201016_1409"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIdeology",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text_1", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст 1")),
                ("text_2", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст 2")),
                (
                    "image_1",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Изображение 1"
                    ),
                ),
                (
                    "image_2",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Изображение 1"
                    ),
                ),
                ("video_link_1", models.URLField(blank=True, verbose_name="Ссылка на видео 1")),
                (
                    "video_preview_1",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Превью видео 1"
                    ),
                ),
                ("video_link_2", models.URLField(blank=True, verbose_name="Ссылка на видео 2")),
                (
                    "video_preview_2",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Превью видео 2"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(blank=True, max_length=100, verbose_name="Текст кнопки"),
                ),
                ("button_link", models.URLField(blank=True, verbose_name="Ссылка на кнопке")),
            ],
            options={
                "verbose_name": "Идеология проекта",
                "verbose_name_plural": "Идеологии проекта",
            },
        ),
        migrations.CreateModel(
            name="ProjectIdeologyCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("file", ajaximage.fields.AjaxImageField(verbose_name="Файл")),
                (
                    "ideology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideology_cards",
                        to="projects.ProjectIdeology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка идеологии проекта",
                "verbose_name_plural": "Карточки идеологии проекта",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="ideology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.ProjectIdeology",
                verbose_name="Идеология",
            ),
        ),
    ]
