# Generated by Django 3.0.10 on 2020-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_auto_20201022_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skip_sections",
            field=models.BooleanField(default=False, verbose_name="Пропустить секции"),
        ),
    ]
