# Generated by Django 3.0.10 on 2020-10-29 12:28

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_project_skip_sections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectadvantage",
            options={
                "ordering": ("order",),
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.RemoveField(model_name="project", name="camera",),
        migrations.RemoveField(model_name="projectadvantage", name="image",),
        migrations.AddField(
            model_name="project",
            name="video",
            field=models.URLField(blank=True, verbose_name="Видео о проекте"),
        ),
        migrations.AddField(
            model_name="projectgalleryslide",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Подзаголовок"
            ),
        ),
        migrations.AddField(
            model_name="projectgalleryslide",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="projectadvantage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advantages",
                to="projects.Project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectAdvantageSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", ajaximage.fields.AjaxImageField(verbose_name="Изображение")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                (
                    "project_advantage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage_slides",
                        to="projects.ProjectAdvantage",
                        verbose_name="Преимущество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд преимущества",
                "verbose_name_plural": "Слайды преимуществ",
                "ordering": ("order",),
            },
        ),
    ]
