# Generated by Django 3.0.10 on 2020-10-29 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_auto_20201029_1228"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video_duration",
            field=models.CharField(
                default="2:30", max_length=30, verbose_name="Длительность видео"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="plan",
            field=models.ImageField(
                blank=True,
                height_field="plan_height",
                upload_to="p/p/p1",
                validators=[django.core.validators.FileExtensionValidator(("jpg", "jpeg"))],
                verbose_name="Генплан",
                width_field="plan_width",
            ),
        ),
    ]
