# Generated by Django 3.0.10 on 2020-10-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_auto_20201029_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="kind",
            field=models.CharField(
                choices=[("living", "Жилые"), ("commercial", "Коммерческие")],
                default="living",
                max_length=15,
                verbose_name="Тип",
            ),
        ),
    ]
