# Generated by Django 3.0.10 on 2020-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_project_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="about_text",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Текст о проекте"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="about_text_colored",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Выделенный тексто проекте"
            ),
        ),
    ]
