# Generated by Django 3.0.10 on 2020-11-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_auto_20201030_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="p/card_image",
                verbose_name="Изображение на карточке",
            ),
        ),
    ]
