# Generated by Django 3.0.10 on 2020-11-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_project_card_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ten_minutes_circle",
            field=models.ImageField(
                blank=True, null=True, upload_to="p/p/tmc", verbose_name="Десятиминутный круг"
            ),
        ),
    ]
