# Generated by Django 3.0.10 on 2020-11-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_project_ten_minutes_circle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "text",
                    models.TextField(blank=True, max_length=500, null=True, verbose_name="Текст"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="p/pf/i", verbose_name="Изображение"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность проекта",
                "verbose_name_plural": "Особенности проекта",
                "ordering": ("order",),
            },
        ),
    ]
