# Generated by Django 3.0.10 on 2020-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_projectfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="amocrm_enum",
            field=models.CharField(
                blank=True,
                help_text="Для отправки запросов",
                max_length=200,
                verbose_name="Enum в AmoCRM",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="amocrm_name",
            field=models.CharField(
                blank=True,
                help_text="Для отправки запросов",
                max_length=200,
                verbose_name="Название в AmoCRM",
            ),
        ),
    ]
