# Generated by Django 3.0.10 on 2020-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_auto_20201106_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="kind",
            field=models.CharField(
                choices=[("RESIDENTIAL", "Жилое"), ("OFFICE", "Коммерческое")],
                default="RESIDENTIAL",
                max_length=15,
                verbose_name="Тип",
            ),
        ),
    ]
