# Generated by Django 3.0.10 on 2020-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_auto_20201112_1359"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="kind",),
        migrations.AddField(
            model_name="project",
            name="is_commercial",
            field=models.BooleanField(default=False, verbose_name="Коммерческий"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_residential",
            field=models.BooleanField(default=False, verbose_name="Жилой"),
        ),
    ]
