# Generated by Django 3.0.10 on 2020-11-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_auto_20201112_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="about_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="p/about_image",
                verbose_name="Изображение о проекте",
            ),
        ),
    ]
