# Generated by Django 3.0.10 on 2020-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_project_about_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="news_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="p/p/ni", verbose_name="Изображение новостей"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="news_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Заголовок новостей"
            ),
        ),
    ]
