# Generated by Django 3.0.10 on 2020-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_auto_20201116_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="socials_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Заголовок соцсетей"
            ),
        ),
    ]
