# Generated by Django 3.0.10 on 2020-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_socials_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disable_parking',
            field=models.BooleanField(default=False, help_text='Отключение выбора на генплане и в подборщике', verbose_name='Отключение паркинга'),
        ),
    ]
