# Generated by Django 3.0.10 on 2020-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_disable_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='panorama_url',
            field=models.TextField(blank=True, verbose_name='URL на файл с панорамой'),
        ),
    ]
