# Generated by Django 3.0.10 on 2020-11-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_panorama_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='panorama_url',
        ),
    ]
