# Generated by Django 3.0.10 on 2020-11-25 14:03

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_remove_project_panorama_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=colorful.fields.RGBColorField(default="#FFFFFF", verbose_name="Цвет"),
        ),
    ]
