# Generated by Django 3.0.10 on 2020-11-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_project_color"),
    ]

    operations = [
        migrations.RenameField(model_name="project", old_name="color", new_name="project_color",),
    ]
