# Generated by Django 3.0.10 on 2020-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0024_auto_20201205_1220"),
        ("projects", "0034_auto_20201125_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="furnish_set",
            field=models.ManyToManyField(
                blank=True, to="properties.Furnish", verbose_name="Варианты отделки"
            ),
        ),
    ]
