# Generated by Django 3.0.10 on 2020-12-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_furnish_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="skip_sections",
            field=models.BooleanField(
                default=False,
                help_text="Отключение секций на генплане",
                verbose_name="Пропустить секции",
            ),
        ),
        migrations.AlterField(
            model_name="projectadvantage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advantages",
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="projectgalleryslide",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_slides",
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="projectideologycard",
            name="ideology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideology_cards",
                to="projects.ProjectIdeology",
                verbose_name="Идеология",
            ),
        ),
    ]
