# Generated by Django 3.0.10 on 2020-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20201214_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apartments',
            field=models.BooleanField(default=False, help_text='Меняет название объектов на апартаменты', verbose_name='Проект с апартаментами'),
        ),
    ]
