# Generated by Django 3.0.10 on 2021-01-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_project_apartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_commercial_business_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Мин цена бизнес'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_commercial_prop_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Мин цена коммерции'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_commercial_tenant_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Мин цена арендатор'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_flat_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Мин цена квартиры'),
        ),
    ]
