# Generated by Django 3.0.10 on 2021-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_project_apartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amo_pipeline_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID  воронки CRM'),
        ),
        migrations.AddField(
            model_name='project',
            name='amo_responsible_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID  ответственного CRM'),
        ),
    ]
