# Generated by Django 3.0.10 on 2021-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20210125_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_commercial_prop_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Макс площадь коммерции'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_flat_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Макс площадь квартиры'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_commercial_prop_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Мин площадь коммерции'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_flat_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Мин площадь квартиры'),
        ),
    ]
