# Generated by Django 3.0.10 on 2021-01-25 12:17

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20210125_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                ('projects', models.ManyToManyField(to='projects.Project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Лейбл проектов',
                'verbose_name_plural': 'Лейбы проектов',
                'ordering': ('order',),
            },
        ),
    ]
