# Generated by Django 3.0.10 on 2021-01-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20210125_0827'),
        ('projects', '0038_auto_20210122_0949'),
    ]

    operations = [
    ]
