# Generated by Django 3.0.10 on 2021-01-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_projectlabel'),
        ('projects', '0039_auto_20210125_1004'),
    ]

    operations = [
    ]
