# Generated by Django 3.0.10 on 2021-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20210125_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flats_0_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена студия'),
        ),
        migrations.AddField(
            model_name='project',
            name='flats_1_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 1-комн'),
        ),
        migrations.AddField(
            model_name='project',
            name='flats_2_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 2-комн'),
        ),
        migrations.AddField(
            model_name='project',
            name='flats_3_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 3-комн'),
        ),
        migrations.AddField(
            model_name='project',
            name='flats_4_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 4-комн'),
        ),
    ]
