# Generated by Django 3.0.10 on 2021-01-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_merge_20210125_0846'),
        ('projects', '0039_auto_20210125_1004'),
    ]

    operations = [
    ]
