# Generated by Django 3.0.10 on 2021-01-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_projectlabel'),
        ('projects', '0040_merge_20210125_1012'),
    ]

    operations = [
    ]
