# Generated by Django 3.0.10 on 2021-01-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20210127_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWebcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Веб-камера проекта',
                'verbose_name_plural': 'Веб-камеры проекта',
                'ordering': ('order',),
            },
        ),
    ]
