# Generated by Django 3.0.10 on 2021-01-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_merge_20210126_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlabel',
            name='description',
            field=models.CharField(max_length=64, verbose_name='Описание'),
        ),
    ]
