# Generated by Django 3.0.10 on 2021-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20210127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_rate_offers',
            field=models.FloatField(blank=True, null=True, verbose_name='Мин ставка ипотечного предложения'),
        ),
    ]
