# Generated by Django 3.0.10 on 2021-01-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_merge_20210126_0803'),
        ('projects', '0040_merge_20210126_1506'),
    ]

    operations = [
    ]
