# Generated by Django 3.0.10 on 2021-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_project_min_rate_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_commercial_mortgage',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Мин платеж по ипотеке коммерции'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_flat_mortgage',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Мин платеж по ипотеке квартир'),
        ),
    ]
