# Generated by Django 3.0.10 on 2021-01-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20210127_1150'),
        ('projects', '0042_merge_20210126_1512'),
    ]

    operations = [
    ]
