# Generated by Django 3.0.10 on 2021-01-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_merge_20210127_1203'),
        ('projects', '0041_project_min_rate_offers'),
    ]

    operations = [
    ]
