# Generated by Django 3.0.10 on 2021-01-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20210127_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bank_logo_1',
            field=models.FileField(blank=True, null=True, upload_to='bank/logo', verbose_name='Лого банка 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bank_logo_2',
            field=models.FileField(blank=True, null=True, upload_to='bank/logo', verbose_name='Лого банка 2'),
        ),
    ]
