# Generated by Django 3.0.10 on 2021-01-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_merge_20210127_1303'),
        ('projects', '0042_auto_20210127_1344'),
    ]

    operations = [
    ]
