# Generated by Django 3.0.10 on 2021-01-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20210127_1500'),
        ('projects', '0038_auto_20210122_0949'),
    ]

    operations = [
    ]
