# Generated by Django 3.0.10 on 2021-01-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_merge_20210128_1123'),
        ('projects', '0045_merge_20210128_1044'),
    ]

    operations = [
    ]
