# Generated by Django 3.0.10 on 2021-01-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_merge_20210127_1345'),
        ('projects', '0043_auto_20210127_1435'),
    ]

    operations = [
    ]
