# Generated by Django 3.0.10 on 2021-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_merge_20210128_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlabel',
            options={'ordering': ('order',), 'verbose_name': 'Лейбл проектов', 'verbose_name_plural': 'Лейблы проектов'},
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='Описание'),
        ),
    ]
