# Generated by Django 3.0.10 on 2021-01-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_merge_20210127_1438'),
        ('projects', '0044_auto_20210127_1500'),
    ]

    operations = [
    ]
