# Generated by Django 3.0.10 on 2021-01-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20210127_1423'),
        ('projects', '0047_merge_20210127_1502'),
    ]

    operations = [
    ]
