# Generated by Django 3.0.10 on 2021-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20210128_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='financing_logo',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/fi', verbose_name='Логотип финансирования'),
        ),
    ]
