# Generated by Django 3.0.10 on 2021-01-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_merge_20210128_1044'),
        ('projects', '0048_merge_20210128_0823'),
    ]

    operations = [
    ]
