# Generated by Django 3.0.10 on 2021-01-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_projectwebcam'),
        ('projects', '0048_auto_20210128_1403'),
    ]

    operations = [
    ]
