# Generated by Django 3.0.10 on 2021-01-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_merge_20210128_1155'),
        ('projects', '0049_merge_20210128_1058'),
    ]

    operations = [
    ]
