# Generated by Django 3.0.10 on 2021-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_project_financing_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlabel',
            name='display_main',
            field=models.BooleanField(default=False, verbose_name='Выводить на главной'),
        ),
    ]
