# Generated by Django 3.0.10 on 2021-02-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_merge_20210129_0919'),
        ('projects', '0050_projectlabel_display_main'),
    ]

    operations = [
    ]
