# Generated by Django 3.0.10 on 2021-01-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_merge_20210128_1235'),
        ('projects', '0047_auto_20210128_1219'),
    ]

    operations = [
    ]
