# Generated by Django 3.0.10 on 2021-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_merge_20210218_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_sky_color',
            field=models.CharField(choices=[('dark_blue', 'Синее'), ('light_blue', 'Голубое'), ('aquamarine', 'Аквамариновое')], default='light_blue', max_length=20, verbose_name='Цвет неба на карточке проекта'),
        ),
    ]
