# Generated by Django 3.0.10 on 2021-03-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_merge_20210218_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('current', 'Текущий'), ('completed', 'Завершенный'), ('future', 'Будущий')], default='current', max_length=20, verbose_name='Статус'),
        ),
    ]
