# Generated by Django 3.0.10 on 2021-01-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20210128_1403'),
        ('projects', '0051_merge_20210128_1318'),
    ]

    operations = [
    ]
