# Generated by Django 3.0.10 on 2021-03-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_project_card_sky_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amocrm_organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация в AmoCRM'),
        ),
    ]
