# Generated by Django 3.0.10 on 2021-03-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_project_status'),
        ('projects', '0052_project_card_sky_color'),
    ]

    operations = [
    ]
