# Generated by Django 3.0.10 on 2021-01-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_merge_20210129_0919'),
        ('projects', '0052_merge_20210128_1455'),
    ]

    operations = [
    ]
