# Generated by Django 3.0.10 on 2021-03-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_merge_20210310_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commissioning_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата старта проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_area',
            field=models.FloatField(blank=True, help_text='В квадратных метрах', null=True, verbose_name='Общая площадь проекта'),
        ),
    ]
