# Generated by Django 3.0.10 on 2021-02-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_project_financing_logo'),
        ('projects', '0053_merge_20210129_1113'),
    ]

    operations = [
    ]
