# Generated by Django 3.0.10 on 2021-02-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_projectlabel_display_main'),
        ('projects', '0054_merge_20210217_0804'),
    ]

    operations = [
    ]
