# Generated by Django 3.0.10 on 2021-02-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_merge_20210217_1059'),
        ('projects', '0051_merge_20210218_1237'),
    ]

    operations = [
    ]
