# Generated by Django 3.0.10 on 2021-04-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20210406_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='window_view_plan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='window_view_plan_height',
        ),
        migrations.RemoveField(
            model_name='project',
            name='window_view_plan_width',
        ),
    ]
