# Generated by Django 3.0.10 on 2021-03-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_merge_20210218_1457'),
        ('projects', '0052_project_status'),
    ]

    operations = [
    ]
