# Generated by Django 3.0.10 on 2021-03-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_project_card_sky_color'),
        ('projects', '0057_merge_20210303_1626'),
    ]

    operations = [
    ]
