# Generated by Django 3.0.10 on 2021-03-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_merge_20210305_0913'),
        ('projects', '0053_merge_20210310_1343'),
    ]

    operations = [
    ]
