# Generated by Django 3.0.10 on 2021-03-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20210324_1524'),
        ('projects', '0059_merge_20210310_1408'),
    ]

    operations = [
    ]
