# Generated by Django 3.0.10 on 2021-03-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_merge_20210324_1527'),
        ('projects', '0053_project_amocrm_organization'),
    ]

    operations = [
    ]
