# Generated by Django 3.0.10 on 2021-04-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_merge_20210331_1236'),
        ('projects', '0055_auto_20210406_1234'),
    ]

    operations = [
    ]
