# Generated by Django 3.0.10 on 2021-04-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_merge_20210406_1338'),
        ('projects', '0056_auto_20210409_1421'),
    ]

    operations = [
    ]
