# Generated by Django 3.0.10 on 2021-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0063_merge_20210409_1631")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="card_link",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Ссылка на карточке проекта"
            ),
        )
    ]
