# Generated by Django 3.0.10 on 2021-06-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0064_project_card_link")]

    operations = [migrations.RemoveField(model_name="project", name="furnish_set")]
