# Generated by Django 3.0.10 on 2021-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0048_layout_window_view"),
        ("projects", "0065_remove_project_furnish_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="furnish_set",
            field=models.ManyToManyField(
                blank=True, to="properties.Furnish", verbose_name="Варианты отделки"
            ),
        )
    ]
