# Generated by Django 3.0.10 on 2021-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0066_project_furnish_set")]

    operations = [
        migrations.AddField(
            model_name="projectlabel",
            name="display_slider",
            field=models.BooleanField(
                default=False,
                help_text="В шапке на странице проекта",
                verbose_name="Выводить в слайдере",
            ),
        )
    ]
