# Generated by Django 3.0.10 on 2021-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0067_projectlabel_display_slider")]

    operations = [
        migrations.AddField(
            model_name="projectlabel",
            name="link",
            field=models.CharField(blank=True, max_length=200, verbose_name="Ссылка"),
        )
    ]
