# Generated by Django 3.0.10 on 2021-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0068_projectlabel_link")]

    operations = [
        migrations.AddField(
            model_name="projectlabel",
            name="shape",
            field=models.CharField(
                choices=[("square", "Квадратная"), ("rectangle", "Прямоугольная")],
                default="square",
                max_length=64,
                verbose_name="Форма лейбла",
            ),
        )
    ]
