# Generated by Django 3.0.10 on 2021-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0069_projectlabel_shape")]

    operations = [
        migrations.AddField(
            model_name="projectgalleryslide",
            name="video_link_mob",
            field=models.URLField(blank=True, verbose_name="Ссылка на видео (моб.)"),
        ),
        migrations.AlterField(
            model_name="projectgalleryslide",
            name="video_link",
            field=models.URLField(blank=True, verbose_name="Ссылка на видео (деск.)"),
        ),
    ]
