# Generated by Django 3.0.10 on 2021-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0069_projectlabel_shape")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="card_image_night",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="p/card_image_night",
                verbose_name="Изображение на карточке (ночь)",
            ),
        )
    ]
