# Generated by Django 3.0.10 on 2021-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0070_auto_20210702_1609")]

    operations = [
        migrations.AddField(
            model_name="projectfeature",
            name="image_description",
            field=models.TextField(blank=True, verbose_name="Опиание изображения"),
        )
    ]
