# Generated by Django 3.0.10 on 2021-07-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0071_projectfeature_image_description"),
        ("projects", "0070_project_card_image_night"),
    ]

    operations = []
