# Generated by Django 3.0.10 on 2021-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0072_merge_20210712_1113")]

    operations = [
        migrations.RemoveField(model_name="projectfeature", name="image_description"),
        migrations.AddField(
            model_name="projectadvantageslide",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опиание изображения"),
        ),
    ]
