# Generated by Django 3.0.10 on 2021-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0073_auto_20210712_1256")]

    operations = [
        migrations.AlterField(
            model_name="projectadvantageslide",
            name="description",
            field=models.TextField(blank=True, max_length=405, verbose_name="Опиание изображения"),
        )
    ]
