# Generated by Django 3.0.10 on 2021-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0074_auto_20210713_1500")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="parking_image",
            field=models.ImageField(
                blank=True, upload_to="p/pi", verbose_name="Изображение блока 'Паркинг'"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="parking_text",
            field=models.TextField(blank=True, verbose_name="Текст блока 'Паркинг'"),
        ),
        migrations.AddField(
            model_name="project",
            name="parking_title",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Заголовок блока 'Паркинг'"
            ),
        ),
    ]
