# Generated by Django 3.0.10 on 2021-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0074_auto_20210713_1500")]

    operations = [
        migrations.RemoveField(model_name="projectgalleryslide", name="video_link"),
        migrations.RemoveField(model_name="projectgalleryslide", name="video_link_mob"),
        migrations.AddField(
            model_name="projectgalleryslide",
            name="video",
            field=models.FileField(blank=True, upload_to="p/pgs/v", verbose_name="Видео (деск.)"),
        ),
        migrations.AddField(
            model_name="projectgalleryslide",
            name="video_mobile",
            field=models.FileField(blank=True, upload_to="p/pgs/vm", verbose_name="Видео (моб.)"),
        ),
    ]
