# Generated by Django 3.0.10 on 2021-07-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0075_auto_20210714_1648"),
        ("projects", "0075_auto_20210714_1617"),
    ]

    operations = []
