# Generated by Django 3.0.10 on 2021-07-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0076_merge_20210716_1101")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="display_news_admin",
            field=models.BooleanField(
                default=True,
                help_text="В админке",
                verbose_name="Выводить в список для новостей/акций",
            ),
        )
    ]
