# Generated by Django 3.0.10 on 2021-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0077_project_display_news_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="label_with_completion",
            field=models.CharField(
                blank=True,
                help_text="Для фильтр квартир, высчитывается автоматически",
                max_length=64,
                null=True,
                verbose_name="Лейбл с ближайшей датой сдачи",
            ),
        ),
    ]
