# Generated by Django 3.0.10 on 2021-08-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0026_news_short_description"),
        ("projects", "0078_project_label_with_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTimer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("end", models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания")),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, verbose_name="Описание"),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.News",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Таймер проекта",
                "verbose_name_plural": "Таймеры проектов",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="timer",
            field=models.ForeignKey(
                blank=True,
                help_text="Отобразится баннер в футере",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.ProjectTimer",
                verbose_name="Таймер",
            ),
        ),
    ]
