# Generated by Django 3.0.10 on 2021-08-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0078_project_label_with_completion")]

    operations = [
        migrations.AddField(
            model_name="projectadvantage",
            name="button_callback",
            field=models.BooleanField(
                default=False, verbose_name="Форма обратного звонка на кнопке"
            ),
        ),
        migrations.AddField(
            model_name="projectadvantage",
            name="button_link",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Ссылка кнопки",
                help_text="Укажите относительный путь или абсолютный, вместе с 'Открывать ссылку в новой вкладке'",
            ),
        ),
        migrations.AddField(
            model_name="projectadvantage",
            name="button_link_blank",
            field=models.BooleanField(
                default=False, verbose_name="Открывать ссылку в новой вкладке"
            ),
        ),
        migrations.AddField(
            model_name="projectadvantage",
            name="button_name",
            field=models.CharField(
                blank=True,
                help_text="Если не заполнено, не выводится. Можно установить ссылку ИЛИ добавить форму обратного звонка.",
                max_length=32,
                verbose_name="Название кнопки",
            ),
        ),
    ]
