# Generated by Django 3.0.10 on 2021-08-31 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_projectadvantageslide_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadvantage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=320, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='projectadvantageslide',
            name='description',
            field=models.TextField(blank=True, max_length=30, verbose_name='Опиание изображения'),
        ),
    ]
