# Generated by Django 3.0.10 on 2021-08-31 12:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_auto_20210831_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadvantage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=450, verbose_name='Текст'),
        ),
    ]
