# Generated by Django 3.0.10 on 2021-09-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_project_is_soon'),
        ('projects', '0080_projecttimer_request_type'),
    ]

    operations = [
    ]
