# Generated by Django 3.0.10 on 2021-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_merge_20210920_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimer',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='projecttimer',
            name='text_button',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст для кнопки'),
        ),
    ]
