# Generated by Django 3.0.10 on 2021-10-01 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_merge_20210920_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadvantage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=600, verbose_name='Текст'),
        ),
    ]
