# Generated by Django 3.0.10 on 2021-10-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_merge_20210823_1212'),
        ('projects', '0085_auto_20211001_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimer',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.News', verbose_name='Новость'),
        ),
    ]
