# Generated by Django 3.0.10 on 2021-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_auto_20211001_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimer',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, verbose_name='Краткое описание'),
        ),
    ]
