# Generated by Django 3.0.10 on 2021-10-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_projecttimer_short_description'),
        ('projects', '0085_auto_20211001_1429'),
    ]

    operations = [
    ]
