# Generated by Django 3.0.10 on 2021-10-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20211007_1808'),
        ('projects', '0087_merge_20211008_1720'),
    ]

    operations = [
    ]
