# Generated by Django 3.0.10 on 2021-10-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_merge_20211008_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='close_sync',
            field=models.BooleanField(default=True, verbose_name='Скрыть для синхронизации с ProfitBase'),
        ),
    ]
