# Generated by Django 3.0.10 on 2021-10-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_project_close_sync'),
        ('projects', '0089_project_is_display_future_on_map'),
    ]

    operations = [
    ]
