# Generated by Django 3.0.10 on 2021-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_merge_20211015_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='close_sync',
            field=models.BooleanField(default=False, verbose_name='Скрыть для синхронизации с ProfitBase'),
        ),
    ]
