# Generated by Django 3.0.10 on 2021-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_auto_20211015_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/logo', verbose_name='Логотип'),
        ),
    ]
