# Generated by Django 3.0.10 on 2021-10-26 09:02

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='Логотип'),
        ),
    ]
