# Generated by Django 3.0.10 on 2021-10-26 09:20

import ajaximage.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20211026_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(('png', 'svg'))], verbose_name='Логотип'),
        ),
    ]
