# Generated by Django 3.0.14 on 2021-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_project_show_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dont_commercial_prop_update',
            field=models.BooleanField(default=False, verbose_name='Не обновлять площади коммерции'),
        ),
    ]
