# Generated by Django 3.0.14 on 2021-11-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_project_dont_commercial_prop_update'),
        ('projects', '0096_project_video_preview'),
    ]

    operations = [
    ]
