# Generated by Django 3.0.14 on 2021-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_merge_20211119_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Добавляет текст на карточку', verbose_name='Сдан'),
        ),
    ]
