# Generated by Django 3.0.14 on 2021-12-03 08:29

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_project_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgalleryslide',
            name='image_desktop_small',
            field=models.ImageField(blank=True, null=True, upload_to='p/gallery/', verbose_name='Изображение десктоп (маленькое)'),
        ),
        migrations.AddField(
            model_name='projectgalleryslide',
            name='image_phone',
            field=models.ImageField(blank=True, null=True, upload_to='p/gallery', verbose_name='Изображение телефон'),
        ),
        migrations.AddField(
            model_name='projectgalleryslide',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='p/gallery', verbose_name='Изображение планшет'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 595', null=True, verbose_name='Изображение десктоп (большое)'),
        ),
    ]
