# Generated by Django 3.0.14 on 2021-12-08 08:25

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_auto_20211203_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 3200, выс. - 1900', null=True, verbose_name='Изображение десктоп (большое)'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image_desktop_small',
            field=models.ImageField(blank=True, help_text='шир. - 1830, выс. - 1168', null=True, upload_to='p/gallery/', verbose_name='Изображение десктоп (маленькое)'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image_phone',
            field=models.ImageField(blank=True, help_text='шир. - 1280, выс. - 1568', null=True, upload_to='p/gallery', verbose_name='Изображение телефон'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image_tablet',
            field=models.ImageField(blank=True, help_text='шир. - 1152, выс. - 811', null=True, upload_to='p/gallery', verbose_name='Изображение планшет'),
        ),
    ]
