# Generated by Django 3.0.14 on 2021-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_auto_20211208_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='open_booking_with_sale',
            field=models.BooleanField(default=False, verbose_name='Открыть бронирование для квартир со скидкой'),
        ),
    ]
