# Generated by Django 3.0.10 on 2021-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_project_open_booking_with_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation',
            field=models.FileField(blank=True, upload_to='p/presentation', verbose_name='Презентация проекта'),
        ),
    ]
