# Generated by Django 3.0.14 on 2021-12-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_project_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dvizh_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id комплекса в Движ.API'),
        ),
    ]
