# Generated by Django 3.0.14 on 2022-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_project_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_sales',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта продаж'),
        ),
    ]
