# Generated by Django 3.0.14 on 2021-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0103_project_dvizh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dvizh_uuid',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, verbose_name='UUID комплекса в Движ.API'),
        ),
    ]
