# Generated by Django 3.0.14 on 2022-01-19 15:33

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0103_project_start_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 3200, выс. - 1900, размер - до 1,5 мб', null=True, verbose_name='Изображение десктоп (большое)'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image_desktop_small',
            field=models.ImageField(blank=True, help_text='шир. - 1830, выс. - 1168, размер - до 1 мб', null=True, upload_to='p/gallery/', verbose_name='Изображение десктоп (маленькое)'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image_phone',
            field=models.ImageField(blank=True, help_text='шир. - 1280, выс. - 1568, размер - до 430 кб', null=True, upload_to='p/gallery', verbose_name='Изображение телефон'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='image_tablet',
            field=models.ImageField(blank=True, help_text='шир. - 1152, выс. - 811, размер - до 750 кб', null=True, upload_to='p/gallery', verbose_name='Изображение планшет'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='video',
            field=models.FileField(blank=True, help_text='шир. - 1920, выс. - 1080, размер - до 21 мб', upload_to='p/pgs/v', verbose_name='Видео (деск.)'),
        ),
        migrations.AlterField(
            model_name='projectgalleryslide',
            name='video_mobile',
            field=models.FileField(blank=True, help_text='шир - 320, выс. - 500, размер - до 5 мб', upload_to='p/pgs/vm', verbose_name='Видео (моб.)'),
        ),
    ]
