# Generated by Django 3.0.14 on 2022-01-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0104_project_dvizh_uuid'),
        ('projects', '0104_auto_20220119_1833'),
    ]

    operations = [
    ]
