# Generated by Django 3.0.14 on 2022-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0104_auto_20220119_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_panel_manager",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="p/p/ipm",
                verbose_name="Изображение на главном экране",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="show_in_panel_manager",
            field=models.BooleanField(default=True, verbose_name="Показывать в панеле мендежера"),
        ),
    ]
