# Generated by Django 3.0.10 on 2022-02-08 11:38

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0104_auto_20220119_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectadvantageslide',
            name='image_laptop',
            field=ajaximage.fields.AjaxImageField(blank=True, verbose_name='Изображение (планшет.)'),
        ),
        migrations.AddField(
            model_name='projectadvantageslide',
            name='image_mob',
            field=ajaximage.fields.AjaxImageField(blank=True, verbose_name='Изображение (моб.)'),
        ),
    ]
