# Generated by Django 3.0.14 on 2022-02-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0105_auto_20220210_1514"),
        ("projects", "0105_auto_20220208_1438"),
    ]

    operations = []
