# Generated by Django 3.0.14 on 2022-02-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0105_merge_20220128_1715"),
        ("projects", "0106_merge_20220214_1537"),
    ]

    operations = []
