# Generated by Django 3.0.14 on 2022-02-25 07:47

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_merge_20220221_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadvantageslide',
            name='image',
            field=ajaximage.fields.AjaxImageField(help_text='Выс.- 1200, Шир.- 1560', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='projectadvantageslide',
            name='image_laptop',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='Выс.- 368, Шир.- 768', verbose_name='Изображение (планшет.)'),
        ),
        migrations.AlterField(
            model_name='projectadvantageslide',
            name='image_mob',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='Выс.- 350, Шир.- 390', verbose_name='Изображение (моб.)'),
        ),
    ]
