# Generated by Django 3.0.14 on 2022-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0108_auto_20220225_1047"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_redirect",
            field=models.BooleanField(default=False, verbose_name="Функционал перехода"),
        ),
        migrations.AddField(
            model_name="project",
            name="redirect_link",
            field=models.URLField(blank=True, verbose_name="Ссылка для перехода"),
        ),
    ]
