# Generated by Django 3.0.14 on 2022-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0109_auto_20220404_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="button_is_redirect",
            field=models.BooleanField(default=False, verbose_name="Функционал перехода по кнопке"),
        ),
        migrations.AddField(
            model_name="project",
            name="button_link",
            field=models.URLField(blank=True, verbose_name="Ссылка для перехода по кнопке"),
        ),
        migrations.AddField(
            model_name="project",
            name="button_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Название кнопки"),
        ),
    ]
