# Generated by Django 3.0.14 on 2022-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0110_auto_20220413_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="auto_update_label",
            field=models.BooleanField(default=True, verbose_name="Aвтообновление лейбла"),
        ),
    ]
