# Generated by Django 3.0.14 on 2022-04-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_project_auto_update_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_furnish',
            field=models.BooleanField(default=True, verbose_name='Отделка'),
        ),
    ]
