# Generated by Django 3.0.14 on 2022-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_project_is_furnish'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='panorama_front_door_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для панорамы парадной'),
        ),
        migrations.AddField(
            model_name='project',
            name='panorama_yard_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для панорамы двора'),
        ),
    ]
