# Generated by Django 3.0.14 on 2022-05-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_auto_20220504_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='panorama_front_door_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='panorama_yard_link',
        ),
    ]
