# Generated by Django 3.0.14 on 2022-05-20 08:22

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_auto_20220504_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 3200, выс. - 1900, размер - до 1,5 мб', null=True, verbose_name='Изображение десктоп (большое)')),
                ('image_desktop_small', models.ImageField(blank=True, help_text='шир. - 1830, выс. - 1168, размер - до 1 мб', null=True, upload_to='p/gallery/', verbose_name='Изображение десктоп (маленькое)')),
                ('image_tablet', models.ImageField(blank=True, help_text='шир. - 1152, выс. - 811, размер - до 750 кб', null=True, upload_to='p/gallery', verbose_name='Изображение планшет')),
                ('image_phone', models.ImageField(blank=True, help_text='шир. - 1280, выс. - 1568, размер - до 430 кб', null=True, upload_to='p/gallery', verbose_name='Изображение телефон')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ('order',),
            },
        ),
    ]
