# Generated by Django 3.0.14 on 2022-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0115_projectgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectGallery',
        ),
    ]
