# Generated by Django 3.0.14 on 2022-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0116_delete_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для презентации'),
        ),
    ]
