# Generated by Django 3.0.14 on 2022-06-29 09:17

import ajaximage.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_project_presentation_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='presentation_link',
        ),
        migrations.AddField(
            model_name='project',
            name='mini_map',
            field=ajaximage.fields.AjaxImageField(blank=True, validators=[django.core.validators.FileExtensionValidator(('png', 'svg'))], verbose_name='Мини-карта'),
        ),
        migrations.AddField(
            model_name='project',
            name='polygon_in_map',
            field=models.TextField(blank=True, verbose_name='Обводка на карте'),
        ),
        migrations.AddField(
            model_name='project',
            name='tour_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для 3D тура'),
        ),
    ]
