# Generated by Django 3.0.14 on 2022-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0119_project_furnish_kitchen_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_furnish_kitchen',
            field=models.BooleanField(default=True, verbose_name='Отделка кухни'),
        ),
    ]
