# Generated by Django 3.0.14 on 2022-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0121_auto_20220708_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commercial_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Коммерция'),
        ),
    ]
