# Generated by Django 3.0.14 on 2022-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0131_auto_20220804_1602'),
        ('projects', '0122_project_commercial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='furnish_furniture_set',
            field=models.ManyToManyField(blank=True, to='properties.FurnishFurniture', verbose_name='Варианты отделки мебели'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_furnish_furniture',
            field=models.BooleanField(default=False, verbose_name='Отделка мебели'),
        ),
    ]
