# Generated by Django 3.0.14 on 2022-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0123_auto_20220804_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_button_presentation',
            field=models.BooleanField(default=False, verbose_name='Кнопка регистрации на презентацию'),
        ),
    ]
