# Generated by Django 3.0.14 on 2022-10-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0124_project_is_button_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_choice_desc',
            field=models.TextField(blank=True, verbose_name="Описание блока 'Выбор за вами'"),
        ),
        migrations.AddField(
            model_name='project',
            name='business_choice_img',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/bus', verbose_name="Изображение блока 'Выбор за вами'"),
        ),
        migrations.AddField(
            model_name='project',
            name='business_choice_title',
            field=models.CharField(blank=True, max_length=200, verbose_name="Заголовок блока 'Выбор за вами'"),
        ),
        migrations.AddField(
            model_name='project',
            name='business_pantry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество кладовых'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_pantry_desc',
            field=models.TextField(blank=True, verbose_name='Описание блока Кладовые'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_pantry_img',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/bus', verbose_name='Изображение блока Кладовые'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_pantry_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Кладовые'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_parking_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество паркинга'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_parking_desc',
            field=models.TextField(blank=True, verbose_name='Описание блока Паркинг'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_parking_img',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/bus', verbose_name='Изображение блока Паркинг'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_parking_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Паркинг'),
        ),
    ]
