# Generated by Django 3.0.14 on 2022-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0125_auto_20221011_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='Включить бизнес шаблон'),
        ),
    ]
