# Generated by Django 3.0.14 on 2022-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0126_project_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_single_building',
            field=models.BooleanField(default=False, help_text='используется для разметки секций на генплане ЖК', verbose_name='Проект только с одним зданием'),
        ),
    ]
