# Generated by Django 3.0.14 on 2022-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0127_project_is_single_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_business',
        ),
        migrations.AddField(
            model_name='project',
            name='template_type',
            field=models.CharField(choices=[('business', 'Бизнес'), ('comfort', 'Комфорт')], default='comfort', max_length=20, verbose_name='Тип шаблона'),
        ),
    ]
