# Generated by Django 3.0.14 on 2022-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0129_auto_20221021_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_flats_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Квартиры'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_office_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Офисы продаж'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_purchase_methods_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Способы покупки'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_special_offers_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Акции'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_video_tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/fi', verbose_name="Картинка в блоке 'Видеоэкскурсия'"),
        ),
        migrations.AddField(
            model_name='project',
            name='business_video_tour_text',
            field=models.CharField(blank=True, max_length=200, verbose_name="Текст в блоке 'Видеоэкскурсия'"),
        ),
        migrations.AddField(
            model_name='project',
            name='business_video_tour_title',
            field=models.CharField(blank=True, max_length=200, verbose_name="Заголовок в блоке 'Видеоэкскурсия'"),
        ),
        migrations.AddField(
            model_name='project',
            name='furnish_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок для Отделки'),
        ),
        migrations.AddField(
            model_name='project',
            name='tour_img',
            field=models.ImageField(blank=True, null=True, upload_to='p/p/tour', verbose_name='Изображение 3D тура'),
        ),
        migrations.AddField(
            model_name='project',
            name='tour_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст 3D тура'),
        ),
        migrations.AddField(
            model_name='project',
            name='tour_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок 3D тура'),
        ),
    ]
