# Generated by Django 3.0.14 on 2022-11-10 09:58

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0130_auto_20221108_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_benefits_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока Преимущества'),
        ),
        migrations.CreateModel(
            name='ProjectFeatureSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', ajaximage.fields.AjaxImageField(help_text='Выс.- 1200, Шир.- 1560', verbose_name='Изображение')),
                ('image_mob', ajaximage.fields.AjaxImageField(blank=True, help_text='Выс.- 350, Шир.- 390', verbose_name='Изображение (моб.)')),
                ('image_laptop', ajaximage.fields.AjaxImageField(blank=True, help_text='Выс.- 368, Шир.- 768', verbose_name='Изображение (планшет.)')),
                ('description', models.TextField(blank=True, max_length=30, verbose_name='Опиание изображения')),
                ('image_position', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа'), ('center', 'Центр'), ('bottom', 'Снизу')], default='center', max_length=20, verbose_name='Положение изображения')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('project_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_slides', to='projects.ProjectFeature', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Слайд особености',
                'verbose_name_plural': 'Слайды особенности',
                'ordering': ('order',),
            },
        ),
    ]