# Generated by Django 3.0.14 on 2022-12-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0131_auto_20221110_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about_furnish',
            field=models.FileField(blank=True, null=True, upload_to='p/about_pdf', verbose_name='Об обтделке'),
        ),
        migrations.AddField(
            model_name='project',
            name='about_furniture',
            field=models.FileField(blank=True, null=True, upload_to='p/about_pdf', verbose_name='О мебели'),
        ),
        migrations.AddField(
            model_name='project',
            name='about_kitchen',
            field=models.FileField(blank=True, null=True, upload_to='p/about_pdf', verbose_name='О кухне'),
        ),
    ]
