# Generated by Django 3.0.14 on 2022-12-12 12:24

from django.db import migrations


def fill_image_panel_manager(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    projects = Project.objects.all()
    for project in projects:
        project.image_panel_manager = project.image
    Project.objects.bulk_update(projects, ['image_panel_manager'])


def backwards(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Project.objects.update(image_panel_manager=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0132_auto_20221206_1656'),
    ]

    operations = [
        migrations.RunPython(fill_image_panel_manager, backwards)
    ]
