# Generated by Django 3.0.10 on 2020-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/o/i", verbose_name="Иконка"
            ),
        ),
        migrations.AddField(
            model_name="subdivision",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/s/i", verbose_name="Иконка"
            ),
        ),
    ]
