# Generated by Django 3.0.10 on 2020-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_project_card_image"),
        ("contacts", "0002_auto_20201009_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="projects",
            field=models.ManyToManyField(to="projects.Project", verbose_name="Проекты"),
        ),
    ]
