# Generated by Django 3.0.10 on 2020-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_office_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("link", models.URLField(max_length=100, verbose_name="Ссылка")),
                (
                    "icon",
                    models.FileField(
                        blank=True, null=True, upload_to="c/s/i", verbose_name="Иконка"
                    ),
                ),
                (
                    "icon_content",
                    models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
                "ordering": ("order",),
            },
        ),
    ]
