# Generated by Django 3.0.10 on 2020-11-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="share_link",
            field=models.CharField(blank=True, max_length=1000, verbose_name="Ссылка для шеринга"),
        ),
    ]
