# Generated by Django 3.0.10 on 2020-11-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_social_share_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="colored_icon",
            field=models.FileField(
                blank=True, null=True, upload_to="c/s/ci", verbose_name="Цветная иконка"
            ),
        ),
        migrations.AddField(
            model_name="social",
            name="colored_icon_content",
            field=models.TextField(blank=True, null=True, verbose_name="Контент цветной иконки"),
        ),
    ]
