# Generated by Django 3.0.10 on 2020-11-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_office_is_central"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="office",
            options={
                "ordering": ("order",),
                "verbose_name": "Офис",
                "verbose_name_plural": "Офисы",
            },
        ),
        migrations.AddField(
            model_name="office",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Порядок"),
        ),
    ]
