# Generated by Django 3.0.10 on 2020-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20201123_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(max_length=1000, verbose_name='Ссылка'),
        ),
    ]
