# Generated by Django 3.0.10 on 2021-06-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cities", "0023_city_disable_site"), ("contacts", "0009_auto_20201123_1512")]

    operations = [
        migrations.AddField(
            model_name="office",
            name="cities",
            field=models.ManyToManyField(blank=True, to="cities.City", verbose_name="Города"),
        ),
        migrations.AlterField(
            model_name="office",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cities.City",
                verbose_name="Город",
            ),
        ),
    ]
