# Generated by Django 3.0.10 on 2021-06-25 08:00

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Office = apps.get_model("contacts", "Office")

    for office in Office.objects.using(db_alias).all():
        office.cities.add(office.city)


def reverse(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Office = apps.get_model("contacts", "Office")

    for office in Office.objects.using(db_alias).all():
        office.cities.clear()


class Migration(migrations.Migration):

    dependencies = [("contacts", "0010_auto_20210625_1058")]

    operations = [migrations.RunPython(forwards, reverse_code=reverse)]
