# Generated by Django 3.0.10 on 2021-06-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("contacts", "0011_dump_cities")]

    operations = [migrations.RemoveField(model_name="office", name="city")]
