# Generated by Django 3.0.10 on 2021-07-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cities", "0023_city_disable_site"), ("contacts", "0012_remove_office_city")]

    operations = [
        migrations.AddField(
            model_name="office",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="Выводится на карточке офиса. Если не заполнен, выводятся 'Города'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cities.City",
                verbose_name="Город",
            ),
        )
    ]
