# Generated by Django 3.0.10 on 2022-02-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_office_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_commercial',
            field=models.BooleanField(default=False, help_text='Выводить офис на странице коммерции проекта', verbose_name='Коммерческий'),
        ),
    ]
