# Generated by Django 3.0.14 on 2022-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0027_auto_20220225_1126"),
        ("projects", "0110_auto_20220413_1230"),
        ("contacts", "0014_office_is_commercial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="cities",
            field=models.ManyToManyField(
                blank=True, null=True, to="cities.City", verbose_name="Города"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="projects",
            field=models.ManyToManyField(
                blank=True, null=True, to="projects.Project", verbose_name="Проекты"
            ),
        ),
    ]
