# Generated by Django 3.0.14 on 2022-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('projects', '0123_auto_20220804_1602'),
        ('contacts', '0015_auto_20220414_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cities.City', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='office',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Проекты'),
        ),
    ]
