# Generated by Django 3.0.7 on 2020-07-02 14:14

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Очередность"),),
            ],
            options={
                "verbose_name": "Категория документа",
                "verbose_name_plural": "Категории докуметов",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=200, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(blank=True, max_length=200, verbose_name="Отчество"),
                ),
                ("position", models.CharField(max_length=200, verbose_name="Должность"),),
                (
                    "image",
                    ajaximage.fields.AjaxImageField(
                        help_text="шир. - 364, выс. - 467", verbose_name="Фотография"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Персона",
                "verbose_name_plural": "Персоны",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="TenderCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Очередность"),),
            ],
            options={
                "verbose_name": "Категория тендеров",
                "verbose_name_plural": "Категории тендеров",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="VacancyCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Очередность"),),
            ],
            options={
                "verbose_name": "Категория вакансии",
                "verbose_name_plural": "Категории вакансий",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200, verbose_name="Должность"),),
                ("announcement", ckeditor.fields.RichTextField(blank=True, verbose_name="Анонс"),),
                ("duties", ckeditor.fields.RichTextField(blank=True, verbose_name="Обязанности"),),
                (
                    "requirements",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Требования"),
                ),
                ("conditions", ckeditor.fields.RichTextField(blank=True, verbose_name="Условия "),),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Очередность"),),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.VacancyCategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("announcement", ckeditor.fields.RichTextField(blank=True, verbose_name="Анонс"),),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Очередность"),),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.TenderCategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тендер",
                "verbose_name_plural": "Тендеры",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата размещения")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("file", models.FileField(upload_to="document/file", verbose_name="Файл"),),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.DocumentCategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ("-date",),
            },
        ),
    ]
