# Generated by Django 3.0.10 on 2020-10-01 13:42

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),),
                (
                    "advantages_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Преимущества / Заголовок",
                    ),
                ),
                (
                    "advantages_button_text_1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Преимущества / Текст кнопки 1",
                    ),
                ),
                (
                    "advantages_button_text_2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Преимущества / Текст кнопки 2",
                    ),
                ),
                ("video", models.CharField(blank=True, max_length=2000, verbose_name="Видео"),),
                (
                    "video_preview",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Видео / Превью"
                    ),
                ),
                (
                    "video_title",
                    models.CharField(blank=True, max_length=200, verbose_name="Видео / Заголовок"),
                ),
                (
                    "video_description",
                    models.TextField(blank=True, verbose_name="Видео / Описание"),
                ),
            ],
            options={
                "verbose_name": "Страница вакансий",
                "verbose_name_plural": "Страница вакансий",
            },
        ),
        migrations.RenameField(model_name="vacancycategory", old_name="title", new_name="name",),
        migrations.AddField(
            model_name="vacancy",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата добавления"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="work_format",
            field=models.CharField(
                choices=[("remotely", "Удаленно"), ("office", "Работа из офиса")],
                default="office",
                max_length=20,
                verbose_name="Формат работы",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Очередность"),
        ),
        migrations.CreateModel(
            name="VacancyRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер"
                    ),
                ),
                ("resume", models.FileField(blank=True, upload_to="", verbose_name="Резюме"),),
                ("message", models.TextField(blank=True, verbose_name="Сопроводительное письмо"),),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.Vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик на вакансию",
                "verbose_name_plural": "Отклики на вакансии",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="VacancyPageAdvantage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("icon", ajaximage.fields.AjaxImageField(blank=True, verbose_name="Иконка"),),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.VacancyPage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество вакансий",
                "verbose_name_plural": "Преимущества вакансий",
                "ordering": ("order",),
            },
        ),
    ]
