# Generated by Django 3.0.10 on 2020-10-02 12:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_auto_20201001_1342"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnersPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),),
            ],
            options={
                "verbose_name": "Страница партнерам",
                "verbose_name_plural": "Страница партнерам",
            },
        ),
        migrations.CreateModel(
            name="SaleRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер"
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(max_length=13, verbose_name="Кадастровый номер"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сопроводительное письмо"),),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки"),
                ),
            ],
            options={
                "verbose_name": "Заявка на продажу участка",
                "verbose_name_plural": "Заявки на продажу участка",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="SaleRequestDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="requests/sale", verbose_name="Файл"),),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_set",
                        to="company.SaleRequest",
                        verbose_name="Заявка на продажу участка",
                    ),
                ),
            ],
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы",},
        ),
        migrations.CreateModel(
            name="PartnersPageBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок"),),
                (
                    "link_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Текст ссылки"),
                ),
                (
                    "link_url",
                    models.CharField(blank=True, max_length=2000, verbose_name="URL ссылки"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.PartnersPage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок страницы партнеров",
                "verbose_name_plural": "Блоки страницы партнеров",
            },
        ),
    ]
