# Generated by Django 3.0.10 on 2020-10-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_partnerspage_partnerspageblock_salerequest_salerequestdocument",),
    ]

    operations = [
        migrations.RemoveField(model_name="salerequestdocument", name="request",),
        migrations.RemoveField(model_name="vacancyrequest", name="vacancy",),
        migrations.DeleteModel(name="SaleRequest",),
        migrations.DeleteModel(name="SaleRequestDocument",),
        migrations.DeleteModel(name="VacancyRequest",),
    ]
