# Generated by Django 3.0.10 on 2020-10-05 07:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_auto_20201002_1230"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=5000, null=True, verbose_name="Текст"
                    ),
                ),
                (
                    "offices",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Офисы"),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=1000, null=True, verbose_name="Описание офисов",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="c/a/i", verbose_name="Изображение",
                    ),
                ),
                (
                    "ideology_description",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=1000, null=True, verbose_name="Описание идеологии",
                    ),
                ),
                (
                    "ideology_text",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=1000, null=True, verbose_name="Текст идеологии",
                    ),
                ),
                (
                    "ideology_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="c/i/i",
                        verbose_name="Изображение идеологии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница о компании",
                "verbose_name_plural": "Страница о компании",
            },
        ),
        migrations.CreateModel(
            name="IdeologySlider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Текст"),),
                ("order", models.PositiveIntegerField(verbose_name="Порядок")),
                (
                    "about_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.AboutPage",
                        verbose_name="Идеология",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайдер идеологии",
                "verbose_name_plural": "Слайдеры идеологии",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="IdeologyCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Текст"),),
                ("image", models.ImageField(upload_to="c/c/i", verbose_name="Изображение"),),
                ("order", models.PositiveIntegerField(verbose_name="Порядок")),
                (
                    "about_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.AboutPage",
                        verbose_name="Идеология",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка идеологии",
                "verbose_name_plural": "Карточки идеологии",
                "ordering": ("order",),
            },
        ),
    ]
