# Generated by Django 3.0.10 on 2020-10-19 11:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_aboutpage_ideologycard_ideologyslider"),
    ]

    operations = [
        migrations.RemoveField(model_name="aboutpage", name="text",),
        migrations.AddField(
            model_name="aboutpage",
            name="text_1",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=5000, null=True, verbose_name="Текст 1"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="text_2",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=5000, null=True, verbose_name="Текст 2"
            ),
        ),
    ]
