# Generated by Django 3.0.10 on 2020-10-29 09:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_auto_20201019_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerspage",
            name="partners",
            field=models.PositiveIntegerField(default=11, verbose_name="Партнеры"),
        ),
        migrations.AddField(
            model_name="partnerspage",
            name="partners_description",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=1000, null=True, verbose_name="Описание партнеров"
            ),
        ),
        migrations.AddField(
            model_name="vacancypage",
            name="vacancies",
            field=models.PositiveIntegerField(default=11, verbose_name="Вакансии"),
        ),
        migrations.AddField(
            model_name="vacancypage",
            name="vacancies_description",
            field=ckeditor.fields.RichTextField(
                blank=True, max_length=1000, null=True, verbose_name="Описание вакансий"
            ),
        ),
    ]
