# Generated by Django 3.0.10 on 2020-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_auto_20201029_0953"),
    ]

    operations = [
        migrations.RemoveField(model_name="ideologycard", name="image",),
        migrations.AddField(
            model_name="ideologycard",
            name="image_one",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/c/i1", verbose_name="Изображение 1"
            ),
        ),
        migrations.AddField(
            model_name="ideologycard",
            name="image_two",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/c/i2", verbose_name="Изображение 2"
            ),
        ),
        migrations.AddField(
            model_name="ideologyslider",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ap/is/i", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="offices",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Офисы"),
        ),
    ]
