# Generated by Django 3.0.10 on 2020-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_auto_20201030_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerspage",
            name="partners",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Партнеры"),
        ),
        migrations.AlterField(
            model_name="vacancypage",
            name="vacancies",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Вакансии"),
        ),
    ]
