# Generated by Django 3.0.10 on 2020-10-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_auto_20201030_0938"),
    ]

    operations = [
        migrations.RenameField(model_name="ideologycard", old_name="image_one", new_name="image",),
        migrations.RemoveField(model_name="aboutpage", name="ideology_image",),
        migrations.RemoveField(model_name="ideologycard", name="image_two",),
        migrations.AddField(
            model_name="aboutpage",
            name="ideology_image_one",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/i/i", verbose_name="Изображение идеологии 1"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="ideology_image_two",
            field=models.ImageField(
                blank=True, null=True, upload_to="c/i/i", verbose_name="Изображение идеологии 2"
            ),
        ),
    ]
