# Generated by Django 3.0.10 on 2020-11-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_auto_20201030_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideologycard",
            name="about_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.AboutPage",
                verbose_name="Страница о компании",
            ),
        ),
        migrations.AlterField(
            model_name="ideologyslider",
            name="about_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.AboutPage",
                verbose_name="Страница о компании",
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Значение")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("subtitle", models.CharField(max_length=50, verbose_name="Подзаголовок")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                (
                    "about_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.AboutPage",
                        verbose_name="Страница о компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
                "ordering": ("order",),
            },
        ),
    ]
