# Generated by Django 3.0.10 on 2020-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_auto_20201102_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="ideology_video_one",
            field=models.URLField(blank=True, null=True, verbose_name="Видео идеологии 1"),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="ideology_video_two",
            field=models.URLField(blank=True, null=True, verbose_name="Видео идеологии 2"),
        ),
    ]
