# Generated by Django 3.0.10 on 2020-11-06 14:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_auto_20201102_1145"),
    ]

    operations = [
        migrations.RemoveField(model_name="partnerspage", name="text",),
        migrations.RemoveField(model_name="vacancypage", name="text",),
        migrations.AddField(
            model_name="partnerspage",
            name="text_1",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание 1"),
        ),
        migrations.AddField(
            model_name="partnerspage",
            name="text_2",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание 2"),
        ),
        migrations.AddField(
            model_name="vacancypage",
            name="text_1",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание 1"),
        ),
        migrations.AddField(
            model_name="vacancypage",
            name="text_2",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание 2"),
        ),
    ]
