# Generated by Django 3.0.10 on 2020-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_auto_20201106_1425"),
    ]

    operations = [
        migrations.RemoveField(model_name="vacancypage", name="advantages_title",),
        migrations.AddField(
            model_name="vacancypage",
            name="advantages_title_1",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Преимущества / Заголовок 1"
            ),
        ),
        migrations.AddField(
            model_name="vacancypage",
            name="advantages_title_2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Преимущества / Заголовок 2"
            ),
        ),
    ]
