# Generated by Django 3.0.10 on 2020-11-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0012_auto_20201112_1359"),
        ("company", "0015_auto_20201111_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="buildings.Building",
                verbose_name="Корпус",
            ),
        ),
    ]
