# Generated by Django 3.0.10 on 2020-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0006_auto_20201118_1307"),
        ("company", "0016_document_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="map_texts",
            field=models.ManyToManyField(
                blank=True, to="main_page.MapText", verbose_name="Тексты для карты"
            ),
        ),
    ]
