# Generated by Django 3.0.10 on 2020-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_offersdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerspageblock',
            name='block_type',
            field=models.CharField(blank=True, choices=[('agent', 'Агент'), ('bank', 'Банк'), ('sale_plot', 'Продажа земельного участка'), ('contractor', 'Подрядчик')], max_length=300, verbose_name='Тип блока'),
        ),
    ]
