# Generated by Django 3.0.10 on 2020-11-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0019_partnerspageblock_block_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LargeTenant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="ap/lt/l", verbose_name="Логотип"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "about_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.AboutPage",
                        verbose_name="Страница о компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Крупный арендатор",
                "verbose_name_plural": "Крупные арендаторы",
                "ordering": ("order",),
            },
        ),
    ]
