# Generated by Django 3.0.10 on 2020-11-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0021_auto_20201123_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancypageform",
            name="image_phone",
            field=models.ImageField(
                blank=True, null=True, upload_to="f/ip", verbose_name="Изображение телефон"
            ),
        ),
    ]
