# Generated by Django 3.0.10 on 2020-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0022_vacancypageform_image_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancypageform",
            name="yandex_metrics",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Яндекс метрика"
            ),
        ),
    ]
