# Generated by Django 3.0.10 on 2021-01-31 16:48

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_vacancy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, choices=[('director', 'Директор'), ('manager', 'Менеджер')], max_length=32, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_hover',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 364, выс. - 467', verbose_name='Фотография при ховере'),
        ),
    ]
