# Generated by Django 3.0.10 on 2021-02-03 13:47

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20210131_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_popup',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 364, выс. - 467', verbose_name='Фотография в модальном окне'),
        ),
    ]
