# Generated by Django 3.0.10 on 2021-03-03 11:29

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_person_image_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                (
                    'about_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='company.AboutPage',
                        verbose_name='Страница о компании',
                    ),
                ),
            ],
            options={
                'verbose_name': 'История о компании',
                'verbose_name_plural': 'Истории о компании',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                (
                    'story',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='company.Story',
                        verbose_name='История',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение истории о компании',
                'verbose_name_plural': 'Изображения истории о компании',
                'ordering': ('order',),
            },
        ),
    ]
