# Generated by Django 3.0.10 on 2021-03-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_story_storyimage'),
        ('company', '0028_vacancypageformemployee'),
    ]

    operations = [
    ]
