# Generated by Django 3.0.10 on 2021-03-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_merge_20210303_1626'),
        ('company', '0029_vacancypageform_google_event_name'),
    ]

    operations = [
    ]
