# Generated by Django 3.0.10 on 2021-03-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_vacancypageform_google_event_name'),
        ('company', '0029_story_file'),
    ]

    operations = [
    ]
