# Generated by Django 3.0.10 on 2021-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_vacancypageform_google_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerspageblock',
            name='block_type',
            field=models.CharField(blank=True, choices=[('bank', 'Банк'), ('agent', 'Агент'), ('contractor', 'Подрядчик'), ('sale_plot', 'Продажа земельного участка'), ('media', 'Блок для СМИ')], max_length=300, verbose_name='Тип блока'),
        ),
    ]
