# Generated by Django 3.0.10 on 2021-03-12 11:21

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_merge_20210310_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.AboutPage', verbose_name='Страница о компании')),
            ],
            options={
                'verbose_name': 'Ценность компании',
                'verbose_name_plural': 'Ценности компании',
                'ordering': ('order',),
            },
        ),
    ]
