# Generated by Django 3.0.10 on 2021-03-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_merge_20210309_1608'),
        ('company', '0030_merge_20210310_1343'),
    ]

    operations = [
    ]
