# Generated by Django 3.0.10 on 2021-03-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20210318_1352'),
        ('company', '0031_companyvalue'),
    ]

    operations = [
    ]
