# Generated by Django 3.0.10 on 2021-03-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_companyvalue'),
        ('company', '0031_merge_20210310_1408'),
    ]

    operations = [
    ]
