# Generated by Django 3.0.10 on 2021-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_merge_20210312_1227'),
        ('company', '0030_auto_20210318_1352'),
    ]

    operations = [
    ]
