# Generated by Django 3.0.10 on 2021-03-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_merge_20210318_1355'),
        ('company', '0032_merge_20210324_1347'),
    ]

    operations = [
    ]
