# Generated by Django 3.0.10 on 2021-05-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_merge_20210409_1631"),
        ("company", "0034_merge_20210324_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        )
    ]
