# Generated by Django 3.0.10 on 2021-05-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("company", "0035_auto_20210527_1455")]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_investors",
            field=models.BooleanField(default=False, verbose_name="Вывести на страницу инвесторам"),
        )
    ]
