# Generated by Django 3.0.10 on 2021-06-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_merge_20210409_1631"),
        ("company", "0036_document_is_investors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Отображается во всех городах, если не указан проект.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        )
    ]
