# Generated by Django 3.0.10 on 2021-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_auto_20210607_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='StableDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=120, verbose_name='Постоянное название документа')),
                ('file', models.FileField(upload_to='stable_document', verbose_name='Файл')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Файл со стабильной ссылкой',
                'verbose_name_plural': 'Файлы со стабильной ссылкой',
            },
        ),
    ]
