# Generated by Django 3.0.14 on 2021-12-24 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_stabledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='credit_rating',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Кредитный рейтинг'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='credit_rating_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Описание кредитного рейтинга'),
        ),
    ]
