# Generated by Django 3.0.14 on 2022-06-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('company', '0039_auto_20211224_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='city',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.ManyToManyField(blank=True, to='cities.City', verbose_name='Города'),
        ),
    ]
