# Generated by Django 3.0.14 on 2022-07-04 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_auto_20220627_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBoxesTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('number_1', models.PositiveIntegerField(verbose_name='Число 1')),
                ('number_2', models.PositiveIntegerField(verbose_name='Число 2')),
                ('number_3', models.PositiveIntegerField(verbose_name='Число 3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке')),
            ],
        ),
    ]
