# Generated by Django 3.0.14 on 2022-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_about_banner_checkboxes_checkboxestitle_map_secondbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='block_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела'),
        ),
    ]
