# Generated by Django 3.0.14 on 2022-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_auto_20220704_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='block_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='map',
            name='number_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число 1'),
        ),
        migrations.AlterField(
            model_name='map',
            name='number_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число 2'),
        ),
        migrations.AlterField(
            model_name='map',
            name='number_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число 3'),
        ),
        migrations.AlterField(
            model_name='secondbanner',
            name='block_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела'),
        ),
    ]
