# Generated by Django 3.0.14 on 2022-07-05 08:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_auto_20220704_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevLandThirdBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
            options={
                'verbose_name': 'Третий Баннер',
                'verbose_name_plural': 'Третий Баннеры',
            },
        ),
        migrations.RenameModel(
            old_name='About',
            new_name='DevLandAbout',
        ),
        migrations.RenameModel(
            old_name='Banner',
            new_name='DevLandBanner',
        ),
        migrations.RenameModel(
            old_name='CheckBoxes',
            new_name='DevLandCheckBoxes',
        ),
        migrations.RenameModel(
            old_name='CheckBoxesTitle',
            new_name='DevLandCheckBoxesTitle',
        ),
        migrations.RenameModel(
            old_name='Map',
            new_name='DevLandMap',
        ),
        migrations.RenameModel(
            old_name='SecondBanner',
            new_name='DevLandSecondBanner',
        ),
        migrations.AlterModelOptions(
            name='devlandabout',
            options={'verbose_name': 'Главный Блок', 'verbose_name_plural': 'Главные Блоки'},
        ),
        migrations.AlterModelOptions(
            name='devlandbanner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='devlandcheckboxes',
            options={'verbose_name': 'Чекбокс', 'verbose_name_plural': 'Чекбоксы'},
        ),
        migrations.AlterModelOptions(
            name='devlandcheckboxestitle',
            options={'verbose_name': 'Описание чекбоксов', 'verbose_name_plural': 'Описание чекбоксов'},
        ),
        migrations.AlterModelOptions(
            name='devlandmap',
            options={'verbose_name': 'Данные на карте', 'verbose_name_plural': 'Данные на карте'},
        ),
        migrations.AlterModelOptions(
            name='devlandsecondbanner',
            options={'verbose_name': 'Второй Баннер', 'verbose_name_plural': 'Вторые Баннеры'},
        ),
    ]
