# Generated by Django 3.0.14 on 2022-07-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_auto_20220705_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevLandAbout',
        ),
        migrations.DeleteModel(
            name='DevLandBanner',
        ),
        migrations.DeleteModel(
            name='DevLandCheckBoxes',
        ),
        migrations.DeleteModel(
            name='DevLandCheckBoxesTitle',
        ),
        migrations.DeleteModel(
            name='DevLandMap',
        ),
        migrations.DeleteModel(
            name='DevLandSecondBanner',
        ),
        migrations.DeleteModel(
            name='DevLandThirdBanner',
        ),
    ]
