# Generated by Django 3.0.10 on 2020-09-29 12:32

import ckeditor.fields
import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_auto_20200929_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfraCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название типа"),),
                ("color", colorful.fields.RGBColorField(default="#FFFFFF", verbose_name="Цвет"),),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="infratype/icon",
                        verbose_name="Иконка для списка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Категория инфраструктуры",
                "verbose_name_plural": "Категории инфраструктуры",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Infra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(blank=True, max_length=200, verbose_name="Адрес"),),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infras.InfraCategory",
                        verbose_name="Тип",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект инфраструктуры",
                "verbose_name_plural": "Объекты инфраструктуры",
            },
        ),
    ]
