# Generated by Django 3.0.10 on 2020-10-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="infras.InfraCategory",
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="InfraType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infras.InfraCategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип инфраструктуры",
                "verbose_name_plural": "Типы инфраструктуры",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="infra",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="infras.InfraType",
                verbose_name="Тип",
            ),
        ),
    ]
