# Generated by Django 3.0.10 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infras", "0002_auto_20201020_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="infracategory",
            name="icon_content",
            field=models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
        ),
    ]
