# Generated by Django 3.0.10 on 2020-10-30 13:29

import colorful.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_auto_20201030_1031"),
        ("infras", "0003_infracategory_icon_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainInfra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "type",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Тип"),
                ),
                (
                    "add_text",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Доп текст"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, verbose_name="Адрес")),
                ("color", colorful.fields.RGBColorField(default="#FFFFFF", verbose_name="Цвет")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="maininfra/icon",
                        verbose_name="Иконка для списка",
                    ),
                ),
                (
                    "icon_content",
                    models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
                ),
                (
                    "exploitation",
                    models.DateField(blank=True, null=True, verbose_name="Срок сдачи"),
                ),
                (
                    "point",
                    common.fields.PpoiField(
                        blank=True,
                        max_length=50,
                        null=True,
                        source="project.plan",
                        verbose_name="Точка на генплане",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная инфраструктура | Генплан",
                "verbose_name_plural": "Главные инфраструктура | Генплан",
            },
        ),
        migrations.AlterModelOptions(
            name="infra",
            options={
                "verbose_name": "Инфраструктура | Карта",
                "verbose_name_plural": "Инфраструктуры | Карта",
            },
        ),
        migrations.AlterModelOptions(
            name="infracategory",
            options={
                "ordering": ("order",),
                "verbose_name": "Категория инфраструктуры | Карта",
                "verbose_name_plural": "Категории инфраструктуры | Карта",
            },
        ),
        migrations.AlterModelOptions(
            name="infratype",
            options={
                "ordering": ("order",),
                "verbose_name": "Тип инфраструктуры | Карта",
                "verbose_name_plural": "Типы инфраструктуры | Карта",
            },
        ),
        migrations.AddField(
            model_name="infra",
            name="exploitation",
            field=models.DateField(blank=True, null=True, verbose_name="Срок сдачи"),
        ),
        migrations.AddField(
            model_name="infra",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Главная"),
        ),
        migrations.CreateModel(
            name="SubInfra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "type",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Тип"),
                ),
                (
                    "add_text",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Доп текст"
                    ),
                ),
                ("color", colorful.fields.RGBColorField(default="#FFFFFF", verbose_name="Цвет")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="subinfra/icon",
                        verbose_name="Иконка для списка",
                    ),
                ),
                (
                    "icon_content",
                    models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
                ),
                (
                    "point",
                    common.fields.PpoiField(
                        blank=True,
                        max_length=50,
                        null=True,
                        source="project.plan",
                        verbose_name="Точка на генплане",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительная инфраструктура | Генплан",
                "verbose_name_plural": "Дополнительные инфраструктуры | Генплан",
            },
        ),
        migrations.CreateModel(
            name="RoundInfra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "type",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Тип"),
                ),
                (
                    "add_text",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Доп текст"
                    ),
                ),
                ("color", colorful.fields.RGBColorField(default="#FFFFFF", verbose_name="Цвет")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="roundinfra/icon",
                        verbose_name="Иконка для списка",
                    ),
                ),
                (
                    "icon_content",
                    models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
                ),
                (
                    "point",
                    common.fields.PpoiField(
                        blank=True,
                        max_length=50,
                        null=True,
                        source="project.plan",
                        verbose_name="Точка на генплане",
                    ),
                ),
                ("is_metro", models.BooleanField(default=False, verbose_name="Метро")),
                (
                    "rotation",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Поворот иконки (в градусах)"
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Время до инфраструктуры",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Окружная инфраструктура | Генплан",
                "verbose_name_plural": "Окружные инфраструктуры | Генплан",
            },
        ),
        migrations.CreateModel(
            name="MainInfraContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("value", models.CharField(max_length=50, verbose_name="Значение")),
                (
                    "main_infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infras.MainInfra",
                        verbose_name="Главная инфраструктура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент главной инфраструктуры | Генплан",
                "verbose_name_plural": "Контенты главной инфраструктуры | Генплан",
            },
        ),
        migrations.CreateModel(
            name="InfraContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("value", models.CharField(max_length=50, verbose_name="Значение")),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infras.Infra",
                        verbose_name="Инфраструктура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент инфраструктуры | Карта",
                "verbose_name_plural": "Контенты инфраструктуры | Карта",
            },
        ),
    ]
