# Generated by Django 3.0.10 on 2020-10-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infras", "0004_auto_20201030_1329"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maininfra",
            options={
                "verbose_name": "Главная инфраструктура | Генплан",
                "verbose_name_plural": "Главные инфраструктуры | Генплан",
            },
        ),
    ]
