# Generated by Django 3.0.10 on 2021-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("infras", "0006_auto_20201211_1154")]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="main_type",
            field=models.CharField(
                choices=[("no", "Нет"), ("small", "Маленький пин"), ("big", "Большой пин")],
                default="no",
                max_length=24,
                verbose_name="Категория основное",
            ),
        )
    ]
