# Generated by Django 3.0.10 on 2021-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("infras", "0007_infra_main_type")]

    operations = [
        migrations.AddField(
            model_name="maininfra",
            name="is_open_left",
            field=models.BooleanField(default=False, verbose_name="Открывать инфраструктуру слева"),
        ),
        migrations.AddField(
            model_name="subinfra",
            name="is_open_left",
            field=models.BooleanField(default=False, verbose_name="Открывать инфраструктуру слева"),
        ),
    ]
