# Generated by Django 3.0.10 on 2021-07-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("infras", "0008_auto_20210517_1739")]

    operations = [
        migrations.AddField(
            model_name="subinfra",
            name="link",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Ссылка инфраструктуры"
            ),
        )
    ]
