# Generated by Django 3.0.14 on 2022-02-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infras", "0009_subinfra_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="show_in_panel",
            field=models.BooleanField(default=False, verbose_name="Показывать на панели менеджера"),
        ),
        migrations.AddField(
            model_name="infra",
            name="show_in_site",
            field=models.BooleanField(default=True, verbose_name="Активная инфраструктура"),
        ),
    ]
