# Generated by Django 3.0.14 on 2022-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_types', models.CharField(max_length=255, verbose_name='Вид инвестиций')),
                ('income', models.CharField(max_length=255, verbose_name='Доходность')),
                ('risks', models.CharField(max_length=255, verbose_name='Риски')),
                ('management_complexity', models.CharField(choices=[('easy', 'Просто'), ('medium', 'Средне'), ('hard', 'Сложно')], max_length=255, verbose_name='Сложность управления')),
                ('liquidity', models.CharField(choices=[('easy', 'Простая'), ('medium', 'Средняя'), ('hard', 'Высокая')], max_length=255, verbose_name='Ликвидность')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBusinessSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена объекта')),
                ('quadrature', models.FloatField(verbose_name='Квадратура')),
                ('month_rent', models.PositiveIntegerField(verbose_name='Аренда в месяц')),
                ('year_rent', models.PositiveIntegerField(verbose_name='Аренда в год')),
                ('payback', models.FloatField(verbose_name='Окупаемость')),
                ('in_percent', models.FloatField(verbose_name='% годовых')),
            ],
        ),
        migrations.CreateModel(
            name='YieldComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.CharField(max_length=255, verbose_name='Сдача в аренду')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('repair', models.PositiveIntegerField(verbose_name='Ремонт')),
                ('appliances_and_furniture', models.PositiveIntegerField(verbose_name='Мебель и техника')),
                ('attachments', models.PositiveIntegerField(verbose_name='Вложения')),
                ('rental_income', models.PositiveIntegerField(verbose_name='Доход от ренты')),
                ('payback', models.FloatField(verbose_name='Окупаемость')),
                ('in_percent', models.FloatField(verbose_name='% годовых')),
            ],
        ),
    ]
