# Generated by Django 3.0.14 on 2022-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldcomparison',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
