# Generated by Django 3.0.14 on 2022-07-04 10:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_yieldcomparison_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255, verbose_name='Название блока')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('icon', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
        ),
        migrations.CreateModel(
            name='LastBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('icon_1', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
                ('icon_2', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
                ('othertitle_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другой заголовок 1')),
                ('othertitle_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другой заголовок 2')),
                ('othersubtitle_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другой подзаголовок 1')),
                ('othersubtitle_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другой подзаголовок 2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
