# Generated by Django 3.0.14 on 2022-07-04 14:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20220704_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Главный баннер', 'verbose_name_plural': 'Главный баннер'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='investmenttypes',
            options={'verbose_name': 'Сравнение видов инвестиций', 'verbose_name_plural': 'Сравнение видов инвестиций'},
        ),
        migrations.AlterModelOptions(
            name='lastbanner',
            options={'verbose_name': 'Данные на третьем блоке', 'verbose_name_plural': 'Данные на третьем блоке'},
        ),
        migrations.AlterModelOptions(
            name='rentalbusinesssales',
            options={'verbose_name': 'Кейсы продажи арендного бизнеса', 'verbose_name_plural': 'Кейсы продажи арендного бизнеса'},
        ),
        migrations.AlterModelOptions(
            name='secondbanner',
            options={'verbose_name': 'Второй блок', 'verbose_name_plural': 'Второй блок'},
        ),
        migrations.AlterModelOptions(
            name='yieldcomparison',
            options={'verbose_name': 'Примеры сранения доходности', 'verbose_name_plural': 'Примеры сранений доходности'},
        ),
        migrations.AlterField(
            model_name='secondbanner',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
