# Generated by Django 3.0.14 on 2022-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_auto_20220705_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttypes',
            name='liquidity',
            field=models.CharField(choices=[('easy', 'Простая'), ('medium', 'Средняя'), ('hard', 'Высокая')], max_length=255, verbose_name='Ликвидность'),
        ),
        migrations.AlterField(
            model_name='investmenttypes',
            name='management_complexity',
            field=models.CharField(choices=[('easy', 'Просто'), ('medium', 'Средне'), ('hard', 'Сложно')], max_length=255, verbose_name='Сложность управления'),
        ),
    ]
