# Generated by Django 3.0.14 on 2022-07-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_auto_20220705_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='MainBanner',
        ),
        migrations.AlterField(
            model_name='investmenttypes',
            name='liquidity',
            field=models.CharField(choices=[('Простая', 'easy'), ('Средняя', 'medium'), ('Высокая', 'hard')], max_length=255, verbose_name='Ликвидность'),
        ),
        migrations.AlterField(
            model_name='investmenttypes',
            name='management_complexity',
            field=models.CharField(choices=[('Просто', 'easy'), ('Средне', 'medium'), ('Сложно', 'hard')], max_length=255, verbose_name='Сложность управления'),
        ),
    ]
