# Generated by Django 3.0.14 on 2022-07-07 07:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_auto_20220706_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnEyeLooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
                ('img_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание изображения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
