# Generated by Django 3.0.14 on 2022-07-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_owneyelooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owneyelooking',
            options={'verbose_name': 'Посмотрите своими глазами', 'verbose_name_plural': 'Посмотрите своими глазами'},
        ),
    ]
