# Generated by Django 3.0.14 on 2022-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_auto_20220707_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttypes',
            name='risks_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание рисков'),
        ),
    ]
