# Generated by Django 3.0.14 on 2022-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20220708_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmenttypes',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='yieldcomparison',
            name='checkin',
        ),
        migrations.AddField(
            model_name='investmenttypes',
            name='check_in',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Приоритет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmenttypes',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='rentalbusinesssales',
            name='check_in',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Приоритет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalbusinesssales',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='check_in',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Приоритет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
