# Generated by Django 3.0.14 on 2022-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_auto_20220715_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='in_percent',
            field=models.CharField(max_length=255, verbose_name='% годовых'),
        ),
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='month_rent',
            field=models.CharField(max_length=255, verbose_name='Аренда в месяц'),
        ),
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='payback',
            field=models.CharField(max_length=255, verbose_name='Окупаемость'),
        ),
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена объекта'),
        ),
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='quadrature',
            field=models.CharField(max_length=255, verbose_name='Квадратура'),
        ),
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='year_rent',
            field=models.CharField(max_length=255, verbose_name='Аренда в год'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='appliances_and_furniture',
            field=models.CharField(max_length=255, verbose_name='Мебель и техника'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='attachments',
            field=models.CharField(max_length=255, verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='in_percent',
            field=models.CharField(max_length=255, verbose_name='% годовых'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='payback',
            field=models.CharField(max_length=255, verbose_name='Окупаемость'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='quadrature',
            field=models.CharField(max_length=255, verbose_name='Квадратура'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='rental_income',
            field=models.CharField(max_length=255, verbose_name='Доход от ренты'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='repair',
            field=models.CharField(max_length=255, verbose_name='Ремонт'),
        ),
    ]
