# Generated by Django 3.0.14 on 2022-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_auto_20220718_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmenttypes',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='rentalbusinesssales',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='yieldcomparison',
            name='check_in',
        ),
        migrations.AddField(
            model_name='investmenttypes',
            name='checkin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='rentalbusinesssales',
            name='checkin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='appliances_and_furniture_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем медель и технику'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='attachments_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем вложения'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='checkin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='in_percent_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем % годовых'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='payback_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем окупаемость'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='price_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем стоимость'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='quadrature_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем квадратуру'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='rent_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем сдачу в аренду'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='rental_income_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем доход от ренты'),
        ),
        migrations.AddField(
            model_name='yieldcomparison',
            name='repair_show',
            field=models.BooleanField(default=False, verbose_name='Выделяем ремонт'),
        ),
        migrations.AlterField(
            model_name='investmenttypes',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='rentalbusinesssales',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='yieldcomparison',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
