# Generated by Django 3.0.10 on 2020-11-02 13:36

import ajaximage.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0015_auto_20201022_0743"),
        ("sites", "0002_alter_domain_unique"),
        ("cities", "0005_city_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название банка")),
                ("logo", ajaximage.fields.AjaxImageField(verbose_name="Логотип")),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Банк",
                "verbose_name_plural": "Банки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Программа ипотеки",
                "verbose_name_plural": "Программы ипотеки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активное")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("commercial", "Коммерческая ипотека"),
                            ("residential", "Жилая ипотека"),
                        ],
                        max_length=100,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "deposit",
                    common.fields.FloatRangeField(
                        blank=True, null=True, verbose_name="Первоначальный взнос"
                    ),
                ),
                (
                    "rate",
                    common.fields.FloatRangeField(
                        blank=True, null=True, verbose_name="Процентная ставка"
                    ),
                ),
                (
                    "term",
                    common.fields.FloatRangeField(
                        blank=True, null=True, verbose_name="Срок кредита"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                (
                    "amount",
                    common.fields.IntegerRangeField(
                        blank=True, null=True, verbose_name="Сумма кредита"
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mortgage.Bank",
                        verbose_name="Банк",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mortgage.Program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, to="projects.Project", verbose_name="Проекты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение по ипотеке",
                "verbose_name_plural": "Предложения по ипотеке",
                "ordering": ("order",),
                "get_latest_by": "rate",
            },
        ),
        migrations.CreateModel(
            name="MortgagePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                (
                    "button_text_1",
                    models.CharField(blank=True, max_length=100, verbose_name="Текст кнопки 1"),
                ),
                ("button_link_1", models.URLField(blank=True, verbose_name="Ссылка на кнопке 1")),
                (
                    "button_text_2",
                    models.CharField(blank=True, max_length=100, verbose_name="Текст кнопки 2"),
                ),
                ("button_link_2", models.URLField(blank=True, verbose_name="Ссылка на кнопке 2")),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница ипотеки",
                "verbose_name_plural": "Страницы ипотеки",
            },
        ),
        migrations.CreateModel(
            name="MortgageInstrument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Изображение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="mortgage.MortgagePage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка ипотечных инструментов",
                "verbose_name_plural": "Карточки ипотечных инструментов",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="MortgageAdvantage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "icon",
                    ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name="Иконка"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantages",
                        to="mortgage.MortgagePage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество ипотеки",
                "verbose_name_plural": "Преимущества ипотеки",
                "ordering": ("order",),
            },
        ),
    ]
