# Generated by Django 3.0.10 on 2020-11-06 06:16

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortgage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="mortgageadvantage", name="icon",),
        migrations.AddField(
            model_name="mortgageadvantage",
            name="icon_content",
            field=models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
        ),
        migrations.AlterField(
            model_name="mortgageinstrument",
            name="image",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 293, выс. - 232",
                null=True,
                verbose_name="Изображение",
            ),
        ),
    ]
