# Generated by Django 3.0.10 on 2020-12-05 12:20

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_mortgagepageform_image_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageinstrument',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 486, выс. - 464', null=True, verbose_name='Изображение'),
        ),
    ]
