# Generated by Django 3.0.10 on 2020-12-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("mortgage", "0007_mortgagepageform_yandex_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortgageadvantage",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advantages",
                to="mortgage.MortgagePage",
                verbose_name="Страница ипотеки",
            ),
        ),
        migrations.AlterField(
            model_name="mortgageinstrument",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruments",
                to="mortgage.MortgagePage",
                verbose_name="Страница ипотеки",
            ),
        ),
        migrations.AlterField(
            model_name="mortgagepage",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="Сайт",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
    ]
