# Generated by Django 3.0.10 on 2021-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0009_auto_20210210_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageadvantage',
            name='formattable_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок с форматированием'),
        ),
        migrations.AddField(
            model_name='mortgagepage',
            name='formattable_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок с форматированием'),
        ),
    ]
