# Generated by Django 3.0.10 on 2021-02-26 11:40

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20210122_1455'),
        ('mortgage', '0010_auto_20210210_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgagePageFormEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1000, выс. - 906', null=True, verbose_name='Изображение')),
                ('image_phone', models.ImageField(blank=True, null=True, upload_to='f/ip', verbose_name='Мобильное изображение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mortgage.MortgagePageForm', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Сотрудник формы страницы ипотеки',
                'verbose_name_plural': 'Сотрудники формы страницы ипотеки',
            },
        ),
    ]
