# Generated by Django 3.0.10 on 2021-03-29 09:08

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0012_mortgagepageform_google_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='subs_rate',
            field=common.fields.FloatRangeField(blank=True, null=True, verbose_name='Процентная ставка (субсидированная ипотека)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subs_term',
            field=common.fields.FloatRangeField(blank=True, null=True, verbose_name='Срок кредита (субсидированная ипотека)'),
        ),
    ]
