# Generated by Django 3.0.14 on 2021-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0013_auto_20210329_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='dvizh_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id банка в Движ.API'),
        ),
        migrations.AddField(
            model_name='offer',
            name='dvizh_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id банка в Движ.API'),
        ),
        migrations.AddField(
            model_name='program',
            name='dvizh_type',
            field=models.CharField(choices=[('STANDARD', 'Стандартная ипотека'), ('FAMILY', 'Семейная ипотека'), ('MILITARY', 'Военная ипотека'), ('GOVERNMENT_SUPPORT', 'Государственная поддержка 2020 (пандемия COVID-19)')], default='STANDARD', max_length=32, verbose_name='Тип предложения для Движ.Api'),
        ),
    ]
