# Generated by Django 3.0.14 on 2021-12-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0014_auto_20211229_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='dvizh_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id предложения в Движ.API'),
        ),
    ]
