# Generated by Django 3.0.14 on 2021-12-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0016_bank_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
