# Generated by Django 3.0.14 on 2022-02-15 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0017_offer_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='dvizh_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='dvizh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=[], null=True, size=None, verbose_name='id предложения в Движ.API'),
        ),
    ]
