# Generated by Django 3.0.14 on 2022-06-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0018_auto_20220215_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.Bank', verbose_name='Банк'),
        ),
    ]
