# Generated by Django 3.0.14 on 2022-06-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0019_auto_20220603_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='bank',
        ),
    ]
