# Generated by Django 3.0.14 on 2022-06-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0020_remove_offer_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.Bank', verbose_name='Банк'),
        ),
    ]
