# Generated by Django 3.0.14 on 2022-06-20 06:52

import ajaximage.fields
import ckeditor.fields
import common.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('projects', '0117_project_presentation_link'),
        ('mortgage', '0021_offer_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='dvizh_ids',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_document',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание для документов'),
        ),
        migrations.AddField(
            model_name='offer',
            name='icon',
            field=ajaximage.fields.AjaxImageField(blank=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='purchase/image', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_commercial',
            field=models.BooleanField(default=False, verbose_name='Для страницы коммерции'),
        ),
        migrations.AddField(
            model_name='offer',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст ссылки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='offer',
            name='purchase_type_step_button',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки шагов покупки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='purchase_type_step_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание шагов покупки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='purchase_type_step_footer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Футер шагов покупки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='purchase_type_step_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок шагов покупки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='show_calk',
            field=models.BooleanField(default=False, verbose_name='Отображать калькулятор'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок 1'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.CreateModel(
            name='OfferPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('type', models.CharField(choices=[('commercial', 'Коммерческая ипотека'), ('residential', 'Жилая ипотека')], max_length=100, verbose_name='Тип')),
                ('deposit', common.fields.FloatRangeField(blank=True, null=True, verbose_name='Первоначальный взнос')),
                ('rate', common.fields.FloatRangeField(blank=True, null=True, verbose_name='Процентная ставка')),
                ('term', common.fields.FloatRangeField(blank=True, null=True, verbose_name='Срок кредита')),
                ('amount', common.fields.IntegerRangeField(blank=True, null=True, verbose_name='Сумма кредита')),
                ('subs_rate', common.fields.FloatRangeField(blank=True, null=True, verbose_name='Процентная ставка (субсидированная ипотека)')),
                ('subs_term', common.fields.FloatRangeField(blank=True, null=True, verbose_name='Срок кредита (субсидированная ипотека)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('dvizh_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=[], null=True, size=None, verbose_name='id предложения в Движ.API')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.Bank', verbose_name='Банк')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.Program', verbose_name='Программа')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Предложение по ипотеке',
                'verbose_name_plural': 'Предложения по ипотеке',
                'ordering': ('order',),
                'get_latest_by': 'rate',
            },
        ),
    ]
