# Generated by Django 3.0.14 on 2022-06-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_auto_20220110_1107'),
        ('mortgage', '0022_auto_20220620_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ по способу покупки',
                'verbose_name_plural': 'FAQ по способу покупки',
            },
        ),
        migrations.AlterModelOptions(
            name='offerpanel',
            options={'get_latest_by': 'rate', 'ordering': ('order',), 'verbose_name': 'Предложение по ипотеке для панели', 'verbose_name_plural': 'Предложения по ипотеке для панели'},
        ),
        migrations.AddField(
            model_name='offer',
            name='faq',
            field=models.ManyToManyField(blank=True, to='purchase.PurchaseFAQ', verbose_name='FAQ'),
        ),
        migrations.CreateModel(
            name='OfferTypeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage.Offer', verbose_name='Способ покупки')),
            ],
            options={
                'verbose_name': 'Шаг способа покупки',
                'verbose_name_plural': 'Шаги способа покупки',
                'ordering': ('order',),
            },
        ),
    ]
