# Generated by Django 3.0.14 on 2022-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0024_auto_20220621_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_site',
            field=models.BooleanField(default=False, verbose_name='Отображать предложение на сайте'),
        ),
    ]
