# Generated by Django 3.0.14 on 2022-09-20 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0025_offer_is_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpanel',
            name='dvizh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='id предложения в Движ.API'),
        ),
    ]
