# Generated by Django 3.0.8 on 2020-07-22 14:29

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_auto_20200721_1253"),
    ]

    operations = [
        migrations.CreateModel(
            name="Furnish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок"),),
            ],
            options={
                "verbose_name": "Отделка",
                "verbose_name_plural": "Отделки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="FurnishImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                ("file", ajaximage.fields.AjaxImageField(verbose_name="Файл")),
                (
                    "furnish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_set",
                        to="properties.Furnish",
                        verbose_name="Отделка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение отделки",
                "verbose_name_plural": "Изображения отделки",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="property",
            name="furnish_set",
            field=models.ManyToManyField(
                blank=True, to="properties.Furnish", verbose_name="Варианты отделки"
            ),
        ),
    ]
