# Generated by Django 3.0.10 on 2020-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_auto_20200915_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="has_tenant",
            field=models.BooleanField(default=False, verbose_name="С арендатором"),
        ),
    ]
