# Generated by Django 3.0.10 on 2020-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_property_has_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="plan_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="Код планировки"),
        ),
    ]
