# Generated by Django 3.0.10 on 2020-10-15 12:09

import ckeditor.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_property_plan_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnishPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    common.fields.PpoiField(
                        blank=True,
                        max_length=50,
                        null=True,
                        source="furnish.file",
                        verbose_name="Точка",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Текст"),),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_set",
                        to="properties.FurnishImage",
                        verbose_name="Отделка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка на изображении отделки",
                "verbose_name_plural": "Точка на изображении отделки",
                "ordering": ("order",),
            },
        ),
    ]
