# Generated by Django 3.0.10 on 2020-11-10 08:46

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0010_auto_20201106_1353"),
        ("properties", "0011_property_furnish_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatRoomsMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rooms_0_image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 415, выс. - 471",
                        null=True,
                        verbose_name="Студии / Изображение",
                    ),
                ),
                (
                    "rooms_0_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Студии / Текст"),
                ),
                (
                    "rooms_1_image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 415, выс. - 471",
                        null=True,
                        verbose_name="1-комнатные / Изображение",
                    ),
                ),
                (
                    "rooms_1_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="1-комнатные / Текст"
                    ),
                ),
                (
                    "rooms_2_image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 415, выс. - 471",
                        null=True,
                        verbose_name="2-комнатные / Изображение",
                    ),
                ),
                (
                    "rooms_2_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="2-комнатные / Текст"
                    ),
                ),
                (
                    "rooms_3_image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 415, выс. - 471",
                        null=True,
                        verbose_name="3-комнатные / Изображение",
                    ),
                ),
                (
                    "rooms_3_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="3-комнатные / Текст"
                    ),
                ),
                (
                    "rooms_4_image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 415, выс. - 471",
                        null=True,
                        verbose_name="4-комнатные / Изображение",
                    ),
                ),
                (
                    "rooms_4_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="4-комнатные / Текст"
                    ),
                ),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flat_rooms_menu",
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображения квартир для меню",
                "verbose_name_plural": "Изображения квартир для меню",
            },
        ),
    ]
