# Generated by Django 3.0.10 on 2020-11-10 10:38

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_flatroomsmenu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furnishpoint",
            name="point",
            field=common.fields.PpoiField(
                blank=True, max_length=50, null=True, source="image.file", verbose_name="Точка"
            ),
        ),
    ]
