# Generated by Django 3.0.10 on 2020-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_auto_20201110_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathroom_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Площадь санузла",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="facade",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Фасады"),
        ),
        migrations.AddField(
            model_name="property",
            name="kitchen_living",
            field=models.BooleanField(blank=True, null=True, verbose_name="Кухня-гостинная"),
        ),
        migrations.AddField(
            model_name="property",
            name="lounge_balcony",
            field=models.BooleanField(blank=True, null=True, verbose_name="Лаунж-балкон"),
        ),
        migrations.AddField(
            model_name="property",
            name="security",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Безопасность"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="storage",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Кладовая"),
        ),
        migrations.AddField(
            model_name="property",
            name="yards",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Дворы"),
        ),
    ]
