# Generated by Django 3.0.10 on 2020-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_auto_20201111_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="action",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Акция"),
        ),
    ]
