# Generated by Django 3.0.10 on 2020-11-12 09:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_property_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uptitle", models.CharField(max_length=50, verbose_name="Над заголовком")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(max_length=1000, verbose_name="Текст")),
                ("image", models.ImageField(upload_to="p/pc/i", verbose_name="Изображение")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("flat", "Квартира"),
                            ("parking", "Парковочное место"),
                            ("commercial", "Коммерческое помещение"),
                            ("pantry", "Кладовка"),
                            ("another", "Другое"),
                        ],
                        max_length=15,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка подборщика",
                "verbose_name_plural": "Карточки подборщика",
            },
        ),
    ]
