# Generated by Django 3.0.10 on 2020-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0017_furnishpoint_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="for_business",
            field=models.BooleanField(default=False, verbose_name="Для бизнеса"),
        ),
    ]
