# Generated by Django 3.0.10 on 2020-11-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_property_for_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertycard",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
