# Generated by Django 3.0.10 on 2020-11-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_propertycard_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnish",
            name="vr_link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка VR-тур"),
        ),
    ]
