# Generated by Django 3.0.10 on 2020-11-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20201119_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='planoplan',
            field=models.TextField(blank=True, verbose_name='URL для виджета от Planoplan'),
        ),
    ]
