# Generated by Django 3.0.10 on 2020-12-05 12:20

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_planoplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatroomsmenu',
            name='rooms_0_image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 830, выс. - 942', null=True, verbose_name='Студии / Изображение'),
        ),
        migrations.AlterField(
            model_name='flatroomsmenu',
            name='rooms_1_image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 830, выс. - 942', null=True, verbose_name='1-комнатные / Изображение'),
        ),
        migrations.AlterField(
            model_name='flatroomsmenu',
            name='rooms_2_image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 830, выс. - 942', null=True, verbose_name='2-комнатные / Изображение'),
        ),
        migrations.AlterField(
            model_name='flatroomsmenu',
            name='rooms_3_image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 830, выс. - 942', null=True, verbose_name='3-комнатные / Изображение'),
        ),
        migrations.AlterField(
            model_name='flatroomsmenu',
            name='rooms_4_image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 830, выс. - 942', null=True, verbose_name='4-комнатные / Изображение'),
        ),
    ]
