# Generated by Django 3.0.10 on 2020-12-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_auto_20201205_1220'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_property_building_number',
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(number__isnull=False), fields=('building', 'number', 'id'), name='unique_property_building_number'),
        ),
    ]
