# Generated by Django 3.0.10 on 2020-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20201211_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='update_text',
            field=models.TextField(blank=True, verbose_name='Отладка обновления'),
        ),
        migrations.AddField(
            model_name='property',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
