# Generated by Django 3.0.10 on 2020-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_property_furnish_price_per_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plan_png',
            field=models.FileField(blank=True, help_text='Генерируется автоматически', upload_to='pp/f/pp', verbose_name='Планировка в PNG'),
        ),
    ]
