# Generated by Django 3.0.10 on 2021-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_property_plan_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plan_png_preview',
            field=models.FileField(blank=True, help_text='Генерируется автоматически', upload_to='pp/f/ppp', verbose_name='Планировка в PNG - превью на карточке'),
        ),
    ]
