# Generated by Django 3.0.10 on 2021-01-21 11:15

from django.db import migrations


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Property = apps.get_model("properties", "Property")
    property_qs = Property.objects.using(db_alias).exclude(plan='')
    for prop in property_qs:
        prop.plan_3d = prop.plan_png
        prop.save()


def reverse(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Property = apps.get_model("properties", "Property")
    property_qs = Property.objects.using(db_alias).exclude(plan='')
    for prop in property_qs:
        prop.plan_3d = ''
        prop.save()


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0030_property_plan_3d'),
    ]

    operations = [migrations.RunPython(forwards, reverse_code=reverse)]
