# Generated by Django 3.0.10 on 2021-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_auto_20210121_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='frontage',
            field=models.BooleanField(default=False, verbose_name='Палисадник'),
        ),
    ]
