# Generated by Django 3.0.10 on 2021-03-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_property_hide_price'),
        ('properties', '0032_property_frontage'),
    ]

    operations = [
    ]
