# Generated by Django 3.0.10 on 2021-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_merge_20210302_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_disable_online_booking',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Для фильтра ипотека 1.6%. Если онлайн-бронирование отключено, на странице лота появляется форма дефолтного бронирования.',
                verbose_name='Онлайн-бронирование отключено',
            ),
        ),
    ]
