# Generated by Django 3.0.10 on 2021-04-02 14:18

import ajaximage.fields
import common.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_building_is_active'),
        ('properties', '0034_property_is_disable_online_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowView',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'ppoi',
                    common.fields.PpoiField(max_length=50, source='type.file', verbose_name='PPOI'),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
            ],
            options={
                'verbose_name': 'Вид из окна',
                'verbose_name_plural': 'Виды из окон',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WindowViewType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
                ('title', models.CharField(max_length=32, verbose_name='Название типа')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                (
                    'building',
                    models.ForeignKey(
                        limit_choices_to={'kind': 'RESIDENTIAL'},
                        on_delete=django.db.models.deletion.CASCADE,
                        to='buildings.Building',
                        verbose_name='Корпус',
                    ),
                ),
                (
                    'section',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'building__kind': 'RESIDENTIAL'},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='buildings.Section',
                        verbose_name='Секция',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тип вида из окна',
                'verbose_name_plural': 'Тип вида из окна',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WindowViewAngle',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'angle',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(360),
                        ],
                        verbose_name='Угол',
                    ),
                ),
                (
                    'window_view',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='properties.WindowView',
                        verbose_name='Вид из окна',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Угол обзора',
                'verbose_name_plural': 'Углы обзора',
            },
        ),
        migrations.AddField(
            model_name='windowview',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='properties.WindowViewType',
                verbose_name='Тип вида из окна',
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='window_view',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='properties.WindowView',
                verbose_name='Вид из окна',
            ),
        ),
    ]
