# Generated by Django 3.0.10 on 2021-04-05 13:40

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_auto_20210402_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mini_plan_ppoi',
            field=common.fields.PpoiField(
                blank=True,
                max_length=50,
                null=True,
                source='building.mini_plan',
                verbose_name='Точка на мини-плане',
            ),
        ),
    ]
