# Generated by Django 3.0.10 on 2021-04-06 13:10

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_property_mini_plan_ppoi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windowviewtype',
            options={'verbose_name': 'Тип вида из окна', 'verbose_name_plural': 'Тип вида из окна'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='mini_plan_ppoi',
        ),
        migrations.RemoveField(
            model_name='windowviewtype',
            name='file',
        ),
        migrations.RemoveField(
            model_name='windowviewtype',
            name='order',
        ),
        migrations.AddField(
            model_name='windowview',
            name='mini_plan_ppoi',
            field=common.fields.PpoiField(
                blank=True,
                max_length=50,
                null=True,
                source='type.building.mini_plan',
                verbose_name='Точка на мини-плане',
            ),
        ),
        migrations.AlterField(
            model_name='windowview',
            name='ppoi',
            field=common.fields.PpoiField(
                max_length=50,
                source='type.building.project.window_view_plan',
                verbose_name='Точка на плане',
            ),
        ),
    ]
