# Generated by Django 3.0.10 on 2021-04-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_auto_20210407_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mini_plan_point',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='properties.MiniPlanPoint',
                verbose_name='Точка на миниплане',
            ),
        ),
    ]
