# Generated by Django 3.0.10 on 2021-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_property_mini_plan_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Алиас')),
                (
                    'filter_show',
                    models.BooleanField(default=True, verbose_name='Отображать в фильтре'),
                ),
                ('icon_show', models.BooleanField(default=False, verbose_name='Отображать иконку')),
                ('icon', models.ImageField(blank=True, upload_to='p/f', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                (
                    'properties',
                    models.ManyToManyField(
                        blank=True, to='properties.Property', verbose_name='Объекты собственнсти'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Особенность объекта собственнсти',
                'verbose_name_plural': 'Особенности объектов собственности',
            },
        ),
    ]
