# Generated by Django 3.0.10 on 2021-04-09 14:21

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_property_mini_plan_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowview',
            name='ppoi',
            field=common.fields.PpoiField(max_length=50, source='type.building.window_view_plan', verbose_name='Точка на плане'),
        ),
    ]
