# Generated by Django 3.0.10 on 2021-04-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_auto_20210409_1421'),
        ('properties', '0040_feature'),
    ]

    operations = [
    ]
