# Generated by Django 3.0.10 on 2021-04-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_auto_20210422_1128'),
        ('properties', '0041_merge_20210413_0843'),
    ]

    operations = [
    ]
