# Generated by Django 3.0.10 on 2021-05-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0027_building_address"),
        ("projects", "0063_merge_20210409_1631"),
        ("properties", "0042_merge_20210426_0811"),
    ]

    operations = [
        migrations.AddField(
            model_name="layout",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buildings.Building",
                verbose_name="Корпус",
            ),
        ),
        migrations.AddField(
            model_name="layout",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buildings.Floor",
                verbose_name="Этаж",
            ),
        ),
        migrations.AddField(
            model_name="layout",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
    ]
