# Generated by Django 3.0.10 on 2021-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0044_auto_20210518_1316")]

    operations = [
        migrations.AddField(
            model_name="property",
            name="corner_windows",
            field=models.BooleanField(default=False, verbose_name="Угловые окна"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="kind",
            field=models.CharField(
                choices=[
                    ("facing", "Отделка"),
                    ("has_parking", "Паркинг"),
                    ("has_terrace", "Терраса"),
                    ("has_view", "Видовые"),
                    ("has_panoramic_windows", "Панорамные окна"),
                    ("has_two_sides_windows", "Окна на 2 стороны"),
                    ("is_duplex", "Двухуровневая"),
                    ("has_high_ceiling", "Высокий потолок"),
                    ("installment", "Рассрочка"),
                    ("frontage", "Палисадник"),
                    ("preferential_mortgage", "Льготная ипотека"),
                    ("has_tenant", "С арендатором"),
                    ("action", "Акция"),
                    ("favorable_rate", "Выгодная ставка"),
                    ("completed", "Завершенная"),
                    ("corner_windows", "Угловые окна"),
                ],
                default="facing",
                max_length=48,
                verbose_name="Тип",
            ),
        ),
    ]
