# Generated by Django 3.0.10 on 2021-05-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0045_auto_20210519_1241")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.FileField(blank=True, upload_to="p/f", verbose_name="Иконка"),
        )
    ]
