# Generated by Django 3.0.10 on 2021-05-28 11:36

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0046_auto_20210520_1107")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="property_kind",
            field=common.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("flat", "Квартира"),
                        ("parking", "Парковочное место"),
                        ("commercial", "Коммерческое помещение"),
                        ("pantry", "Кладовка"),
                        ("commercial_apartment", "Аппартаменты коммерции"),
                    ],
                    max_length=20,
                ),
                default=list,
                size=None,
                verbose_name="Типы недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                    ("commercial_apartment", "Аппартаменты коммерции"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
