# Generated by Django 3.0.10 on 2021-05-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("properties", "0047_auto_20210528_1436")]

    operations = [
        migrations.AddField(
            model_name="layout",
            name="window_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.WindowView",
                verbose_name="Вид из окна",
            ),
        )
    ]
