# Generated by Django 3.0.10 on 2021-06-11 09:46

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0048_layout_window_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("color", colorful.fields.RGBColorField(blank=True, verbose_name="Цвет")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "description_active",
                    models.BooleanField(default=True, verbose_name="Описание активно"),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "finish_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания"),
                ),
                (
                    "discount_active",
                    models.BooleanField(default=False, verbose_name="Скидка активна"),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(default=0, verbose_name="Значение скидки"),
                ),
                (
                    "discount_type",
                    models.CharField(blank=True, max_length=32, verbose_name="Тип скидки"),
                ),
                (
                    "discount_unit",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Единицы измерения скидки"
                    ),
                ),
                (
                    "discount_description",
                    models.TextField(blank=True, verbose_name="Описание скидки"),
                ),
                (
                    "badge_icon",
                    models.CharField(blank=True, max_length=32, verbose_name="Иконка бейджа"),
                ),
                (
                    "badge_label",
                    models.CharField(blank=True, max_length=32, verbose_name="Название бейджа"),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True, to="properties.Property", verbose_name="Объекты собственности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция объектов собственности",
                "verbose_name_plural": "Акции объектов собственности",
            },
        ),
    ]
