# Generated by Django 3.0.10 on 2021-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0048_layout_window_view")]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="main_filter_show",
            field=models.BooleanField(
                default=False, verbose_name="Отображать в фильтре на главной"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="filter_show",
            field=models.BooleanField(default=True, verbose_name="Отображать в фильтре листинга"),
        ),
    ]
