# Generated by Django 3.0.10 on 2021-06-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("properties", "0049_auto_20210616_1120")]

    operations = [migrations.RemoveField(model_name="property", name="furnish_price")]
