# Generated by Django 3.0.10 on 2021-06-21 15:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0050_remove_property_furnish_price")]

    operations = [
        migrations.CreateModel(
            name="PropertyPurpose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                ("icon", models.FileField(blank=True, upload_to="p/pp", verbose_name="Иконка")),
                ("description", ckeditor.fields.RichTextField(blank=True, verbose_name="Описание")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Назначение объекта собственности",
                "verbose_name_plural": "Назначения объектов собственности",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="property",
            name="purposes",
            field=models.ManyToManyField(
                blank=True, to="properties.PropertyPurpose", verbose_name="Назначения помещения"
            ),
        ),
    ]
