# Generated by Django 3.0.10 on 2021-06-22 14:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0050_remove_property_furnish_price")]

    operations = [
        migrations.CreateModel(
            name="PropertyConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "lot_form_title",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Заголовок формы на карточке лота"
                    ),
                ),
                (
                    "lot_form_description",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Описание формы на карточке лота"
                    ),
                ),
            ],
            options={"verbose_name": "Настройка объектов собственности"},
        )
    ]
