# Generated by Django 3.0.10 on 2021-06-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0051_auto_20210623_1616"),
        ("properties", "0051_propertyconfig"),
    ]

    operations = []
