# Generated by Django 3.0.10 on 2021-06-24 15:15

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("properties", "0051_auto_20210623_1616")]

    operations = [
        migrations.AddField(
            model_name="layout",
            name="plan_hover",
            field=common.fields.PolygonField(
                blank=True, source="floor.plan", verbose_name="Обводка на плане"
            ),
        )
    ]
