# Generated by Django 3.0.10 on 2021-06-24 15:34

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("properties", "0052_layout_plan_hover")]

    operations = [
        migrations.AlterField(
            model_name="layout",
            name="plan_hover",
            field=common.fields.PolygonField(
                blank=True, null=True, source="floor.plan", verbose_name="Обводка на плане"
            ),
        )
    ]
