# Generated by Django 3.0.10 on 2021-06-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0051_auto_20210621_1810"),
        ("properties", "0053_auto_20210624_1834"),
    ]

    operations = []
