# Generated by Django 3.0.10 on 2021-06-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0054_property_commercial_plan"),
        ("properties", "0054_merge_20210625_1810"),
    ]

    operations = []
