# Generated by Django 3.0.10 on 2021-07-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0055_merge_20210630_1610"),
        ("properties", "0052_merge_20210624_1300"),
    ]

    operations = []
