# Generated by Django 3.0.10 on 2021-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0056_merge_20210702_1706")]

    operations = [
        migrations.AddField(
            model_name="layout",
            name="min_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Минимальная цена",
            ),
        ),
        migrations.AddField(
            model_name="layout",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                    ("commercial_apartment", "Аппартаменты коммерции"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
