# Generated by Django 3.0.10 on 2021-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("properties", "0057_auto_20210712_1616")]

    operations = [
        migrations.AlterField(
            model_name="layout",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                    ("commercial_apartment", "Аппартаменты коммерции"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип",
            ),
        )
    ]
