# Generated by Django 3.0.10 on 2021-07-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0058_auto_20210713_1101"),
        ("properties", "0049_specialoffer"),
    ]

    operations = []
