# Generated by Django 3.0.10 on 2021-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0061_auto_20210721_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layout",
            name="name",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="Название"
            ),
        ),
    ]
