# Generated by Django 3.0.10 on 2021-07-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0062_auto_20210728_1529"),
        ("properties", "0059_merge_20210720_1658"),
    ]

    operations = []
