# Generated by Django 3.0.10 on 2021-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_auto_20210729_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
