# Generated by Django 3.0.10 on 2021-08-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_auto_20210729_1856'),
        ('properties', '0063_merge_20210729_1325'),
    ]

    operations = [
    ]
