# Generated by Django 3.0.10 on 2021-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_listingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingaction',
            name='uptitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Над заголовком'),
        ),
    ]
