# Generated by Django 3.0.10 on 2021-08-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_merge_20210813_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='is_display',
            field=models.BooleanField(default=False, verbose_name='Отображать на сайте'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название', help_text='Заполняется вручную'),
        ),
    ]
