# Generated by Django 3.0.10 on 2021-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0065_auto_20210813_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='badge_icon',
            field=models.CharField(blank=True, max_length=120, verbose_name='Иконка бейджа'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='badge_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название бейджа'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='discount_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тип скидки'),
        ),
    ]
