# Generated by Django 3.0.10 on 2021-08-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_city_disable_site'),
        ('properties', '0065_listingaction_uptitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingaction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City', verbose_name='Город'),
        ),
    ]
