# Generated by Django 3.0.10 on 2021-09-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0066_listingaction_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description_hypo',
            field=models.TextField(blank=True, verbose_name='Описание для гипотезы'),
        ),
    ]
