# Generated by Django 3.0.10 on 2021-09-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_property_views_count'),
        ('properties', '0067_feature_description_hypo'),
    ]

    operations = [
    ]
