# Generated by Django 3.0.10 on 2021-09-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0066_auto_20210816_1524'),
        ('properties', '0067_feature_description_hypo'),
    ]

    operations = [
    ]
