# Generated by Django 3.0.10 on 2021-09-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0068_merge_20210913_1516'),
        ('properties', '0067_property_repair_color'),
    ]

    operations = [
    ]
