# Generated by Django 3.0.10 on 2021-09-13 13:53

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0069_merge_20210913_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название цвета ремонта')),
                ('color', colorful.fields.RGBColorField(blank=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет ремонта',
                'verbose_name_plural': 'Цвета ремонта',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='repair_color_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.RepairColor', verbose_name='Цвет ремонта'),
        ),
    ]
