# Generated by Django 3.0.10 on 2021-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0069_merge_20210913_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='min_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальная процентная ставка'),
        ),
    ]
