# Generated by Django 3.0.10 on 2021-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0069_merge_20210913_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='lot_page_show',
            field=models.BooleanField(default=True, verbose_name='Отображать на странице лота'),
        ),
    ]
