# Generated by Django 3.0.10 on 2021-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0070_auto_20210913_1653'),
        ('properties', '0070_feature_lot_page_show'),
    ]

    operations = [
    ]
