# Generated by Django 3.0.10 on 2021-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0070_feature_lot_page_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='icon',
            field=models.FileField(blank=True, upload_to='spo/f', verbose_name='Иконка'),
        ),
    ]
