# Generated by Django 3.0.10 on 2021-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0073_feature_icon_hypo'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Максимальная скидка'),
        ),
    ]
