# Generated by Django 3.0.10 on 2021-09-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0068_merge_20210913_1006'),
        ('properties', '0073_feature_icon_hypo'),
    ]

    operations = [
    ]
