# Generated by Django 3.0.10 on 2021-10-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0073_feature_icon_hypo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='planoplan_commercial',
            field=models.TextField(blank=True, verbose_name='URL для виджета от Planoplan (коммерческий апартамент)'),
        ),
    ]
