# Generated by Django 3.0.10 on 2021-10-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0074_layout_max_discount'),
        ('properties', '0074_property_planoplan_commercial'),
    ]

    operations = [
    ]
