# Generated by Django 3.0.10 on 2021-10-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0075_merge_20211004_1549'),
        ('properties', '0074_merge_20210928_1112'),
    ]

    operations = [
    ]
