# Generated by Django 3.0.10 on 2021-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0077_auto_20211109_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view_cathedral',
            field=models.BooleanField(default=False, verbose_name='Вид на Исаакиевский собор'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_center',
            field=models.BooleanField(default=False, verbose_name='Вид на центр'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_gulf',
            field=models.BooleanField(default=False, verbose_name='Вид на Финский залив'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_park',
            field=models.BooleanField(default=False, verbose_name='Вид на парк Екатерингоф'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_river',
            field=models.BooleanField(default=False, verbose_name='Вид на реку'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_square',
            field=models.BooleanField(default=False, verbose_name='Вид на сквер'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_temple',
            field=models.BooleanField(default=False, verbose_name='Вид на храм'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='kind',
            field=models.CharField(choices=[('facing', 'Отделка'), ('has_parking', 'Паркинг'), ('has_action_parking', 'Паркинг по спец. цене'), ('has_terrace', 'Терраса'), ('has_view', 'Видовые'), ('has_panoramic_windows', 'Панорамные окна'), ('has_two_sides_windows', 'Окна на 2 стороны'), ('is_duplex', 'Двухуровневая'), ('has_high_ceiling', 'Высокий потолок'), ('installment', 'Рассрочка'), ('frontage', 'Палисадник'), ('preferential_mortgage', 'Льготная ипотека'), ('preferential_mortgage4', 'Льготная ипотека 4.95%'), ('has_tenant', 'С арендатором'), ('action', 'Акция'), ('favorable_rate', 'Выгодная ставка'), ('completed', 'Завершенная'), ('corner_windows', 'Угловые окна'), ('maternal_capital', 'Материнский капитал'), ('has_separate_entrance', 'Отдельная входная группа'), ('has_two_entrances', 'Два входа'), ('has_stained_glass', 'Витражное остекление'), ('has_functional_layout', 'Функциональная планировка'), ('has_place_for_ads', 'Место под рекл. вывеску'), ('has_ceiling_three_meters', 'Потолок 3-3,6м'), ('has_water_supply', 'Горячее и холодное водоснабжение'), ('has_dot_two_kilowatts', 'Эл. мощность 0,2 кВт/м2'), ('has_own_ventilation', 'Собственная вент. шахта'), ('has_balcony_or_loggia', 'Есть балкон или лоджия'), ('view_cathedral', 'Вид на Исаакиевский собор'), ('view_gulf', 'Вид на Финский залив'), ('view_river', 'Вид на реку'), ('view_park', 'Вид на парк Екатерингоф'), ('view_temple', 'Вид на храм'), ('view_square', 'Вид на сквер'), ('view_center', 'Вид на центр')], default='facing', max_length=48, verbose_name='Тип'),
        ),
    ]
