# Generated by Django 3.0.10 on 2021-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_auto_20210922_1328'),
        ('properties', '0078_auto_20211111_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cities.City', verbose_name='Города'),
        ),
    ]
