# Generated by Django 3.0.10 on 2021-11-11 10:43

from django.db import migrations

def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    City = apps.get_model("cities", "City")
    Feature = apps.get_model("properties", "Feature")

    cities = City.objects.filter(active=True)
    for feature in Feature.objects.using(db_alias).all():
        feature.cities.add(*cities)


def reverse(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Feature = apps.get_model("properties", "Feature")

    for feature in Feature.objects.using(db_alias).all():
        feature.cities.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0079_feature_cities'),
    ]

    operations = [migrations.RunPython(forwards, reverse_code=reverse)]
