# Generated by Django 3.0.14 on 2021-11-17 14:12

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0080_cities_to_property_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(null=True, verbose_name='Изображение')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Furnish', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'Описание работы',
                'verbose_name_plural': 'Описание работы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(verbose_name='Изображение')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Furnish', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'Преимущество отделки',
                'verbose_name_plural': 'Преимущества отделки',
                'ordering': ('order',),
            },
        ),
    ]
