# Generated by Django 3.0.14 on 2021-11-22 09:14

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0081_furnishadvantage_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnish',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео / Ссылка'),
        ),
        migrations.AddField(
            model_name='furnish',
            name='video_preview',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='Видео / Превью'),
        ),
    ]
