# Generated by Django 3.0.14 on 2021-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0082_auto_20211122_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hypo_experimental_lot',
            field=models.BooleanField(default=False, verbose_name='Экспериментальный лот'),
        ),
    ]
