# Generated by Django 3.0.14 on 2021-11-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0083_property_hypo_experimental_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='hypo_experimental_lot',
        ),
        migrations.AddField(
            model_name='layout',
            name='hypo_experimental_lot',
            field=models.BooleanField(default=False, verbose_name='Экспериментальный лот'),
        ),
    ]
