# Generated by Django 3.0.14 on 2021-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0084_auto_20211129_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hypo_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная(для гипотезы)'),
        ),
    ]
