# Generated by Django 3.0.14 on 2021-12-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0086_feature_is_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCommercialGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='b/bcg/i/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'verbose_name': 'Изображение для коммерческого помещения',
                'verbose_name_plural': 'Галерея для коммерческих помещений',
                'ordering': ('order',),
            },
        ),
    ]
