# Generated by Django 3.0.14 on 2021-12-21 13:18

import ajaximage.fields
import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0088_auto_20211220_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='area',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='layout',
            name='facing',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='layout',
            name='first_flat_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Id первой квартиры'),
        ),
        migrations.AddField(
            model_name='layout',
            name='flat_count',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Количество квартир'),
        ),
        migrations.AddField(
            model_name='layout',
            name='floor_plan',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(('svg',))], verbose_name='Планировка этажа'),
        ),
        migrations.AddField(
            model_name='layout',
            name='floor_plan_height',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Высота планировки этажа'),
        ),
        migrations.AddField(
            model_name='layout',
            name='floor_plan_hover',
            field=common.fields.PolygonField(blank=True, editable=False, null=True, source='floor.section.plan', verbose_name='Обводка на плане'),
        ),
        migrations.AddField(
            model_name='layout',
            name='floor_plan_width',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Ширина планировки этажа'),
        ),
        migrations.AddField(
            model_name='layout',
            name='frontage',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Палисадник'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_action_parking',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Паркинг по спец. цене'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_high_ceiling',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Высокий потолок'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_panoramic_windows',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Панорамные окна'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_parking',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_terrace',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Терраса'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_two_sides_windows',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Окна на 2 стороны'),
        ),
        migrations.AddField(
            model_name='layout',
            name='has_view',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Видовая'),
        ),
        migrations.AddField(
            model_name='layout',
            name='hypo_popular',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Популярная(для гипотезы)'),
        ),
        migrations.AddField(
            model_name='layout',
            name='installment',
            field=models.BooleanField(blank=True, db_index=True, default=False, editable=False, null=True, verbose_name='Рассрочка'),
        ),
        migrations.AddField(
            model_name='layout',
            name='is_duplex',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Двухуровневая'),
        ),
        migrations.AddField(
            model_name='layout',
            name='maternal_capital',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Материнский капитал'),
        ),
        migrations.AddField(
            model_name='layout',
            name='max_floor',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Максимальный этаж'),
        ),
        migrations.AddField(
            model_name='layout',
            name='min_floor',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Минимальный этаж'),
        ),
        migrations.AddField(
            model_name='layout',
            name='plan',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(('png', 'svg'))], verbose_name='Планировка объекта собственности'),
        ),
        migrations.AddField(
            model_name='layout',
            name='planoplan',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='URL для виджета от Planoplan'),
        ),
        migrations.AddField(
            model_name='layout',
            name='preferential_mortgage4',
            field=models.BooleanField(blank=True, db_index=True, default=False, editable=False, null=True, verbose_name='Льготная ипотека 4.95%'),
        ),
    ]
