# Generated by Django 3.0.14 on 2021-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0089_auto_20211221_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='min_mortgage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная ставка по ипотеке(при депозите в 20%)'),
        ),
    ]
