# Generated by Django 3.0.14 on 2021-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0090_layout_min_mortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Комнатность'),
        ),
    ]
