# Generated by Django 3.0.14 on 2021-12-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0089_auto_20211223_1616'),
        ('properties', '0091_layout_rooms'),
    ]

    operations = [
    ]
