# Generated by Django 3.0.10 on 2021-12-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0092_merge_20211224_1225'),
        ('properties', '0071_specialoffer_icon'),
    ]

    operations = [
    ]
