# Generated by Django 3.0.14 on 2022-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0093_merge_20211224_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hypo_min_mortgage',
            field=models.IntegerField(editable=False, null=True, verbose_name='Ежемесячный платеж(для гипотезы)'),
        ),
    ]
