# Generated by Django 3.0.10 on 2022-01-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0094_property_hypo_min_mortgage'),
        ('properties', '0070_layout_min_rate'),
    ]

    operations = [
    ]
