# Generated by Django 3.0.14 on 2022-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0095_merge_20220112_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=14, verbose_name='Цена'),
        ),
    ]
