# Generated by Django 3.0.10 on 2022-01-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0096_auto_20220117_1252'),
        ('properties', '0096_auto_20220117_1259'),
    ]

    operations = [
    ]
