# Generated by Django 3.0.14 on 2022-01-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0097_layout_design_gift'),
        ('properties', '0097_merge_20220117_1449'),
    ]

    operations = [
    ]
