# Generated by Django 3.0.14 on 2022-01-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0098_merge_20220117_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='design_gift',
            field=models.BooleanField(default=False, null=True, verbose_name='Дизайн-проект в подарок'),
        ),
    ]
