# Generated by Django 3.0.14 on 2022-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0099_auto_20220117_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='flat_sold',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество проданных квартир'),
        ),
    ]
