# Generated by Django 3.0.14 on 2022-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0100_layout_flat_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='wardobe',
            field=models.BooleanField(default=False, verbose_name='Гаредеробная'),
        ),
    ]
