# Generated by Django 3.0.14 on 2022-02-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0102_auto_20220127_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='description_hypo',
        ),
    ]
