# Generated by Django 3.0.14 on 2022-02-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0103_auto_20220202_1143'),
        ('properties', '0103_remove_feature_description_hypo'),
    ]

    operations = [
    ]
