# Generated by Django 3.0.10 on 2022-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0105_auto_20220203_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='wardobe',
            field=models.BooleanField(default=False, verbose_name='Гаредеробная'),
        ),
    ]
