# Generated by Django 3.0.14 on 2022-02-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0106_property_wardobe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='wardobe',
        ),
    ]
