# Generated by Django 3.0.14 on 2022-02-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0107_remove_property_wardobe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='repair_color',
        ),
        migrations.RemoveField(
            model_name='property',
            name='repair_color_object',
        ),
        migrations.DeleteModel(
            name='RepairColor',
        ),
    ]
