# Generated by Django 3.0.14 on 2022-02-05 11:41

from django.db import migrations, models

def forwards(apps, schema_editor):
    Furnish = apps.get_model("properties", "Furnish")
    for furnish in Furnish.objects.all():
        furnish.tech_name = furnish.name
        furnish.save()

def reverse(apps, schema_editor):
    Furnish = apps.get_model("properties", "Furnish")
    for furnish in Furnish.objects.all():
        furnish.tech_name = ""
        furnish.save()



class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0107_remove_property_wardobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnish',
            name='tech_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Техническое название'),
        ),
        migrations.RunPython(forwards, reverse),
    ]
