# Generated by Django 3.0.14 on 2022-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0108_furnish_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnish',
            name='tech_name',
            field=models.CharField(max_length=200, verbose_name='Техническое название'),
        ),
    ]
