# Generated by Django 3.0.10 on 2022-02-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0109_auto_20220205_1446'),
        ('properties', '0108_auto_20220205_1632'),
    ]

    operations = [
    ]
