# Generated by Django 3.0.14 on 2022-02-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0110_merge_20220208_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='is_display',
            field=models.BooleanField(default=False, help_text='Отображение чек-бокса в фильтре и акции на странице квартиры', verbose_name='Отображать на сайте'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='name',
            field=models.CharField(blank=True, help_text='Заполняется вручную. Название чек-бокса в фильтре и акции на странице квартиры', max_length=120, verbose_name='Название'),
        ),
    ]
