# Generated by Django 3.0.14 on 2022-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0111_auto_20220214_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='badge_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название акции в PB'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='icon',
            field=models.FileField(blank=True, help_text='Отображается на странице квартиры', upload_to='spo/f', verbose_name='Иконка'),
        ),
    ]
