# Generated by Django 3.0.14 on 2022-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0110_auto_20220413_1230"),
        ("properties", "0112_auto_20220225_1047"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnishimage",
            name="project",
            field=models.ManyToManyField(
                blank=True, null=True, to="projects.Project", verbose_name="Проект"
            ),
        ),
    ]
