# Generated by Django 3.0.14 on 2022-05-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0114_auto_20220525_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Свободен'), (1, 'Продан'), (2, 'Забронирован'), (3, 'Не для продажи')], db_index=True, default=0, verbose_name='Статус'),
        ),
    ]
