# Generated by Django 3.0.14 on 2022-06-29 09:45

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0118_auto_20220629_1217'),
        ('properties', '0121_auto_20220610_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_hover', common.fields.PolygonField(blank=True, source='project.mini_map', verbose_name='Обводка на карте')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property', verbose_name='Объект собственности')),
            ],
        ),
    ]
