# Generated by Django 3.0.14 on 2022-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0123_auto_20220630_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertymap',
            options={'verbose_name': 'Объект собственности на карте', 'verbose_name_plural': 'Объект собственности на карте'},
        ),
    ]
