# Generated by Django 3.0.14 on 2022-07-08 06:36

import ajaximage.fields
import ckeditor.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0118_auto_20220629_1217'),
        ('properties', '0124_auto_20220701_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnishKitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('tech_name', models.CharField(max_length=200, verbose_name='Техническое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка VR-тур')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Видео / Ссылка')),
                ('video_preview', ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='Видео / Превью')),
                ('video_description', models.TextField(blank=True, verbose_name='Подпись к Видео / Превью')),
            ],
            options={
                'verbose_name': 'Отделка кухни',
                'verbose_name_plural': 'Отделки кухни',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishKitchenCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория отделки кухни',
                'verbose_name_plural': 'Категории отделки кухни',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishKitchenImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='properties.FurnishKitchenCategory', verbose_name='Категория')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='properties.FurnishKitchen', verbose_name='Отделка кухни')),
                ('project', models.ManyToManyField(blank=True, null=True, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение отделки кухни',
                'verbose_name_plural': 'Изображения отделки кухни',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='furnish',
            name='video_description',
            field=models.TextField(blank=True, verbose_name='Подпись к Видео / Превью'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnish_kitchen_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена кухни'),
        ),
        migrations.CreateModel(
            name='JobDescriptionKitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(null=True, verbose_name='Изображение')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.FurnishKitchen', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'Описание работы для кухни',
                'verbose_name_plural': 'Описание работы для кухни',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishKitchenPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', common.fields.PpoiField(blank=True, max_length=50, null=True, source='image.file', verbose_name='Точка')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_set', to='properties.FurnishKitchenImage', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'Точка на изображении отделки кухни',
                'verbose_name_plural': 'Точка на изображении отделки кухни',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishKitchenAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(verbose_name='Изображение')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.FurnishKitchen', verbose_name='Отделка кухни')),
            ],
            options={
                'verbose_name': 'Преимущество отделки кухни',
                'verbose_name_plural': 'Преимущества отделки кухни',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='furnish_kitchen_set',
            field=models.ManyToManyField(blank=True, to='properties.FurnishKitchen', verbose_name='Варианты отделки кухни'),
        ),
    ]
