# Generated by Django 3.0.14 on 2022-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0128_auto_20220722_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymap',
            name='map_hover',
            field=models.TextField(blank=True, verbose_name='Обводка на карте'),
        ),
    ]
