# Generated by Django 3.0.14 on 2022-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0129_auto_20220802_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_hover',
            field=models.TextField(blank=True, verbose_name='Обводка на карте'),
        ),
    ]
