# Generated by Django 3.0.14 on 2022-08-04 13:02

import ajaximage.fields
import ckeditor.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0122_project_commercial_title'),
        ('properties', '0130_property_map_hover'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnishFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('tech_name', models.CharField(max_length=200, verbose_name='Техническое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка VR-тур')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Видео / Ссылка')),
                ('video_preview', ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='Видео / Превью')),
                ('video_description', models.TextField(blank=True, verbose_name='Подпись к Видео / Превью')),
            ],
            options={
                'verbose_name': 'Отделка мебели',
                'verbose_name_plural': 'Отделки мебели',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishFurnitureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория отделки мебели',
                'verbose_name_plural': 'Категории отделки мебели',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishFurnitureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='properties.FurnishFurnitureCategory', verbose_name='Категория')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='properties.FurnishFurniture', verbose_name='Отделка мебели')),
                ('project', models.ManyToManyField(blank=True, null=True, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение отделки мебели',
                'verbose_name_plural': 'Изображения отделки мебели',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(null=True, verbose_name='Изображение')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.FurnishFurniture', verbose_name='Мебель')),
            ],
            options={
                'verbose_name': 'Описание работы для мебели',
                'verbose_name_plural': 'Описание работы для мебели',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishFurniturePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', common.fields.PpoiField(blank=True, max_length=50, null=True, source='image.file', verbose_name='Точка')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_set', to='properties.FurnishFurnitureImage', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'Точка на изображении отделки мебели',
                'verbose_name_plural': 'Точка на изображении отделки мебели',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FurnishFurnitureAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(verbose_name='Изображение')),
                ('furnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.FurnishFurniture', verbose_name='Отделка мобели')),
            ],
            options={
                'verbose_name': 'Преимущество отделки мебели',
                'verbose_name_plural': 'Преимущества отделки мебели',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='furnish_furniture_set',
            field=models.ManyToManyField(blank=True, to='properties.FurnishFurniture', verbose_name='Варианты отделки мебели'),
        ),
    ]
