# Generated by Django 3.0.14 on 2022-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0131_auto_20220804_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furniture_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена мебелировки'),
        ),
    ]
