# Generated by Django 3.0.14 on 2022-08-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0132_property_furniture_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='furnish_kitchen_price',
            new_name='kitchen_price',
        ),
    ]
