# Generated by Django 3.0.14 on 2022-08-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0123_auto_20220804_1602'),
        ('properties', '0133_auto_20220808_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Название')),
                ('map_hover', models.TextField(blank=True, verbose_name='Обводка на карте')),
                ('weekday_morning', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Будни утро')),
                ('weekday_day', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Будни день')),
                ('weekday_evening', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Будни вечер')),
                ('weekday_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Будни текущий трафик')),
                ('weekend_morning', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Выходные утро')),
                ('weekend_day', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Выходные день')),
                ('weekend_evening', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Выходные вечер')),
                ('weekend_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Выходные текущий трафик')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Трафик на карте',
                'verbose_name_plural': 'Трафик на карте',
            },
        ),
        migrations.DeleteModel(
            name='PropertyMap',
        ),
    ]
