# Generated by Django 3.0.14 on 2022-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0136_auto_20220810_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='is_update_profit',
            field=models.BooleanField(default=True, verbose_name='Выгрузка из profit-a'),
        ),
    ]
