# Generated by Django 3.0.14 on 2022-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0137_specialoffer_is_update_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='discount_unit',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Проценты'), ('VALUE', 'Рубли')], max_length=32, verbose_name='Единицы измерения скидки'),
        ),
    ]
