# Generated by Django 3.0.14 on 2022-08-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0138_auto_20220811_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balcony_and_terrace_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, default=0.0, verbose_name='Площадь балкона и террасы'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь кухни'),
        ),
    ]
