# Generated by Django 3.0.14 on 2022-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0140_layout_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='stores',
        ),
        migrations.AddField(
            model_name='layout',
            name='stores_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество кладовых'),
        ),
    ]
