# Generated by Django 3.0.14 on 2022-08-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0141_auto_20220812_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='balcony_and_terrace_area',
        ),
        migrations.AddField(
            model_name='property',
            name='no_balcony_and_terrace_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Площадь без балкона и террасы'),
        ),
    ]
