# Generated by Django 3.0.14 on 2022-08-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0142_auto_20220816_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon_3d_tour',
            field=models.FileField(blank=True, upload_to='p/f', verbose_name='Иконка 3-д тура'),
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_3d_tour_show',
            field=models.BooleanField(default=True, verbose_name='Отображать иконку 3-д тура на странице лотов'),
        ),
    ]
