# Generated by Django 3.0.14 on 2022-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0143_auto_20220825_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon_3d_tour',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='icon_3d_tour_show',
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_flats',
            field=models.FileField(blank=True, upload_to='p/f', verbose_name='Иконка для страницы flats'),
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_flats_show',
            field=models.BooleanField(default=False, verbose_name='Отображать на странице flats'),
        ),
    ]
