# Generated by Django 3.0.14 on 2022-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0147_propertypurpose_icon_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plan_3d_1',
            field=models.ImageField(blank=True, help_text='Добавляется вручную', upload_to='pp/i/p3', verbose_name='3D-планировка'),
        ),
    ]
