# Generated by Django 3.0.14 on 2022-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0123_auto_20220804_1602'),
        ('properties', '0148_property_plan_3d_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnishfurnitureimage',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='furnishimage',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='furnishkitchenimage',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Проект'),
        ),
    ]
