# Generated by Django 3.0.14 on 2022-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0151_auto_20221010_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер паркинга'),
        ),
    ]
