# Generated by Django 3.0.14 on 2022-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0152_property_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='profitbase_id',
            field=models.PositiveIntegerField(blank=True, help_text='внутренний ID объекта собственности в Profitbase', null=True, verbose_name='ID в Profitbase'),
        ),
    ]
