# Generated by Django 3.0.14 on 2022-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0155_remove_layout_first_flat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnishimage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Текст изображения'),
        ),
        migrations.AddField(
            model_name='furnishimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок'),
        ),
    ]
