from .benefit import PrivilegeBenefitAdmin
from .category import PrivilegeCategoryAdmin
from .cooperation_type import PrivilegeCooperationTypeAdmin
from .feedback_email import PrivilegeFeedbackEmailAdmin
from .info import PrivilegeInfoAdmin
from .partner_company import PrivilegePartnerCompanyAdmin
from .program import PrivilegeProgramAdmin
from .request import PrivilegeRequestAdmin
from .subcategory import PrivilegeSubCategoryAdmin
