"""add table user_reactions

Revision ID: 7773d8c6d8c1
Revises: 569ffe3b81d2
Create Date: 2024-08-15 12:26:00.916456

"""

import sqlalchemy as sa
from alembic import op

revision: str = "7773d8c6d8c1"
down_revision: str | None = "ed7fc64e8fd0"
branch_labels: tuple[str, ...] | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_reactions",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.String(), server_default="U+1F525", nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.UniqueConstraint("message_id", "user_id", "emoji", name="unique_user_reaction"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_reactions")
    # ### end Alembic commands ###
