"""add fields to ChatMembership to handle scout replacement

Revision ID: 884b890fa127
Revises: bd790fb420d0
Create Date: 2024-08-27 12:41:58.350447

"""

import sqlalchemy as sa
from alembic import op

revision: str = "884b890fa127"
down_revision: str | None = "bd790fb420d0"
branch_labels: tuple[str, ...] | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_membership", sa.Column("last_available_message_id", sa.BigInteger(), nullable=True))
    op.add_column("chat_membership", sa.Column("first_available_message_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "chat_membership", sa.Column("is_archive_member", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_membership", "is_archive_member")
    op.drop_column("chat_membership", "first_available_message_id")
    op.drop_column("chat_membership", "last_available_message_id")
    # ### end Alembic commands ###
