"""empty message

Revision ID: ed7fc64e8fd0
Revises: 569ffe3b81d2
Create Date: 2024-08-12 13:08:18.131183

"""

import sqlalchemy as sa
from alembic import op

revision: str = "ed7fc64e8fd0"
down_revision: str | None = "569ffe3b81d2"
branch_labels: tuple[str, ...] | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("messages", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "deleted_at")
    op.drop_column("messages", "updated_at")
    # ### end Alembic commands ###
