# Generated by Django 3.0.10 on 2021-08-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0080_projectadvantageslide_image_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProjectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, verbose_name='Алиас')),
                ('about_text', models.CharField(blank=True, max_length=300, verbose_name='Текст о проекте')),
                ('about_text_colored', models.CharField(blank=True, max_length=300, verbose_name='Выделенный тексто проекте')),
                ('about_image', models.ImageField(blank=True, upload_to='cpp/about_image', verbose_name='Изображение о проекте')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Страница коммерческого проекта',
                'verbose_name_plural': 'Страницы коммерческих проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.PositiveSmallIntegerField(default=50, help_text='%', verbose_name='Мужчины')),
                ('women', models.PositiveSmallIntegerField(default=50, help_text='%', verbose_name='Женщины')),
                ('commercial_project_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_project_page.CommercialProjectPage', verbose_name='Страница коммерческого проекта')),
            ],
            options={
                'verbose_name': 'Аудитория прокта',
                'verbose_name_plural': 'Аудитории проектов',
            },
        ),
        migrations.CreateModel(
            name='AudienceIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=64, verbose_name='Возраст')),
                ('income', models.PositiveIntegerField(help_text='тыс. ₽', verbose_name='Доход')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Очередность')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_project_page.ProjectAudience', verbose_name='Аудитория проекта')),
            ],
            options={
                'verbose_name': 'Доход аудитории',
                'verbose_name_plural': 'Доходы аудитории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AudienceFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=64, verbose_name='Ползаголовок')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Очередность')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_project_page.ProjectAudience', verbose_name='Аудитория проекта')),
            ],
            options={
                'verbose_name': 'Факт аудитории',
                'verbose_name_plural': 'Факты аудитории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AudienceAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=64, verbose_name='Возраст')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Очередность')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_project_page.ProjectAudience', verbose_name='Аудитория проекта')),
            ],
            options={
                'verbose_name': 'Возраст аудитории',
                'verbose_name_plural': 'Возраст аудитории',
                'ordering': ('order',),
            },
        ),
    ]
