# Generated by Django 3.0.10 on 2021-09-28 08:39

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_project_page', '0002_auto_20210913_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProjectGallerySlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('video', models.FileField(blank=True, upload_to='cpp/pgs/v', verbose_name='Видео (деск.)')),
                ('video_mobile', models.FileField(blank=True, upload_to='cpp/pgs/vm', verbose_name='Видео (моб.)')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 595', null=True, verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('commercial_project_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_slides', to='commercial_project_page.CommercialProjectPage', verbose_name='Страница коммерческого проекта')),
            ],
            options={
                'verbose_name': 'Слайд галереи',
                'verbose_name_plural': 'Слайды галереи',
                'ordering': ('order',),
            },
        ),
    ]
