# Generated by Django 3.0.10 on 2021-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_project_page', '0003_commercialprojectgalleryslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialprojectpage',
            name='form_image',
            field=models.ImageField(blank=True, upload_to='cpp/fi', verbose_name='Изображение формы'),
        ),
        migrations.AddField(
            model_name='commercialprojectpage',
            name='form_text',
            field=models.TextField(blank=True, verbose_name='Текст формы'),
        ),
        migrations.AddField(
            model_name='commercialprojectpage',
            name='form_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок формы'),
        ),
    ]
