# Generated by Django 3.0.10 on 2021-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_project_page', '0004_auto_20211012_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProjectPageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок формы')),
                ('text', models.TextField(blank=True, verbose_name='Текст формы')),
                ('image', models.ImageField(blank=True, upload_to='cpp/fi', verbose_name='Изображение формы')),
            ],
            options={
                'verbose_name': 'Форма на странице коммерческого проекта',
                'verbose_name_plural': 'Формы на странице коммерческого проекта',
            },
        ),
        migrations.RemoveField(
            model_name='commercialprojectpage',
            name='form_image',
        ),
        migrations.RemoveField(
            model_name='commercialprojectpage',
            name='form_text',
        ),
        migrations.RemoveField(
            model_name='commercialprojectpage',
            name='form_title',
        ),
    ]
