# Generated by Django 3.0.10 on 2021-10-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_project_page', '0005_auto_20211012_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialprojectpage',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial_project_page.CommercialProjectPageForm', verbose_name='Форма'),
        ),
    ]
