# Generated by Django 3.0.14 on 2021-12-02 11:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_project_page', '0007_commercialprojectpage_video_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок блока')),
            ],
            options={
                'verbose_name': "Блок 'MALLTEAM'",
                'verbose_name_plural': "Блок 'MALLTEAM'",
            },
        ),
        migrations.CreateModel(
            name='MallTeamAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cpp/mt/i', verbose_name='Изображение')),
                ('mall_team_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_project_page.MallTeam', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Карточка Преимущества MallTeam',
                'verbose_name_plural': 'Карточки Преимуществ MallTeam',
                'ordering': ('order',),
            },
        ),
    ]
