# Generated by Django 3.0.10 on 2021-03-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Мета ключевые слова')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Промо страница')),
            ],
            options={
                'verbose_name': 'Лендинг',
                'verbose_name_plural': 'Лендинги',
            },
        ),
    ]
