# Generated by Django 3.0.10 on 2021-04-16 13:57

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_property_mini_plan_point'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageBlockItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
                (
                    'subtitle',
                    models.CharField(
                        blank=True, max_length=256, verbose_name='Подзаголовок изображения'
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Элемент блока преимуществ',
                'verbose_name_plural': 'Элементы блока преимуществ',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DigitsBlockItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                (
                    'subtitle',
                    models.CharField(blank=True, max_length=128, verbose_name='Подзаголовок'),
                ),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Элемент блока цифры',
                'verbose_name_plural': 'Элемент блока цифры',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'meta_title',
                    models.CharField(blank=True, max_length=200, verbose_name='Мета заголовок'),
                ),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Мета ключевые слова')),
                (
                    'title',
                    models.CharField(max_length=128, verbose_name='Заголовок главного экрана'),
                ),
                ('slug', models.SlugField(unique=True, verbose_name='Алиас')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Промо-лендинг')),
                ('text', models.TextField(blank=True, verbose_name='Текст главного экрана')),
                (
                    'main_image',
                    ajaximage.fields.AjaxImageField(
                        help_text='шир. - 3200, выс. - 1900',
                        verbose_name='Изображение главного экрана',
                    ),
                ),
                (
                    'end',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='Для промо-лендинга.',
                        null=True,
                        verbose_name='Дата окончания акции',
                    ),
                ),
                (
                    'card_image',
                    models.ImageField(
                        blank=True,
                        help_text='Для промо-лендинга. шир. - 960, выс. - 1120',
                        upload_to='news/images',
                        verbose_name='Изображение на карточке',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Лендинг',
                'verbose_name_plural': 'Лендинги',
            },
        ),
        migrations.CreateModel(
            name='LandingBlock',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name='Порядок'
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Заголовок')),
                (
                    'block_type',
                    models.CharField(
                        choices=[
                            ('one_image', 'Блок с текстом и одним изображением'),
                            ('two_image', 'Блок с текстом и двумя изображением'),
                            ('three_image', 'Блок с текстом и тремя изображением'),
                            ('slider', 'Блок со слайдером'),
                            ('simple_cta', 'Простой блок CTA'),
                            ('text_list', 'Блок с текстом и списком'),
                            ('two_column', 'Блок с иконками в две колонки'),
                            ('furnish', 'Блок с отделкой'),
                            ('digits', 'Блок с цифрами'),
                            ('flats', 'Блок квартир'),
                            ('advantage', 'Блок преимуществ'),
                            ('steps', 'Блок шаги'),
                        ],
                        max_length=64,
                        verbose_name='Тип блока',
                    ),
                ),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                (
                    'image_1',
                    ajaximage.fields.AjaxImageField(blank=True, verbose_name='Изображение'),
                ),
                (
                    'image_1_description',
                    models.TextField(blank=True, verbose_name='Описание изображения'),
                ),
                (
                    'image_2',
                    ajaximage.fields.AjaxImageField(blank=True, verbose_name='Изображение (2)'),
                ),
                (
                    'image_2_description',
                    models.TextField(blank=True, verbose_name='Описание изображения (2)'),
                ),
                (
                    'image_3',
                    ajaximage.fields.AjaxImageField(blank=True, verbose_name='Изображение (3)'),
                ),
                (
                    'image_3_description',
                    models.TextField(blank=True, verbose_name='Описание изображения (3)'),
                ),
                (
                    'is_full_screen',
                    models.BooleanField(
                        default=False,
                        help_text='Для блока со слайдером. В полноэкранном режиме не отображается текст',
                        verbose_name='Full-screen слайды',
                    ),
                ),
                (
                    'cta_block_type',
                    models.CharField(
                        choices=[('presentation', 'Презентация'), ('instruction', 'Инструкция')],
                        default='presentation',
                        help_text='для CTA блока',
                        max_length=20,
                        verbose_name='Тип CTA блока',
                    ),
                ),
                (
                    'item_1',
                    models.CharField(
                        blank=True,
                        help_text='для блока с текстом и списком',
                        max_length=256,
                        verbose_name='Пункт списка (1)',
                    ),
                ),
                (
                    'item_2',
                    models.CharField(blank=True, max_length=256, verbose_name='Пункт списка (2)'),
                ),
                (
                    'item_3',
                    models.CharField(blank=True, max_length=256, verbose_name='Пункт списка (3)'),
                ),
                (
                    'item_4',
                    models.CharField(blank=True, max_length=256, verbose_name='Пункт списка (4)'),
                ),
                ('text_end', models.TextField(blank=True, verbose_name='Текст в конце блока')),
                (
                    'button_name_1',
                    models.CharField(
                        blank=True, max_length=64, verbose_name='Надпись на кнопке (1)'
                    ),
                ),
                (
                    'button_link_1',
                    models.CharField(
                        blank=True, max_length=258, verbose_name='Ссылка на кнопке (1)'
                    ),
                ),
                (
                    'button_name_2',
                    models.CharField(
                        blank=True, max_length=64, verbose_name='Надпись на кнопке (2)'
                    ),
                ),
                (
                    'button_link_2',
                    models.CharField(
                        blank=True, max_length=258, verbose_name='Ссылка на кнопке (2)'
                    ),
                ),
                (
                    'furnishes',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Для блока с отделкой',
                        to='properties.Furnish',
                        verbose_name='Варианты отделки',
                    ),
                ),
                (
                    'landing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='landing.Landing',
                        verbose_name='Лендинг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Блок лендинга',
                'verbose_name_plural': 'Блоки лендинга',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SliderBlockSlide',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                (
                    'block',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='slides',
                        to='landing.LandingBlock',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Слайд блока со слайдером',
                'verbose_name_plural': 'Слайды блока со слайдером',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='StepsBlockItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                (
                    'block',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='steps',
                        to='landing.LandingBlock',
                        verbose_name='Блок',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Элемент блока шаги',
                'verbose_name_plural': 'Элемент блока шаги',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TwoColumnsBlockItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
                ),
                (
                    'subtitle',
                    models.CharField(
                        blank=True, max_length=256, verbose_name='Подзаголовок изображения'
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                (
                    'block',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='two_column_items',
                        to='landing.LandingBlock',
                        verbose_name='Блок',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Элемент блока c иконками в две колонки',
                'verbose_name_plural': 'Элементы блока c иконками в две колонки',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
        migrations.AddField(
            model_name='digitsblockitem',
            name='block',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='digit_items',
                to='landing.LandingBlock',
                verbose_name='Блок',
            ),
        ),
        migrations.AddField(
            model_name='advantageblockitem',
            name='block',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='advantages',
                to='landing.LandingBlock',
                verbose_name='Блок',
            ),
        ),
    ]
