# Generated by Django 3.0.10 on 2021-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210419_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(
                choices=[
                    ('oneImage', 'Блок с текстом и одним изображением'),
                    ('twoImage', 'Блок с текстом и двумя изображением'),
                    ('threeImage', 'Блок с текстом и тремя изображением'),
                    ('slider', 'Блок со слайдером'),
                    ('simpleCta', 'Простой блок CTA'),
                    ('textList', 'Блок с текстом и списком'),
                    ('twoColumn', 'Блок с иконками в две колонки'),
                    ('furnish', 'Блок с отделкой'),
                    ('digits', 'Блок с цифрами'),
                    ('flats', 'Блок квартир'),
                    ('advantage', 'Блок преимуществ'),
                    ('steps', 'Блок шаги'),
                    ('mortgage', 'Блок с ипотекой'),
                    ('progress', 'Ход строительства'),
                ],
                max_length=64,
                verbose_name='Тип блока',
            ),
        ),
    ]
