# Generated by Django 3.0.10 on 2021-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20210413_1343'),
        ('landing', '0004_auto_20210419_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingblock',
            name='anchor',
            field=models.CharField(blank=True, max_length=32, verbose_name='Якорь блока'),
        ),
        migrations.AddField(
            model_name='landingblock',
            name='news_set',
            field=models.ManyToManyField(blank=True, help_text='Для блока новости', related_name='_landingblock_news_set_+', to='news.News', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('oneImage', 'Блок с текстом и одним изображением'), ('twoImage', 'Блок с текстом и двумя изображением'), ('threeImage', 'Блок с текстом и тремя изображением'), ('slider', 'Блок со слайдером'), ('simpleCta', 'Простой блок CTA'), ('textList', 'Блок с текстом и списком'), ('twoColumn', 'Блок с иконками в две колонки'), ('furnish', 'Блок с отделкой'), ('digits', 'Блок с цифрами'), ('flats', 'Блок квартир'), ('advantage', 'Блок преимуществ'), ('steps', 'Блок шаги'), ('mortgage', 'Блок с ипотекой'), ('progress', 'Ход строительства'), ('forms', 'Блок с формами'), ('news', 'Блок с новостями')], max_length=64, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='progress_set',
            field=models.ManyToManyField(blank=True, help_text='Для блока прогресс', limit_choices_to={'type': 'progress'}, related_name='_landingblock_progress_set_+', to='news.News', verbose_name='Новости ход строительства'),
        ),
    ]
