# Generated by Django 3.0.10 on 2021-04-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20210409_1421'),
        ('landing', '0005_auto_20210419_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingblock',
            name='image_3_description',
        ),
        migrations.AddField(
            model_name='landingblock',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Для блока квартир и прогресс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('oneImage', 'Блок с текстом и одним изображением'), ('twoImage', 'Блок с текстом и двумя изображением'), ('threeImage', 'Блок с текстом и тремя изображением'), ('titleText', 'Блок с заголовком и текстом'), ('slider', 'Блок со слайдером'), ('simpleCta', 'Простой блок CTA'), ('textList', 'Блок с текстом и списком'), ('twoColumn', 'Блок с иконками в две колонки'), ('furnish', 'Блок с отделкой'), ('digits', 'Блок с цифрами'), ('flats', 'Блок квартир'), ('advantage', 'Блок преимуществ'), ('steps', 'Блок шаги'), ('mortgage', 'Блок с ипотекой'), ('progress', 'Ход строительства'), ('forms', 'Блок с формами'), ('news', 'Блок с новостями')], max_length=64, verbose_name='Тип блока'),
        ),
    ]
