# Generated by Django 3.0.10 on 2021-04-20 12:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20210420_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingblock',
            name='presentation',
            field=models.FileField(blank=True, help_text='для CTA блока, будет отправлена на почту', upload_to='lnd/cta/f', verbose_name='Презентация'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст главного экрана'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('oneImage', 'Блок с текстом и одним изображением'), ('twoImage', 'Блок с двумя изображениями и описаниями к ним'), ('threeImage', 'Блок с коллажом из трех изображений'), ('titleText', 'Блок с заголовком и текстом'), ('slider', 'Блок со слайдером'), ('simpleCta', 'Простой блок CTA'), ('textList', 'Блок с текстом и списком'), ('twoColumn', 'Блок с иконками в две колонки'), ('furnish', 'Блок с отделкой'), ('digits', 'Блок с цифрами'), ('flats', 'Блок квартир'), ('advantage', 'Блок преимуществ'), ('steps', 'Блок шаги'), ('mortgage', 'Блок с ипотекой'), ('progress', 'Ход строительства'), ('forms', 'Блок с формами'), ('news', 'Блок с новостями')], max_length=64, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
    ]
