# Generated by Django 3.0.10 on 2021-04-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20210420_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='main_image',
            field=models.ImageField(help_text='шир. - 3200, выс. - 1900', upload_to='lnd/i', verbose_name='Изображение главного экрана'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='lnd/lb/i', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='lnd/lb/i2', verbose_name='Изображение (2)'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='lnd/lb/i3', verbose_name='Изображение (3)'),
        ),
    ]
