# Generated by Django 3.0.10 on 2021-04-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20210420_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingblock',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='item_4',
        ),
        migrations.CreateModel(
            name='ListBlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='landing.LandingBlock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент блока со списокм',
                'verbose_name_plural': 'Элементы блока со списокм',
                'ordering': ('order',),
            },
        ),
    ]
