# Generated by Django 3.0.10 on 2021-05-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0022_news_projects"),
        ("projects", "0063_merge_20210409_1631"),
        ("landing", "0009_auto_20210422_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="landing_news",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.News",
                verbose_name="Новость лендинга",
            ),
        ),
        migrations.AddField(
            model_name="landing",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Для промо-лендинга. Проекты будут установлены для связанной Новости",
                to="projects.Project",
                verbose_name="Проекты",
            ),
        ),
        migrations.AddField(
            model_name="landingblock",
            name="send_to_email",
            field=models.BooleanField(
                default=False,
                help_text="Если включен, появится форма с email, иначе будет отображаться кнопка 'Скачать'",
                verbose_name="Отправлять презентацию на почту",
            ),
        ),
        migrations.AlterField(
            model_name="landingblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("OneImage", "Блок с текстом и одним изображением"),
                    ("TwoImage", "Блок с двумя изображениями и описаниями к ним"),
                    ("ThreeImage", "Блок с коллажом из трех изображений"),
                    ("TitleText", "Блок с заголовком и текстом"),
                    ("Image", "Изображение"),
                    ("Panorama", "Панорама"),
                    ("Slider", "Блок со слайдером"),
                    ("SimpleCta", "Простой блок CTA"),
                    ("TextList", "Блок с текстом и списком"),
                    ("TwoColumn", "Блок с иконками в две колонки"),
                    ("Furnish", "Блок с отделкой"),
                    ("Digits", "Блок с цифрами"),
                    ("Flats", "Блок квартир"),
                    ("Advantage", "Блок преимуществ"),
                    ("Steps", "Блок шаги"),
                    ("Mortgage", "Блок с ипотекой"),
                    ("Progress", "Ход строительства"),
                    ("Forms", "Блок с формами"),
                    ("News", "Блок с новостями"),
                ],
                max_length=64,
                verbose_name="Тип блока",
            ),
        ),
    ]
