# Generated by Django 3.0.10 on 2021-05-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0044_auto_20210518_1316"),
        ("landing", "0010_auto_20210519_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingblock",
            name="flat_set",
            field=models.ManyToManyField(
                blank=True,
                help_text="Для блока квартир",
                limit_choices_to={"status": 0, "type": "flat"},
                to="properties.Property",
                verbose_name="Квартиры",
            ),
        )
    ]
