# Generated by Django 3.0.10 on 2020-10-13 06:35

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("cities", "0003_metro_metroline_transport")]

    operations = [
        migrations.CreateModel(
            name="CommercialPropertyPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница коммерческой недвижимости",
                "verbose_name_plural": "Страницы коммерческой недвижимости",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "logo",
                    ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name="Логотип"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Арендатор",
                "verbose_name_plural": "Арендаторы",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="CommercialPropertyPageSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Изображение"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="commercial_property_page/slide",
                        verbose_name="Видео",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_set",
                        to="commercial_property_page.CommercialPropertyPage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд на странице коммерческой недвижимости",
                "verbose_name_plural": "Слайды на странице коммерческой недвижимости",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="CommercialPropertyPageAdvantage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст")),
                ("file", ajaximage.fields.AjaxImageField(verbose_name="Файл")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage_set",
                        to="commercial_property_page.CommercialPropertyPage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество на странице коммерческой недвижимости",
                "verbose_name_plural": "Преимущества на странице коммерческой недвижимости",
                "ordering": ("order",),
            },
        ),
    ]
