# Generated by Django 3.0.10 on 2020-11-03 10:56

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial_property_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_1",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 1 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 2 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_3",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 3 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_4",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 4 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Блок 1 / Заголовок"),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_1",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 2 / Элемент 1 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 2 / Элемент 2 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_3",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 2 / Элемент 3 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_4",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 2 / Элемент 4 / Заголовок"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Блок 2 / Заголовок"),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="video",
            field=models.CharField(blank=True, max_length=2000, verbose_name="Видео"),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="video_description",
            field=models.TextField(blank=True, verbose_name="Видео / Описание"),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="video_preview",
            field=ajaximage.fields.AjaxImageField(
                blank=True, null=True, verbose_name="Видео / Превью"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="video_title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Видео / Заголовок"),
        ),
    ]
