# Generated by Django 3.0.10 on 2020-11-05 15:20

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial_property_page", "0002_auto_20201103_1056"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_1_item_1",
            new_name="block_1_item_1_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_1_item_2",
            new_name="block_1_item_2_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_1_item_3",
            new_name="block_1_item_3_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_1_item_4",
            new_name="block_1_item_4_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_2_item_1",
            new_name="block_2_item_1_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_2_item_2",
            new_name="block_2_item_2_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_2_item_3",
            new_name="block_2_item_3_title",
        ),
        migrations.RenameField(
            model_name="commercialpropertypage",
            old_name="block_2_item_4",
            new_name="block_2_item_4_title",
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_image",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 1 / Изображение",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_1_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 1 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_2_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 2 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_3_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 3 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_item_4_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 4 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_image",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 2 / Изображение",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_1_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 1 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_2_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 2 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_3_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 3 / Текст"
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_item_4_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок 1 / Элемент 4 / Текст"
            ),
        ),
        migrations.AlterField(
            model_name="commercialpropertypage",
            name="video",
            field=models.CharField(blank=True, max_length=2000, verbose_name="сылка на видео"),
        ),
        migrations.AlterField(
            model_name="commercialpropertypage",
            name="video_preview",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 1920, выс. - 1080",
                null=True,
                verbose_name="Видео / Превью",
            ),
        ),
    ]
