# Generated by Django 3.0.10 on 2020-11-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial_property_page", "0003_auto_20201105_1520"),
    ]

    operations = [
        migrations.RemoveField(model_name="commercialpropertypageslide", name="video",),
        migrations.AddField(
            model_name="commercialpropertypageslide",
            name="video_link",
            field=models.URLField(blank=True, verbose_name="Ссылка на видео"),
        ),
    ]
