# Generated by Django 3.0.10 on 2020-11-09 07:16

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commercial_property_page", "0004_auto_20201106_0654"),
    ]

    operations = [
        migrations.RemoveField(model_name="commercialpropertypage", name="block_1_image",),
        migrations.RemoveField(model_name="commercialpropertypage", name="block_2_image",),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_image_1",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 1 / Изображение 1",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_image_2",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 1 / Изображение 2",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_image_3",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 1 / Изображение 3",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_1_image_4",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 1 / Изображение 4",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_image_1",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 2 / Изображение 1",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_image_2",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 2 / Изображение 2",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_image_3",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 2 / Изображение 3",
            ),
        ),
        migrations.AddField(
            model_name="commercialpropertypage",
            name="block_2_image_4",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 720, выс. - 720",
                null=True,
                verbose_name="Блок 2 / Изображение 4",
            ),
        ),
    ]
