# Generated by Django 3.0.10 on 2020-12-05 12:20

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0005_auto_20201109_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_1_image_1',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 1 / Изображение 1'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_1_image_2',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 1 / Изображение 2'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_1_image_3',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 1 / Изображение 3'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_1_image_4',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 1 / Изображение 4'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_2_image_1',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 2 / Изображение 1'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_2_image_2',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 2 / Изображение 2'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_2_image_3',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 2 / Изображение 3'),
        ),
        migrations.AlterField(
            model_name='commercialpropertypage',
            name='block_2_image_4',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1440, выс. - 1440', null=True, verbose_name='Блок 2 / Изображение 4'),
        ),
    ]
