# Generated by Django 3.0.10 on 2020-12-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commercial_property_page", "0006_auto_20201205_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercialpropertypageadvantage",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advantage_set",
                to="commercial_property_page.CommercialPropertyPage",
                verbose_name="Страница коммерческой недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="commercialpropertypageslide",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slide_set",
                to="commercial_property_page.CommercialPropertyPage",
                verbose_name="Страница коммерческой недвижимости",
            ),
        ),
    ]
