# Generated by Django 3.0.10 on 2021-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_auto_20201211_0708'),
        ('commercial_property_page', '0007_auto_20201211_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialpropertypage',
            name='tenant_block_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока арендаторов'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cities.City', verbose_name='Города'),
        ),
    ]
