# Generated by Django 3.0.10 on 2021-01-28 09:36

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0008_auto_20210115_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialRentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('success', models.CharField(blank=True, max_length=200, verbose_name='Сообщение при успешной отправке')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Текст на кнопке')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('yandex_metrics', models.CharField(blank=True, max_length=100, null=True, verbose_name='Яндекс метрика')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 500, выс. - 440', null=True, verbose_name='Изображение')),
                ('image_phone', models.ImageField(blank=True, null=True, upload_to='f/ip', verbose_name='Изображение телефон')),
            ],
            options={
                'verbose_name': 'Форма на странице коммерции',
                'verbose_name_plural': 'Формы на странице коммерции',
            },
        ),
    ]
