# Generated by Django 3.0.10 on 2021-02-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0010_commercialrentformemployee'),
        ('commercial_property_page', '0010_hide_page_field'),
    ]

    operations = [
    ]
