# Generated by Django 3.0.10 on 2021-03-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0010_hide_page_field'),
        ('commercial_property_page', '0010_commercialrentformemployee'),
    ]

    operations = [
    ]
