# Generated by Django 3.0.10 on 2021-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0011_merge_20210304_1403'),
        ('commercial_property_page', '0011_merge_20210225_1247'),
    ]

    operations = [
    ]
