# Generated by Django 3.0.10 on 2021-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_property_is_disable_online_booking'),
        ('commercial_property_page', '0012_commercialrentform_google_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialpropertypage',
            name='furnish_set',
            field=models.ManyToManyField(blank=True, to='properties.Furnish', verbose_name='Варианты отделки'),
        ),
    ]
