# Generated by Django 3.0.10 on 2021-03-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0012_merge_20210304_1455'),
        ('commercial_property_page', '0012_commercialrentform_google_event_name'),
    ]

    operations = [
    ]
