# Generated by Django 3.0.10 on 2021-03-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_property_page', '0013_merge_20210309_1608'),
        ('commercial_property_page', '0013_commercialpropertypage_furnish_set'),
    ]

    operations = [
    ]
