# Generated by Django 3.0.14 on 2022-06-03 08:20

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1239, выс. - 566', null=True, verbose_name='Изображение')),
                ('pop_up_type', models.CharField(choices=[('refurbished', 'С ремонтом'), ('smart_house', 'Умный дом')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Refurbished',
        ),
        migrations.DeleteModel(
            name='SmartHouse',
        ),
    ]
