# Generated by Django 3.0.14 on 2022-06-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0003_auto_20220607_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='pop_up_type',
            field=models.CharField(choices=[('refurbished', 'С ремонтом'), ('smart_house', 'Умный дом'), ('submit_application_1', 'Оставить заявку 1'), ('submit_application_2', 'Оставить заявку 2'), ('submit_application_3', 'Оставить заявку 3'), ('subscribe', 'Подписаться на рассылку'), ('mortgage_application_1', 'Заявка на ипотеку 1'), ('callback_1', 'Обратный звонок 1'), ('one_step_1', 'Вы в шаге от ответа 1'), ('one_step_2', 'Вы в шаге от ответа 2'), ('one_step_3', 'Вы в шаге от ответа 3'), ('auction_1', 'Уведомим о начале аукциона 1'), ('auction_2', 'Уведомим о начале аукциона 2'), ('mortgage_application_2', 'Заявка на ипотеку 2'), ('installment_application', 'Заявка на рассрочку'), ('callback_2', 'Обратный звонок 2'), ('anti_corruption', 'Противодействие коррупции'), ('callback_3', 'Обратный звонок 3'), ('callback_4', 'Обратный звонок 4'), ('callback_5', 'Обратный звонок 5'), ('callback_6', 'Обратный звонок 6'), ('meeting_registration_1', 'Запись на встречу 1'), ('callback_7', 'Обратный звонок 7'), ('meeting_registration_2', 'Запись на встречу 2'), ('callback_8', 'Обратный звонок 8'), ('callback_9', 'Обратный звонок 9'), ('callback_10', 'Обратный звонок 10'), ('callback_11', 'Обратный звонок 11'), ('callback_12', 'Обратный звонок 12'), ('untitled_1', 'Без названия 1'), ('callback_13', 'Обратный звонок 13'), ('callback_14', 'Обратный звонок 14'), ('callback_15', 'Обратный звонок 15'), ('excursion', 'Записаться на экскурсию'), ('callback_16', 'Обратный звонок 16'), ('callback_17', 'Обратный звонок 17'), ('callback_18', 'Обратный звонок 18'), ('to_director_1', 'Письмо директору 1'), ('to_director_2', 'Письмо директору 2'), ('newsletter_subscription_1', 'Подписка на рассылку 1'), ('newsletter_subscription_2', 'Подписка на рассылку 2'), ('showing', 'Записаться на показ'), ('to_director_3', 'Письмо директору 3'), ('newsletter_subscription_3', 'Подписка на рассылку 3'), ('untitled_2', 'Без названия 2'), ('newsletter_subscription_4', 'Подписка на рассылку 4'), ('like', 'Понравился проект?'), ('untitled_3', 'Без названия 3')], max_length=255, unique=True),
        ),
    ]
