# Generated by Django 3.0.14 on 2022-06-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0004_auto_20220608_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись к картинке'),
        ),
    ]
