# Generated by Django 3.0.14 on 2022-06-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0005_popup_alt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopUp',
        ),
    ]
