# Generated by Django 3.0.14 on 2022-06-09 09:42

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pop_ups', '0006_delete_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1239, выс. - 566', null=True, verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Подпись к картинке')),
            ],
        ),
        migrations.CreateModel(
            name='PopUpTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='Тэг')),
                ('name', models.CharField(max_length=200, verbose_name='Название Поп-апа')),
                ('pop_up_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pop_ups.PopUpInfo')),
            ],
        ),
    ]
