# Generated by Django 3.0.14 on 2022-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('pop_ups', '0007_popupinfo_popuptag'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupinfo',
            name='city',
            field=models.ManyToManyField(blank=True, to='cities.City', verbose_name='Город'),
        ),
    ]
