# Generated by Django 3.0.14 on 2022-06-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0008_popupinfo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popuptag',
            name='pop_up_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pop_ups.PopUpInfo'),
        ),
    ]
