# Generated by Django 3.0.14 on 2022-06-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0009_auto_20220621_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popuptag',
            name='pop_up_info',
        ),
    ]
