# Generated by Django 3.0.14 on 2022-06-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0010_remove_popuptag_pop_up_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupinfo',
            name='pop_up_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pop_ups.PopUpTag', verbose_name='Pop up tag'),
        ),
    ]
