# Generated by Django 3.0.14 on 2022-06-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_project_presentation_link'),
        ('pop_ups', '0011_popupinfo_pop_up_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupinfo',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Проекты'),
        ),
    ]
