# Generated by Django 3.0.14 on 2022-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_ups', '0012_popupinfo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popuptag',
            name='tag',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тэг'),
        ),
    ]
