from .main_page_content import MainPageContentAdmin
from .main_page_manager import MainPageManagerAdmin
from .main_page_offer import MainPageOfferAdmin
from .main_page_partner_logo import MainPagePartnerLogoAdmin
from .main_page_sell_online import MainPageSellOnlineAdmin
