# Generated by Django 3.1 on 2024-01-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.CharField(max_length=30, verbose_name='Слаг')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Тип консультации',
                'verbose_name_plural': '6.9. [Справочник] Тип консультации',
                'db_table': 'users_consultation_type',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AmoCrmCheckLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50, verbose_name='Статус ответа')),
                ('status', models.IntegerField(verbose_name='Статус ответа')),
                ('request_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отправленные данные')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Тело ответа(Пустое если статус ответа 200)')),
                ('check_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disputes.checkhistory', verbose_name='запрос и  ответ АМО')),
            ],
            options={
                'verbose_name': 'Лог: ',
                'verbose_name_plural': '6.8. [Логи] Логи запросов в AmoCrm',
                'db_table': 'users_amocrm_checks_history_log',
            },
        ),
    ]
