from .mortgage_text_block import MortgageTextBlockResponseSchema
from .get_amo_statuses_pipelines import AmoStatusesPipelinesSchema
from .get_bookings_agents import BookingsAgentsSchema
from .send_amo_data import SendAmoDataSchema
from .archive_ticket_status import ArchiveTicketStatusSchema
from .send_ddu_form import SendDDUFormSchema
