# Generated by Django 3.0.8 on 2020-09-24 14:57

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("sites", "0002_alter_domain_unique")]

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "news_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Новости / Заголовок"
                    ),
                ),
                (
                    "news_image",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Изображение"
                    ),
                ),
                (
                    "ideology_text_1",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Идеология / Текст 1"),
                ),
                (
                    "ideology_text_2",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Идеология / Текст 2"),
                ),
                (
                    "ideology_image_1",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Идеология / Изображение 1"
                    ),
                ),
                (
                    "ideology_image_2",
                    ajaximage.fields.AjaxImageField(
                        blank=True, null=True, verbose_name="Идеология / Изображение 1"
                    ),
                ),
                (
                    "ideology_button_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Идеология / Текст кнопки"
                    ),
                ),
                (
                    "ideology_button_link",
                    models.URLField(blank=True, verbose_name="Идеология / Ссылка на кнопке"),
                ),
                (
                    "map_text",
                    models.CharField(blank=True, max_length=400, verbose_name="Карта / Текст"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.Site",
                    ),
                ),
            ],
            options={"verbose_name": "Главная страница", "verbose_name_plural": "Главные страницы"},
        ),
        migrations.CreateModel(
            name="MainPageSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст")),
                (
                    "button_text",
                    models.CharField(blank=True, max_length=100, verbose_name="Текст кнопки"),
                ),
                ("button_link", models.URLField(blank=True, verbose_name="Ссылка на кнопке")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("file", ajaximage.fields.AjaxImageField(verbose_name="Файл")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="main_page.MainPage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд на главной",
                "verbose_name_plural": "Слайды на главной",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="MainPageIdeologyCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(blank=True, verbose_name="Текст")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("file", ajaximage.fields.AjaxImageField(verbose_name="Файл")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideology_cards",
                        to="main_page.MainPage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка идеологии на главной",
                "verbose_name_plural": "Карточки идеологии на главной",
                "ordering": ("order",),
            },
        ),
    ]
