# Generated by Django 3.0.10 on 2020-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_page", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MapText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=400, verbose_name="Текст")),
                (
                    "red_text",
                    models.CharField(blank=True, max_length=400, verbose_name="Красный текст"),
                ),
            ],
            options={"verbose_name": "Текст для карты", "verbose_name_plural": "Тексты для карты"},
        ),
        migrations.RemoveField(model_name="mainpage", name="map_text"),
        migrations.AddField(
            model_name="mainpageslide",
            name="red_text",
            field=models.CharField(blank=True, max_length=400, verbose_name="Красный текст"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="map_texts",
            field=models.ManyToManyField(
                blank=True, to="main_page.MapText", verbose_name="Тексты для карты"
            ),
        ),
    ]
