# Generated by Django 3.0.10 on 2020-10-22 06:52

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0003_auto_20201016_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="ideology_video_link_1",
            field=models.URLField(blank=True, verbose_name="Идеология / Ссылка на видео 1"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="ideology_video_link_2",
            field=models.URLField(blank=True, verbose_name="Идеология / Ссылка на видео 2"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="ideology_video_preview_1",
            field=ajaximage.fields.AjaxImageField(
                blank=True, null=True, verbose_name="Идеология / Превью видео 1"
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="ideology_video_preview_2",
            field=ajaximage.fields.AjaxImageField(
                blank=True, null=True, verbose_name="Идеология / Превью видео 2"
            ),
        ),
    ]
