# Generated by Django 3.0.10 on 2020-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0004_auto_20201022_0652"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="side_block_link_1",
            field=models.URLField(blank=True, null=True, verbose_name="Боковой блок 1 / Ссылка"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="side_block_link_2",
            field=models.URLField(blank=True, null=True, verbose_name="Боковой блок 2 / Ссылка"),
        ),
    ]
