# Generated by Django 3.0.10 on 2020-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_page", "0005_auto_20201112_0711")]

    operations = [
        migrations.RemoveField(model_name="mainpageslide", name="file"),
        migrations.AddField(
            model_name="mainpageslide",
            name="image_desktop_big",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mp/mps/idb",
                verbose_name="Изображение десктоп (большое)",
            ),
        ),
        migrations.AddField(
            model_name="mainpageslide",
            name="image_desktop_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mp/mps/ids",
                verbose_name="Изображение десктоп (маленькое)",
            ),
        ),
        migrations.AddField(
            model_name="mainpageslide",
            name="image_phone",
            field=models.ImageField(
                blank=True, null=True, upload_to="mp/mps/ip", verbose_name="Изображение телефон"
            ),
        ),
        migrations.AddField(
            model_name="mainpageslide",
            name="image_tablet",
            field=models.ImageField(
                blank=True, null=True, upload_to="mp/mps/it", verbose_name="Изображение планшет"
            ),
        ),
    ]
