# Generated by Django 3.0.10 on 2020-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0006_auto_20201118_1307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpageslide",
            name="button_link",
            field=models.SlugField(blank=True, max_length=100, verbose_name="Ссылка на кнопке"),
        ),
    ]
