# Generated by Django 3.0.10 on 2020-12-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("main_page", "0008_auto_20201127_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpage",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.Site",
                verbose_name="Сайт",
            ),
        ),
        migrations.AlterField(
            model_name="mainpageideologycard",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideology_cards",
                to="main_page.MainPage",
                verbose_name="Главная страница",
            ),
        ),
        migrations.AlterField(
            model_name="mainpageslide",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slides",
                to="main_page.MainPage",
                verbose_name="Главная страница",
            ),
        ),
    ]
