# Generated by Django 3.0.10 on 2020-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_page", "0009_auto_20201211_1310")]

    operations = [
        migrations.AlterField(
            model_name="mainpageslide",
            name="button_link",
            field=models.CharField(blank=True, max_length=1000, verbose_name="Ссылка на кнопке"),
        )
    ]
