# Generated by Django 3.0.10 on 2021-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_page", "0010_auto_20201230_1020")]

    operations = [
        migrations.AddField(
            model_name="mainpageslide",
            name="blank",
            field=models.BooleanField(
                default=False, verbose_name="Открывать ссылку в новой вкладке"
            ),
        )
    ]
