# Generated by Django 3.0.10 on 2021-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_page", "0011_mainpageslide_blank")]

    operations = [
        migrations.AddField(
            model_name="mainpageslide",
            name="form_title",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="Заголовок формы",
                help_text="Если заполнен, на слайде появляется форма",
            ),
        )
    ]
