# Generated by Django 3.0.10 on 2021-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main_page", "0012_mainpageslide_form_title")]

    operations = [
        migrations.AddField(
            model_name="mainpageslide",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="При наступлении даты, слайд деактивируется",
                null=True,
                verbose_name="Дата окончания",
            ),
        ),
        migrations.AddField(
            model_name="mainpageslide",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
