# Generated by Django 3.0.10 on 2021-09-13 07:33

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20210630_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main_page.MainPage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'История о на главной странице',
                'verbose_name_plural': 'Истории на главных страницах',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='MainPageStoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('file', ajaximage.fields.AjaxImageField(verbose_name='Файл')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_page.MainPageStory', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Изображение истории о компании',
                'verbose_name_plural': 'Изображения истории о компании',
                'ordering': ('order',),
            },
        ),
    ]
