# Generated by Django 3.0.10 on 2021-09-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_mainpagestory_mainpagestoryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagestory',
            options={'ordering': ('order',), 'verbose_name': 'История главной страницы', 'verbose_name_plural': 'Истории главных страницах'},
        ),
    ]
