# Generated by Django 3.0.14 on 2022-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0016_projectslide"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectSlide",
        ),
    ]
