# Generated by Django 3.0.14 on 2022-06-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_delete_projectslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='side_block_title_2_mobile',
            field=models.CharField(blank=True, max_length=200, verbose_name='Боковой блок 2 мообильный / Заголовок'),
        ),
    ]
