# Generated by Django 3.0.14 on 2022-10-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0126_project_is_business'),
        ('main_page', '0018_mainpage_side_block_title_2_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageslide',
            name='button_projects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект'),
        ),
    ]
