# Generated by Django 3.0.14 on 2022-10-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_mainpageslide_button_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpageslide',
            old_name='button_projects',
            new_name='button_project',
        ),
    ]
