from .person_admin import PersonAdmin
from .tender_admin import TenderAdmin
from .tender_category_admin import TenderCategoryAdmin
from .document_admin import DocumentAdmin
from .document_category_admin import DocumentCategoryAdmin
from .partners_page_admin import PartnersPageAdmin
from .about_page_admin import AboutPageAdmin
from .offers_document_admin import OffersDocumentAdmin
from .stories_admin import StoryAdmin
from .stable_documents_admin import StableDocumentAdmin
