# Generated by Django 3.0.10 on 2020-10-02 12:30

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0004_auto_20201002_1230"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "type_list",
                    common.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("vacancy", "Отклик на вакансию"),
                                ("sale", "Заявка на продажу участка"),
                            ],
                            max_length=20,
                        ),
                        size=None,
                        verbose_name="Типы заявок",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный"),),
            ],
            options={"verbose_name": "Менеджер", "verbose_name_plural": "Менеджеры",},
        ),
        migrations.CreateModel(
            name="SaleRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер"
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(max_length=13, verbose_name="Кадастровый номер"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сопроводительное письмо"),),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки"),
                ),
            ],
            options={
                "verbose_name": "Заявка на продажу участка",
                "verbose_name_plural": "Заявки на продажу участка",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="VacancyRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер"
                    ),
                ),
                ("resume", models.FileField(blank=True, upload_to="", verbose_name="Резюме"),),
                ("message", models.TextField(blank=True, verbose_name="Сопроводительное письмо"),),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.Vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик на вакансию",
                "verbose_name_plural": "Отклики на вакансии",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="SaleRequestDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="requests/sale", verbose_name="Файл"),),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_set",
                        to="request_forms.SaleRequest",
                        verbose_name="Заявка на продажу участка",
                    ),
                ),
            ],
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы",},
        ),
    ]
