# Generated by Django 3.0.10 on 2020-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancyrequest",
            name="resume",
            field=models.FileField(blank=True, upload_to="request/vacancy", verbose_name="Резюме"),
        ),
    ]
