# Generated by Django 3.0.10 on 2020-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0006_auto_20201027_0843"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время подписки"),
                ),
            ],
            options={
                "verbose_name": "Подписка на рассылку",
                "verbose_name_plural": "Подписки на рассылку",
                "ordering": ("-date",),
            },
        ),
    ]
