# Generated by Django 3.0.10 on 2020-11-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_auto_20201106_1319"),
        ("request_forms", "0008_auto_20201103_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="callbackrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
            ),
        ),
        migrations.AddField(
            model_name="callbackrequest",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="directorcommunicaterequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
            ),
        ),
        migrations.AddField(
            model_name="directorcommunicaterequest",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="excursionrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
            ),
        ),
        migrations.AddField(
            model_name="excursionrequest",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="purchasehelprequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
            ),
        ),
        migrations.AddField(
            model_name="purchasehelprequest",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="reservationrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
            ),
        ),
        migrations.AddField(
            model_name="reservationrequest",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                    ("pantry", "Кладовка"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
