# Generated by Django 3.0.10 on 2020-11-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0014_auto_20201109_1449"),
        ("request_forms", "0009_auto_20201106_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancyrequest",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.Vacancy",
                verbose_name="Вакансия",
            ),
        ),
    ]
