# Generated by Django 3.0.10 on 2020-11-11 09:14

import ajaximage.fields
import ckeditor.fields
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_auto_20201106_1319"),
        ("request_forms", "0010_auto_20201110_1355"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("description", ckeditor.fields.RichTextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 500, выс. - 453",
                        null=True,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Текст на кнопке"),
                ),
                ("full_name", models.CharField(blank=True, max_length=200, verbose_name="ФИО")),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=200, verbose_name="Должность"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Форма кастомной заявки",
                "verbose_name_plural": "Формы кастомных заявок",
            },
        ),
        migrations.AlterField(
            model_name="manager",
            name="type_list",
            field=common.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("vacancy", "Отклик на вакансию"),
                        ("sale", "Заявка на продажу участка"),
                        ("callback", "Заявка на обратный звонок"),
                        ("reservation", "Заявка на бронирование"),
                        ("excursion", "Запись на экскурсию"),
                        ("director", "Запрос на связь с директором"),
                        ("purchase", "Заявка на помощь с оформлением покупки"),
                        ("custom", "Кастомная заявка"),
                    ],
                    max_length=20,
                ),
                size=None,
                verbose_name="Типы заявок",
            ),
        ),
        migrations.CreateModel(
            name="CustomRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "Квартира"),
                            ("parking", "Парковочное место"),
                            ("commercial", "Коммерческое помещение"),
                            ("pantry", "Кладовка"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="request_forms.CustomForm",
                        verbose_name="Форма",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кастомная заявка",
                "verbose_name_plural": "Кастомные заявки",
                "ordering": ("-date",),
            },
        ),
    ]
