# Generated by Django 3.0.10 on 2020-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0012_customrequest_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorcommunicaterequest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Адрес электронной почты"
            ),
        ),
        migrations.AddField(
            model_name="directorcommunicaterequest",
            name="message",
            field=models.TextField(default="", verbose_name="Сообщение"),
            preserve_default=False,
        ),
    ]
