# Generated by Django 3.0.10 on 2020-11-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0013_auto_20201112_0517"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directorcommunicaterequest", old_name="message", new_name="text",
        ),
    ]
