# Generated by Django 3.0.10 on 2020-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0014_auto_20201112_1006"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="success",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Сообщение при успешной отправке"
            ),
        ),
    ]
