# Generated by Django 3.0.10 on 2020-11-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0017_customform_image_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customform", old_name="image_mobile", new_name="image_phone",
        ),
    ]
