# Generated by Django 3.0.10 on 2020-12-05 12:20

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0019_salerequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1000, выс. - 906', null=True, verbose_name='Изображение'),
        ),
    ]
