# Generated by Django 3.0.10 on 2020-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0020_auto_20201205_1220"),
    ]

    operations = [
        migrations.AddField(
            model_name="customform",
            name="yandex_metrics",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Яндекс метрика"
            ),
        ),
    ]
