# Generated by Django 3.0.10 on 2020-12-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_auto_20201214_0725"),
        ("request_forms", "0021_customform_yandex_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="callbackrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="contractorrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="customrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="directorcommunicaterequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="excursionrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="purchasehelprequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="reservationrequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.Project",
                verbose_name="Проект",
            ),
        ),
    ]
