# Generated by Django 3.0.10 on 2020-12-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_auto_20201218_1431'),
        ('request_forms', '0022_auto_20201214_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Property', verbose_name='Помещение'),
        ),
    ]
