# Generated by Django 3.0.10 on 2020-12-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0023_reservationrequest_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='type_form',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип для обработки запроса'),
        ),
    ]
