# Generated by Django 3.0.10 on 2021-01-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_merge_20210128_1044'),
        ('properties', '0031_auto_20210121_1115'),
        ('request_forms', '0024_customform_type_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationLKRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('property_type', models.CharField(choices=[('flat', 'Квартира'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение'), ('pantry', 'Кладовка')], max_length=20, verbose_name='Тип')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Проект')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Property', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование в ЛК',
                'verbose_name_plural': 'Заявки на бронирование в ЛК',
                'ordering': ('-date',),
            },
        ),
    ]
