# Generated by Django 3.0.10 on 2021-01-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0025_auto_20210126_1736'),
        ('request_forms', '0025_reservationlkrequest'),
    ]

    operations = [
    ]
