# Generated by Django 3.0.10 on 2021-02-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0026_merge_20210128_1058'),
        ('request_forms', '0026_auto_20210202_1543'),
    ]

    operations = [
    ]
