# Generated by Django 3.0.10 on 2021-02-19 11:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0027_merge_20210203_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationlkrequest',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='reservationlkrequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name='Номер'
            ),
        ),
        migrations.AlterField(
            model_name='reservationlkrequest',
            name='property_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('flat', 'Квартира'),
                    ('parking', 'Парковочное место'),
                    ('commercial', 'Коммерческое помещение'),
                    ('pantry', 'Кладовка'),
                ],
                max_length=20,
                verbose_name='Тип',
            ),
        ),
    ]
