# Generated by Django 3.0.10 on 2021-02-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0028_auto_20210219_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationlkrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservationlkrequest',
            name='phone',
        ),
        migrations.AlterField(
            model_name='reservationlkrequest',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Квартира'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение'), ('pantry', 'Кладовка')], max_length=20, verbose_name='Тип'),
        ),
    ]
