# Generated by Django 3.0.10 on 2021-02-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_merge_20210218_1237'),
        ('cities', '0022_auto_20210122_1455'),
        ('request_forms', '0029_auto_20210220_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformemployee',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customformemployee',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект'),
        ),
    ]
