# Generated by Django 3.0.10 on 2021-03-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20210122_1455'),
        ('request_forms', '0030_add_custom_form_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformemployee',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город'),
        ),
    ]
