# Generated by Django 3.0.10 on 2021-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0032_customform_google_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformemployee',
            name='is_for_comm_page',
            field=models.BooleanField(
                default=False, verbose_name='Показывать на странице коммерции'
            ),
        ),
    ]
