# Generated by Django 3.0.10 on 2021-03-18 08:52

import common.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0033_customformemployee_is_for_comm_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
            ],
            options={
                'verbose_name': 'Заявка для СМИ',
                'verbose_name_plural': 'Заявки для СМИ',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='manager',
            name='type_list',
            field=common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('vacancy', 'Отклик на вакансию'), ('sale', 'Заявка на продажу участка'), ('callback', 'Заявка на обратный звонок'), ('reservation', 'Заявка на бронирование'), ('excursion', 'Запись на экскурсию'), ('director', 'Запрос на связь с директором'), ('purchase', 'Заявка на помощь с оформлением покупки'), ('agent', 'Заявка агенств'), ('Contractor', 'Заявки для подрядчиков'), ('custom', 'Кастомная заявка'), ('commercial_rent', 'Заявка на аренду коммерческого помещения'), ('media', 'Заявка для СМИ')], max_length=20), size=None, verbose_name='Типы заявок'),
        ),
    ]
