# Generated by Django 3.0.10 on 2021-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0034_auto_20210318_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customform',
            options={'ordering': ('order',), 'verbose_name': 'Форма кастомной заявки', 'verbose_name_plural': 'Формы кастомных заявок'},
        ),
        migrations.AddField(
            model_name='customform',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
