# Generated by Django 3.0.10 on 2021-03-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20210122_1455'),
        ('request_forms', '0035_auto_20210319_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название агенства недвижимости'),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contractorrequest',
            name='about_company',
            field=models.TextField(blank=True, verbose_name='О компании подрядчика'),
        ),
        migrations.AddField(
            model_name='contractorrequest',
            name='offer',
            field=models.FileField(blank=True, upload_to='', verbose_name='Коммерческое предложение'),
        ),
        migrations.AddField(
            model_name='contractorrequest',
            name='type_of_job',
            field=models.CharField(blank=True, max_length=100, verbose_name='Виды работ'),
        ),
        migrations.AddField(
            model_name='manager',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Для отправки e-mail сообщений.', to='cities.City', verbose_name='Города'),
        ),
    ]
