# Generated by Django 3.0.10 on 2021-03-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0038_auto_20210326_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrequest',
            options={'ordering': ('-date',), 'verbose_name': 'Заявка агентств', 'verbose_name_plural': 'Заявка агентств'},
        ),
    ]
