# Generated by Django 3.0.10 on 2021-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("request_forms", "0041_auto_20210407_1356")]

    operations = [
        migrations.AddField(
            model_name="vacancyrequest",
            name="city",
            field=models.CharField(blank=True, max_length=64, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="vacancyrequest",
            name="position",
            field=models.CharField(blank=True, max_length=64, verbose_name="Должность"),
        ),
    ]
