# Generated by Django 3.0.10 on 2021-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("request_forms", "0042_auto_20210519_1151")]

    operations = [
        migrations.AddField(
            model_name="mediarequest",
            name="media_name",
            field=models.CharField(blank=True, max_length=250, verbose_name="Назвиние СМИ"),
        )
    ]
