# Generated by Django 3.0.10 on 2021-05-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0042_auto_20210519_1151"),
        ("request_forms", "0042_auto_20210520_1325"),
    ]

    operations = []
