# Generated by Django 3.0.10 on 2021-05-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0043_mediarequest_media_name"),
        ("request_forms", "0043_auto_20210528_1436"),
    ]

    operations = []
