# Generated by Django 3.0.10 on 2021-06-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0044_merge_20210528_1442"),
        ("request_forms", "0043_merge_20210520_1351"),
    ]

    operations = []
