# Generated by Django 3.0.10 on 2021-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0045_auto_20210610_1604"),
        ("request_forms", "0045_auto_20210609_1317"),
    ]

    operations = []
