# Generated by Django 3.0.10 on 2021-06-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0046_merge_20210611_1437"),
        ("request_forms", "0045_merge_20210609_1306"),
    ]

    operations = []
