# Generated by Django 3.0.10 on 2021-06-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0047_auto_20210616_1120"),
        ("request_forms", "0047_auto_20210616_1541"),
    ]

    operations = []
