# Generated by Django 3.0.10 on 2021-06-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0047_auto_20210615_1716"),
        ("request_forms", "0048_merge_20210617_1225"),
    ]

    operations = []
