# Generated by Django 3.0.10 on 2021-06-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0047_merge_20210615_1609"),
        ("request_forms", "0049_merge_20210618_1630"),
    ]

    operations = []
