# Generated by Django 3.0.10 on 2021-06-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0047_auto_20210617_1101"),
        ("request_forms", "0051_auto_20210622_1427"),
    ]

    operations = []
