# Generated by Django 3.0.10 on 2021-06-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0050_auto_20210621_1206"),
        ("request_forms", "0051_auto_20210622_1427"),
    ]

    operations = []
