# Generated by Django 3.0.10 on 2021-06-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0052_merge_20210622_1447"),
        ("request_forms", "0052_merge_20210622_1502"),
    ]

    operations = []
