# Generated by Django 3.0.10 on 2021-06-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0053_auto_20210623_1616"),
        ("request_forms", "0053_merge_20210622_1511"),
    ]

    operations = []
