# Generated by Django 3.0.10 on 2021-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("request_forms", "0055_auto_20210623_1859")]

    operations = [
        migrations.AddField(
            model_name="vacancyrequest",
            name="graduated_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выпуска"),
        ),
        migrations.AddField(
            model_name="vacancyrequest",
            name="institution",
            field=models.CharField(blank=True, max_length=128, verbose_name="Учебное заведение"),
        ),
        migrations.AddField(
            model_name="vacancyrequest",
            name="specialty",
            field=models.CharField(blank=True, max_length=128, verbose_name="Специальность"),
        ),
    ]
