# Generated by Django 3.0.10 on 2021-07-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0054_merge_20210624_1300"),
        ("request_forms", "0055_auto_20210623_1859"),
    ]

    operations = []
