# Generated by Django 3.0.10 on 2021-07-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_forms", "0056_auto_20210702_1519"),
        ("request_forms", "0057_auto_20210702_1727"),
    ]

    operations = []
