# Generated by Django 3.0.10 on 2021-08-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0059_auto_20210809_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatlistingrequestform',
            name='uptitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Над заголовком'),
        ),
    ]
