# Generated by Django 3.0.10 on 2021-10-12 13:00

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_merge_20211008_1746'),
        ('request_forms', '0060_flatlistingrequestform_uptitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='type_list',
            field=common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('vacancy', 'Отклик на вакансию'), ('sale', 'Заявка на продажу участка'), ('callback', 'Заявка на обратный звонок'), ('reservation', 'Заявка на бронирование'), ('excursion', 'Запись на экскурсию'), ('director', 'Запрос на связь с директором'), ('purchase', 'Заявка на помощь с оформлением покупки'), ('agent', 'Заявка агентств'), ('Contractor', 'Заявки для подрядчиков'), ('custom', 'Кастомная заявка'), ('commercial_rent', 'Заявка на аренду коммерческого помещения'), ('media', 'Заявка для СМИ'), ('realty_update', 'Обновление недвижимости'), ('lading', 'Заявка с лендинга'), ('anti_corruption', 'Заявка о противодействии коррупции'), ('teaser', 'Заявка со слайда главной страницы (тизера)'), ('news', 'Заявка со страницы новости'), ('office', 'Заявка на встречу в офисе'), ('lot_card', 'Заявка с карточки лота'), ('flat_listing', 'Заявка в листинге квартир'), ('start_sale', 'Заявка на уведомление о старте продаж')], max_length=20), size=None, verbose_name='Типы заявок'),
        ),
        migrations.CreateModel(
            name='StartSaleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('property_type', models.CharField(choices=[('flat', 'Квартира'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение'), ('pantry', 'Кладовка'), ('commercial_apartment', 'Аппартаменты коммерции')], max_length=20, verbose_name='Тип объекта собственности')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка на уведомление о старте продаж',
                'verbose_name_plural': 'Заявки на уведомление о старте продаж',
                'ordering': ('-date',),
            },
        ),
    ]
