# Generated by Django 3.0.10 on 2021-10-14 12:56

import common.fields
from django.db import migrations, models
import request_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0061_auto_20211012_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='property_type_list',
            field=common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('flat', 'Квартира'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение'), ('pantry', 'Кладовка'), ('commercial_apartment', 'Аппартаменты коммерции')], max_length=20), default=request_forms.models.get_property_type_list_default, help_text='Для отправки email-сообщений.', size=None, verbose_name='Типы недвижимости'),
        ),
    ]
