# Generated by Django 3.0.10 on 2021-10-15 07:42

from django.db import migrations
from request_forms.models import get_property_type_list_default


def forwards(apps, schema_editor):
    Manager = apps.get_model("request_forms", "Manager")

    property_type_list: list = get_property_type_list_default()
    for manager in Manager.objects.all():
        manager.property_type_list = property_type_list
        manager.save()


def reverse(apps, schema_editor):
    Manager = apps.get_model("request_forms", "Manager")

    for manager in Manager.objects.all():
        manager.property_type_list = []
        manager.save()


class Migration(migrations.Migration):

    dependencies = [('request_forms', '0062_manager_property_type_list')]

    operations = [migrations.RunPython(forwards, reverse_code=reverse)]
