# Generated by Django 3.0.10 on 2021-10-28 15:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0063_change_property_type_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='startsalerequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер'),
        ),
    ]
