# Generated by Django 3.0.10 on 2021-10-25 10:55

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0063_change_property_type_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='amo_send',
            field=models.BooleanField(default=True, verbose_name='Заявка отправлена в АМО'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='interval',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Интервал для звонка'),
        ),
    ]
