# Generated by Django 3.0.10 on 2021-10-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0064_auto_20211025_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='interval',
            field=models.CharField(choices=[('any', 'Любое'), ('9-11', '9:00-11:00'), ('11-13', '11:00-13:00'), ('13-15', '13:00-15:00'), ('15-17', '15:00-17:00'), ('17-19', '17:00-19:00')], default='any', max_length=5, verbose_name='Интервал для звонка'),
        ),
    ]
