# Generated by Django 3.0.10 on 2021-10-27 10:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('request_forms', '0065_auto_20211027_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='cookies',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='Сайт'),
        ),
    ]
