# Generated by Django 3.0.14 on 2021-11-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0064_startsalerequest_phone'),
        ('request_forms', '0067_callbackrequest_timezone_user'),
    ]

    operations = [
    ]
