# Generated by Django 3.0.14 on 2021-11-29 09:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_merge_20211119_1126'),
        ('request_forms', '0068_merge_20211117_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка на получение презентации',
                'verbose_name_plural': 'Заявки на получение презентации',
            },
        ),
    ]
