# Generated by Django 3.0.14 on 2021-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0071_auto_20211210_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeFirstRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('date', models.DateTimeField(verbose_name='Дата отправки')),
                ('subdomain', models.CharField(max_length=20, verbose_name='Поддомен')),
            ],
            options={
                'verbose_name': "Заявка 'Узнайте о новых проектах'",
                'verbose_name_plural': "Заявки 'Узнайте о новых проектах'",
            },
        ),
    ]
