# Generated by Django 3.0.14 on 2021-12-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0072_befirstrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='befirstrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
    ]
