# Generated by Django 3.0.14 on 2022-01-14 15:06

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0074_advantageformrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='type_list',
            field=common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('vacancy', 'Отклик на вакансию'), ('sale', 'Заявка на продажу участка'), ('callback', 'Заявка на обратный звонок'), ('reservation', 'Заявка на бронирование'), ('excursion', 'Запись на экскурсию'), ('director', 'Запрос на связь с директором'), ('purchase', 'Заявка на помощь с оформлением покупки'), ('agent', 'Заявка агентств'), ('Contractor', 'Заявки для подрядчиков'), ('custom', 'Кастомная заявка'), ('commercial_rent', 'Заявка на аренду коммерческого помещения'), ('media', 'Заявка для СМИ'), ('realty_update', 'Обновление недвижимости'), ('lading', 'Заявка с лендинга'), ('anti_corruption', 'Заявка о противодействии коррупции'), ('teaser', 'Заявка со слайда главной страницы (тизера)'), ('news', 'Заявка со страницы новости'), ('office', 'Заявка на встречу в офисе'), ('lot_card', 'Заявка с карточки лота'), ('flat_listing', 'Заявка в листинге квартир'), ('start_sale', 'Заявка на уведомление о старте продаж'), ('mallteam', 'Заявка с формы MallTeam'), ('comm_kotelniki', 'Заявка коммерции Котельники')], max_length=20), size=None, verbose_name='Типы заявок'),
        ),
    ]
