# Generated by Django 3.0.14 on 2022-01-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0075_auto_20220114_1806'),
        ('request_forms', '0075_auto_20220117_1252'),
    ]

    operations = [
    ]
