# Generated by Django 3.0.14 on 2022-01-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0076_merge_20220118_1020'),
        ('request_forms', '0075_reservationrequest_booking_type'),
    ]

    operations = [
    ]
