# Generated by Django 3.0.14 on 2022-02-01 07:38

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0104_auto_20220119_1833'),
        ('request_forms', '0077_merge_20220124_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='type_list',
            field=common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('vacancy', 'Отклик на вакансию'), ('sale', 'Заявка на продажу участка'), ('callback', 'Заявка на обратный звонок'), ('reservation', 'Заявка на бронирование'), ('excursion', 'Запись на экскурсию'), ('director', 'Запрос на связь с директором'), ('purchase', 'Заявка на помощь с оформлением покупки'), ('agent', 'Заявка агентств'), ('Contractor', 'Заявки для подрядчиков'), ('custom', 'Кастомная заявка'), ('commercial_rent', 'Заявка на аренду коммерческого помещения'), ('media', 'Заявка для СМИ'), ('realty_update', 'Обновление недвижимости'), ('lading', 'Заявка с лендинга'), ('anti_corruption', 'Заявка о противодействии коррупции'), ('teaser', 'Заявка со слайда главной страницы (тизера)'), ('news', 'Заявка со страницы новости'), ('office', 'Заявка на встречу в офисе'), ('lot_card', 'Заявка с карточки лота'), ('flat_listing', 'Заявка в листинге квартир'), ('start_sale', 'Заявка на уведомление о старте продаж'), ('mallteam', 'Заявка с формы MallTeam'), ('comm_kotelniki', 'Заявка коммерции Котельники'), ('show', 'Заявка записи на показ')], max_length=20), size=None, verbose_name='Типы заявок'),
        ),
        migrations.CreateModel(
            name='ShowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('property_type', models.CharField(blank=True, choices=[('flat', 'Квартира'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение'), ('pantry', 'Кладовка'), ('commercial_apartment', 'Аппартаменты коммерции')], max_length=20, verbose_name='Тип')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка записи на показ',
                'verbose_name_plural': 'Заявки записи на показ',
            },
        ),
    ]
