# Generated by Django 3.0.14 on 2022-09-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_auto_20220908_1648'),
        ('request_forms', '0078_auto_20220201_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_direction', to='vacancy.VacancyCategory', verbose_name='Категория'),
        ),
    ]
