# Generated by Django 3.0.14 on 2022-09-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_auto_20220908_1648'),
        ('request_forms', '0079_vacancyrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrequest',
            name='new_vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy', verbose_name='Вакансия'),
        ),
    ]
