# Generated by Django 3.0.14 on 2022-09-09 09:50

from django.db import migrations


def company_to_vacancy(apps, schema_editor):

    rf = apps.get_model('request_forms', 'VacancyRequest')
    NewVacancy = apps.get_model('vacancy', 'Vacancy')

    for obj in rf.objects.all():
        job_title = None
        if getattr(obj, 'vacancy'):
            job_title = obj.vacancy.job_title

        if job_title:
            obj.new_vacancy = NewVacancy.objects.filter(job_title=job_title).first()
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0080_vacancyrequest_new_vacancy'),
    ]

    operations = [
        migrations.RunPython(company_to_vacancy, reverse_code=migrations.RunPython.noop),
    ]
