# Generated by Django 3.0.14 on 2022-09-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0082_remove_vacancyrequest_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyrequest',
            old_name='new_vacancy',
            new_name='vacancy',
        ),
    ]
