# Generated by Django 3.0.14 on 2022-09-28 13:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('request_forms', '0084_auto_20220920_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='EKBStartSaleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1024, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер')),
                ('applicant', models.CharField(choices=[('realtor', 'Риелтор'), ('person', 'Частное лицо')], default='person', max_length=20, verbose_name='Тип заявителя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
            ],
            options={
                'verbose_name': 'Заявка на уведомление о старте продаж',
                'verbose_name_plural': 'Заявки на уведомление о старте продаж',
                'ordering': ('-date',),
            },
        ),
    ]
