# Generated by Django 3.0.14 on 2022-10-06 10:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0123_auto_20220804_1602'),
        ('request_forms', '0085_ekbstartsalerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartProjectsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер')),
                ('applicant', models.CharField(choices=[('realtor', 'Риелтор'), ('person', 'Частное лицо')], default='person', max_length=20, verbose_name='Тип заявителя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отклики старта проекта',
                'verbose_name_plural': 'Отклики старта проекта',
                'ordering': ('-date',),
            },
        ),
    ]
