# Generated by Django 3.0.14 on 2022-08-31 15:01

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0028_projectslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Категория вакансии',
                'verbose_name_plural': 'Категории вакансий',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VacancyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание 1')),
                ('text_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание 2')),
                ('advantages_title_1', models.CharField(blank=True, max_length=200, verbose_name='Преимущества / Заголовок 1')),
                ('advantages_title_2', models.CharField(blank=True, max_length=200, verbose_name='Преимущества / Заголовок 2')),
                ('advantages_button_text_1', models.CharField(blank=True, max_length=100, verbose_name='Преимущества / Текст кнопки 1')),
                ('advantages_button_text_2', models.CharField(blank=True, max_length=100, verbose_name='Преимущества / Текст кнопки 2')),
                ('video', models.CharField(blank=True, max_length=2000, verbose_name='Видео')),
                ('video_preview', ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='Видео / Превью')),
                ('video_title', models.CharField(blank=True, max_length=200, verbose_name='Видео / Заголовок')),
                ('video_description', models.TextField(blank=True, verbose_name='Видео / Описание')),
                ('vacancies', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вакансии')),
                ('vacancies_description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Описание вакансий')),
            ],
            options={
                'verbose_name': 'Страница вакансий',
                'verbose_name_plural': 'Страница вакансий',
            },
        ),
        migrations.CreateModel(
            name='VacancyPageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 500, выс. - 453', null=True, verbose_name='Изображение')),
                ('image_phone', models.ImageField(blank=True, null=True, upload_to='f/ip', verbose_name='Изображение телефон')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Текст на кнопке')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('yandex_metrics', models.CharField(blank=True, max_length=100, null=True, verbose_name='Яндекс метрика')),
                ('google_event_name', models.CharField(blank=True, max_length=100, verbose_name='Название ивента Google')),
            ],
            options={
                'verbose_name': 'Форма на странице вакансий',
                'verbose_name_plural': 'Формы на странице вакансий',
            },
        ),
        migrations.CreateModel(
            name='VacancyPageAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('icon', ajaximage.fields.AjaxImageField(blank=True, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.VacancyPage', verbose_name='Страница вакансий')),
            ],
            options={
                'verbose_name': 'Преимущество вакансий',
                'verbose_name_plural': 'Преимущества вакансий',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='vacancypage',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.VacancyPageForm', verbose_name='Форма'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Должность')),
                ('announcement', ckeditor.fields.RichTextField(blank=True, verbose_name='Анонс')),
                ('duties', ckeditor.fields.RichTextField(blank=True, verbose_name='Обязанности')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, verbose_name='Требования')),
                ('conditions', ckeditor.fields.RichTextField(blank=True, verbose_name='Условия ')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата добавления')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Очередность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('work_format', models.CharField(choices=[('remotely', 'Удаленно'), ('office', 'Работа из офиса')], default='office', max_length=20, verbose_name='Формат работы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.VacancyCategory', verbose_name='Категория')),
                ('city', models.ManyToManyField(blank=True, to='cities.City', verbose_name='Города')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('order',),
            },
        ),
    ]
