# Generated by Django 3.0.14 on 2022-09-02 08:56

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyPageFormEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 1000, выс. - 906', null=True, verbose_name='Изображение')),
                ('image_phone', models.ImageField(blank=True, null=True, upload_to='f/ip', verbose_name='Мобильное изображение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancy.VacancyPageForm', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Сотрудник формы страницы вакансий',
                'verbose_name_plural': 'Сотрудники формы страницы вакансий',
            },
        ),
    ]
