# Generated by Django 3.0.14 on 2022-09-06 08:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20220905_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='f/ip', verbose_name='Иконка')),
                ('main_img', models.ImageField(upload_to='f/ip', verbose_name='Основное изображение')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VacancyShouldWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('video', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Почему вам стоит работать',
                'verbose_name_plural': 'Почему вам стоит работать',
            },
        ),
        migrations.CreateModel(
            name='VacancyShouldWorkSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('img', models.ImageField(blank=True, null=True, upload_to='f/ip', verbose_name='Иконка')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст при наведении на карточку')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Почему вам стоит работать ( слайдер )',
                'verbose_name_plural': 'Почему вам стоит работать ( слайдер )',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VacancySlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='f/ip', verbose_name='Картинка')),
            ],
        ),
        migrations.AddField(
            model_name='vacancyabout',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.VacancyPageForm', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='vacancypageadvantage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.VacancyAbout', verbose_name='Страница вакансий'),
        ),
        migrations.DeleteModel(
            name='VacancyPage',
        ),
    ]
