# Generated by Django 3.0.14 on 2022-09-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20220906_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyabout',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AlterModelOptions(
            name='vacancyslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
