# Generated by Django 3.0.14 on 2022-09-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('vacancy', '0006_vacancydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='city', to='cities.City', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='vacancypageformemployee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_city', to='cities.City', verbose_name='Город'),
        ),
    ]
