# Generated by Django 3.0.14 on 2022-09-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('vacancy', '0008_auto_20220908_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypageformemployee',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_city', to='cities.City', verbose_name='Город'),
        ),
    ]
