# Generated by Django 3.0.14 on 2022-09-20 08:59

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_auto_20220908_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyslider',
            options={'verbose_name': 'Кадры нашей жизни', 'verbose_name_plural': 'Кадры нашей жизни'},
        ),
        migrations.AlterField(
            model_name='vacancypageformemployee',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
