# Generated by Django 3.0.14 on 2022-12-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_auto_20220920_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Формат работы',
                'verbose_name_plural': 'Форматы работы',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.VacancyFormat', verbose_name='Формат работы'),
        ),
    ]
