# Generated by Django 3.0.14 on 2022-12-08 12:11

from django.db import migrations
# Generated by Django 3.0.14 on 2022-12-08 08:48

from django.db import migrations


def fill_work_format_fk(apps, schema_editor):
    Vacancy = apps.get_model('vacancy', 'Vacancy')
    VacancyFormat = apps.get_model('vacancy', 'VacancyFormat')
    vacancies = Vacancy.objects.all()
    for vacancy in vacancies:
        vacancy.work_format_fk, _ = VacancyFormat.objects.get_or_create(name=vacancy.work_format)
    Vacancy.objects.bulk_update(vacancies, ['work_format_fk'])


def backwards(apps, schema_editor):
    Vacancy = apps.get_model('vacancy', 'Vacancy')
    VacancyFormat = apps.get_model('vacancy', 'VacancyFormat')
    vacancies = Vacancy.objects.all()
    for vacancy in vacancies:
        vacancy.work_format = vacancy.work_format_fk.name
    Vacancy.objects.bulk_update(vacancies, ['work_format'])
    VacancyFormat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0011_auto_20221208_1709'),
    ]

    operations = [
        migrations.RunPython(fill_work_format_fk, backwards)
    ]
