# Generated by Django 3.0.14 on 2022-12-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_auto_20221208_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='work_format',
        ),
    ]
