# Generated by Django 3.0.14 on 2022-12-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_remove_vacancy_work_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='work_format_fk',
            new_name='work_format',
        ),
    ]
