# Generated by Django 3.0.8 on 2020-07-03 08:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                (
                    "id_instagram",
                    models.CharField(db_index=True, max_length=200, verbose_name="ID инстаграмма"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="На обложке",
                        upload_to="instagram/image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Описание поста"),
                ),
                (
                    "shortcode",
                    models.CharField(db_index=True, max_length=200, verbose_name="Код поста"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="Количество лайков"),
                ),
                (
                    "timestamp",
                    models.PositiveIntegerField(default=0, verbose_name="Таймстап поста"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовать пост на сайте"),
                ),
            ],
            options={
                "verbose_name": "Пост в инстаграмме",
                "verbose_name_plural": "Посты в инстаграмме",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="InstagramPostImages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                (
                    "id_instagram",
                    models.CharField(db_index=True, max_length=200, verbose_name="ID инстаграмма"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="instagram/s_image", verbose_name="Слайд поста"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Очередность"),),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instagram.InstagramPost",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд поста",
                "verbose_name_plural": "Слайды поста",
                "ordering": ("order",),
            },
        ),
    ]
