# Generated by Django 3.0.10 on 2020-10-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_deadline"),
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramAccount",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True, verbose_name="ID",
                    ),
                ),
                ("first", models.PositiveSmallIntegerField(default=12, verbose_name="Количество"),),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт в инстраграме",
                "verbose_name_plural": "Аккаунты в инстаграме",
            },
        ),
        migrations.AddField(
            model_name="instagrampost",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="instagram.InstagramAccount",
                verbose_name="Аккаунт",
            ),
        ),
    ]
