# Generated by Django 3.0.10 on 2020-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_auto_20201007_0905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagramaccount",
            name="id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True, verbose_name="ID"
            ),
        ),
    ]
