# Generated by Django 3.0.10 on 2020-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_auto_20201105_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagramaccount",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="instagram/p_image",
                verbose_name="Изображение профиля",
            ),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="username",
            field=models.CharField(blank=True, max_length=50, verbose_name="Username"),
        ),
    ]
