# Generated by Django 3.0.10 on 2020-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0004_auto_20201109_0848"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrampost",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
