# Generated by Django 3.0.14 on 2022-07-08 07:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevLandAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
            options={
                'verbose_name': 'Главный Блок',
                'verbose_name_plural': 'Главные Блоки',
            },
        ),
        migrations.CreateModel(
            name='DevLandBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='DevLandCheckBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Чекбокс',
                'verbose_name_plural': 'Чекбоксы',
            },
        ),
        migrations.CreateModel(
            name='DevLandCheckBoxesTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке')),
            ],
            options={
                'verbose_name': 'Описание чекбоксов',
                'verbose_name_plural': 'Описание чекбоксов',
            },
        ),
        migrations.CreateModel(
            name='DevLandMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('number_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число 1')),
                ('number_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число 2')),
                ('number_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число 3')),
            ],
            options={
                'verbose_name': 'Данные на карте',
                'verbose_name_plural': 'Данные на карте',
            },
        ),
        migrations.CreateModel(
            name='DevLandSecondBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке')),
            ],
            options={
                'verbose_name': 'Второй Баннер',
                'verbose_name_plural': 'Вторые Баннеры',
            },
        ),
        migrations.CreateModel(
            name='DevLandThirdBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
            ],
            options={
                'verbose_name': 'Третий Баннер',
                'verbose_name_plural': 'Третий Баннеры',
            },
        ),
    ]
