# Generated by Django 3.0.14 on 2022-07-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landowners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devlandabout',
            options={'verbose_name': 'Информация в шапке', 'verbose_name_plural': 'Информация в шапке'},
        ),
        migrations.AlterModelOptions(
            name='devlandbanner',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='devlandsecondbanner',
            options={'verbose_name': 'Привмер успешного сотрудничества', 'verbose_name_plural': 'Привмеры успешного сотрудничества'},
        ),
        migrations.AlterModelOptions(
            name='devlandthirdbanner',
            options={'verbose_name': 'Партнерская программа', 'verbose_name_plural': 'Партнерские программы'},
        ),
        migrations.RemoveField(
            model_name='devlandsecondbanner',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='devlandsecondbanner',
            name='button_name',
        ),
        migrations.AddField(
            model_name='devlandsecondbanner',
            name='main_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Главное название'),
        ),
        migrations.AddField(
            model_name='devlandsecondbanner',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i'),
        ),
        migrations.AddField(
            model_name='devlandsecondbanner',
            name='quadrature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Квадратура'),
        ),
        migrations.AddField(
            model_name='devlandsecondbanner',
            name='years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='devlandthirdbanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке'),
        ),
        migrations.AddField(
            model_name='devlandthirdbanner',
            name='button_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке'),
        ),
        migrations.AddField(
            model_name='devlandthirdbanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='DevLandImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, max_length=500, null=True, upload_to='f/i')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='landowners.DevLandThirdBanner')),
            ],
            options={
                'verbose_name': 'Картинка бля блоока партнерская программа',
                'verbose_name_plural': 'Картинка бля блоока партнерская программа',
            },
        ),
    ]
