# Generated by Django 3.0.14 on 2022-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landowners', '0002_auto_20220721_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlandsecondbanner',
            name='quadrature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Площадь застройки'),
        ),
        migrations.AlterField(
            model_name='devlandsecondbanner',
            name='years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Годы застройки'),
        ),
    ]
