# Generated by Django 3.0.10 on 2020-09-30 12:36

import ajaximage.fields
import common.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_auto_20200721_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="mini_plan",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                validators=[django.core.validators.FileExtensionValidator(("jpg", "jpeg", "png"))],
                verbose_name="Мини-планировка",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="mini_plan_hover",
            field=common.fields.PolygonField(
                blank=True, source="building.mini_plan", verbose_name="Обводка на мини-плане",
            ),
        ),
    ]
