# Generated by Django 3.0.10 on 2020-10-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("buildings", "0005_auto_20201016_1356")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="mini_plan_height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Высота мини-планировки"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="mini_plan_width",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина мини-планировки"
            ),
        ),
    ]
