# Generated by Django 3.0.10 on 2020-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0006_auto_20201016_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="plan_height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Высота планировки"
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="plan_width",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина планировки"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="plan_height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Высота планировки"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="plan_width",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина планировки"
            ),
        ),
    ]
