# Generated by Django 3.0.10 on 2020-10-30 14:06

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0007_auto_20201016_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="point",
            field=common.fields.PpoiField(
                blank=True,
                max_length=50,
                null=True,
                source="project.plan",
                verbose_name="Точка на генплане",
            ),
        ),
    ]
