# Generated by Django 3.0.10 on 2020-10-30 14:52

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0008_building_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="point",
            field=common.fields.PpoiField(
                blank=True,
                max_length=50,
                null=True,
                source="section.plan",
                verbose_name="Точка на плане",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="point",
            field=common.fields.PpoiField(
                blank=True,
                max_length=50,
                null=True,
                source="building.plan",
                verbose_name="Точка на плане",
            ),
        ),
    ]
