# Generated by Django 3.0.10 on 2020-11-05 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0009_auto_20201030_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="plan_height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Высота планировки"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="plan_width",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ширина планировки"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="mini_plan",
            field=models.ImageField(
                blank=True,
                height_field="mini_plan_height",
                null=True,
                upload_to="b/b/mp",
                validators=[django.core.validators.FileExtensionValidator(("jpg", "jpeg", "png"))],
                verbose_name="Мини-планировка",
                width_field="mini_plan_width",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="plan",
            field=models.ImageField(
                blank=True,
                height_field="plan_height",
                null=True,
                upload_to="b/b/p",
                validators=[django.core.validators.FileExtensionValidator(("jpg", "jpeg"))],
                verbose_name="Планировка",
                width_field="plan_width",
            ),
        ),
    ]
