# Generated by Django 3.0.10 on 2020-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0011_auto_20201105_0824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="kind",
            field=models.CharField(
                choices=[
                    ("RESIDENTIAL", "Жилое"),
                    ("APARTMENT", "Апартаменты"),
                    ("PARKING", "Паркинг"),
                    ("OFFICE", "Коммерческое"),
                ],
                db_index=True,
                default="RESIDENTIAL",
                max_length=32,
                verbose_name="Тип строения",
            ),
        ),
    ]
