# Generated by Django 3.0.10 on 2020-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0012_auto_20201112_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="name_display",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отображаемое имя"
            ),
        ),
    ]
