# Generated by Django 3.0.10 on 2020-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_building_name_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='panorama_url',
            field=models.TextField(blank=True, verbose_name='URL на файл с панорамой'),
        ),
    ]
