# Generated by Django 3.0.10 on 2020-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_building_panorama_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Номер'),
        ),
    ]
