# Generated by Django 3.0.10 on 2020-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_auto_20201201_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='show_furnish',
            field=models.BooleanField(default=False, verbose_name='Показывать отделки'),
        ),
    ]
