# Generated by Django 3.0.10 on 2020-12-22 11:21

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_building_show_furnish'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='plan_2',
            field=ajaximage.fields.AjaxImageField(blank=True, verbose_name='Планировка'),
        ),
    ]
