# Generated by Django 3.0.10 on 2020-12-24 08:28

import ajaximage.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_section_plan_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='plan_2',
        ),
        migrations.RemoveField(
            model_name='section',
            name='plan_height',
        ),
        migrations.RemoveField(
            model_name='section',
            name='plan_width',
        ),
        migrations.CreateModel(
            name='GroupSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы секции')),
                ('plan', ajaximage.fields.AjaxImageField(blank=True, validators=[django.core.validators.FileExtensionValidator(('png', 'svg'))], verbose_name='Планировка')),
                ('plan_width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина планировки')),
                ('plan_height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота планировки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Очередность')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Группа секции',
                'verbose_name_plural': 'Группы секции',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='section',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.GroupSection', verbose_name='Группа секции'),
        ),
    ]
