# Generated by Django 3.0.10 on 2021-01-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0018_auto_20201224_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='booking_active',
            field=models.BooleanField(default=True, verbose_name='Бронирование активно'),
        ),
        migrations.AddField(
            model_name='building',
            name='booking_period',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Длительность бронирования'),
        ),
        migrations.AddField(
            model_name='building',
            name='booking_price',
            field=models.PositiveIntegerField(default=5000, verbose_name='Стоимость бронирования'),
        ),
    ]
