# Generated by Django 3.0.10 on 2021-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0018_auto_20201224_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='flats_0_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена студия'),
        ),
        migrations.AddField(
            model_name='building',
            name='flats_1_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 1-комн'),
        ),
        migrations.AddField(
            model_name='building',
            name='flats_2_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 2-комн'),
        ),
        migrations.AddField(
            model_name='building',
            name='flats_3_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 3-комн'),
        ),
        migrations.AddField(
            model_name='building',
            name='flats_4_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 4-комн'),
        ),
        migrations.AddField(
            model_name='floor',
            name='flats_0_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена студия'),
        ),
        migrations.AddField(
            model_name='floor',
            name='flats_1_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 1-комн'),
        ),
        migrations.AddField(
            model_name='floor',
            name='flats_2_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 2-комн'),
        ),
        migrations.AddField(
            model_name='floor',
            name='flats_3_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 3-комн'),
        ),
        migrations.AddField(
            model_name='floor',
            name='flats_4_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 4-комн'),
        ),
        migrations.AddField(
            model_name='section',
            name='flats_0_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена студия'),
        ),
        migrations.AddField(
            model_name='section',
            name='flats_1_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 1-комн'),
        ),
        migrations.AddField(
            model_name='section',
            name='flats_2_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 2-комн'),
        ),
        migrations.AddField(
            model_name='section',
            name='flats_3_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 3-комн'),
        ),
        migrations.AddField(
            model_name='section',
            name='flats_4_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Мин цена 4-комн'),
        ),
    ]
