# Generated by Django 3.0.10 on 2021-01-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0019_auto_20210125_0656'),
        ('buildings', '0019_auto_20210128_1445'),
    ]

    operations = [
    ]
