# Generated by Django 3.0.10 on 2021-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_merge_20210128_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
