# Generated by Django 3.0.10 on 2021-04-02 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_building_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание строительства'),
        ),
        migrations.AddField(
            model_name='building',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Старт строительства'),
        ),
        migrations.AlterField(
            model_name='building',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Высчитывается автоматически по полям "Старт строительства" и "Окончание строительства"', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Текущий уровень готовности'),
        ),
    ]
