# Generated by Django 3.0.10 on 2021-03-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_building_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='is_active',
        ),
    ]
