# Generated by Django 3.0.10 on 2021-04-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_auto_20210402_1554'),
        ('buildings', '0022_remove_building_is_active'),
    ]

    operations = [
    ]
