# Generated by Django 3.0.10 on 2021-05-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("buildings", "0023_auto_20210409_1421")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="commercial_building",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buildings.Building",
                verbose_name="Коммерческое строение",
            ),
        )
    ]
