# Generated by Django 3.0.10 on 2021-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_merge_20210413_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
