# Generated by Django 3.0.10 on 2021-04-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_auto_20210409_1421'),
        ('buildings', '0024_building_is_active'),
    ]

    operations = [
    ]
