# Generated by Django 3.0.10 on 2021-04-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0025_merge_20210416_1435'),
        ('buildings', '0025_merge_20210420_0837'),
    ]

    operations = [
    ]
