# Generated by Django 3.0.10 on 2021-05-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0026_merge_20210420_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
