# Generated by Django 3.0.10 on 2021-05-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0027_building_address"),
        ("buildings", "0024_building_commercial_building"),
    ]

    operations = []
