# Generated by Django 3.0.10 on 2021-05-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("buildings", "0028_merge_20210518_1002")]

    operations = [
        migrations.RemoveField(model_name="building", name="commercial_building"),
        migrations.AddField(
            model_name="building",
            name="residential_building",
            field=models.ForeignKey(
                blank=True,
                help_text="Привязывает коммерческие к жилым помещениям",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buildings.Building",
                verbose_name="Жилое строение",
            ),
        ),
    ]
