# Generated by Django 3.0.10 on 2021-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("buildings", "0029_auto_20210518_1004")]

    operations = [
        migrations.RemoveField(model_name="building", name="residential_building"),
        migrations.AddField(
            model_name="building",
            name="residential_set",
            field=models.ManyToManyField(
                blank=True,
                help_text="Привязывает коммерческие к жилым помещениям",
                limit_choices_to={"kind": "RESIDENTIAL"},
                related_name="_building_residential_set_+",
                to="buildings.Building",
                verbose_name="Жилое строение",
            ),
        ),
    ]
