# Generated by Django 3.0.10 on 2021-05-21 07:55

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("buildings", "0030_auto_20210520_1439")]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="exit_tooltip",
            field=models.CharField(blank=True, max_length=150, verbose_name="Текст подсказки"),
        ),
        migrations.AddField(
            model_name="floor",
            name="plan_exit",
            field=common.fields.PolygonField(
                blank=True, source="section.plan", verbose_name="Выход на плане"
            ),
        ),
    ]
