# Generated by Django 3.0.10 on 2021-05-21 15:30

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("buildings", "0031_auto_20210521_0755")]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="plan_exit",
            field=common.fields.PpoiField(
                blank=True, max_length=50, source="section.plan", verbose_name="Выход на плане"
            ),
        )
    ]
