# Generated by Django 3.0.10 on 2021-05-24 12:51

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("buildings", "0033_auto_20210521_1549")]

    operations = [
        migrations.RemoveField(model_name="floor", name="plan_exit"),
        migrations.CreateModel(
            name="FloorExitPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plan_exit",
                    common.fields.PpoiField(
                        blank=True,
                        max_length=50,
                        source="floor.plan",
                        verbose_name="Выход на плане",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.Floor",
                        verbose_name="Этаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "План выхода этажа",
                "verbose_name_plural": "Планы выхода этажей",
            },
        ),
    ]
