# Generated by Django 3.0.10 on 2021-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0048_layout_window_view"),
        ("buildings", "0034_auto_20210524_1251"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="furnish_set",
            field=models.ManyToManyField(
                blank=True, to="properties.Furnish", verbose_name="Варианты отделки"
            ),
        )
    ]
