# Generated by Django 3.0.10 on 2021-06-29 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0035_building_furnish_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="sun_azimuth",
            field=models.PositiveSmallIntegerField(
                default=180,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(360),
                ],
                verbose_name="Градус солнца",
            ),
        ),
    ]
