# Generated by Django 3.0.10 on 2021-07-19 12:20

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("buildings", "0035_building_furnish_set")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="commercial_plan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="b/b/cp",
                validators=[django.core.validators.FileExtensionValidator(("jpg", "jpeg"))],
                verbose_name="Планировка коммерции",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="commercial_point",
            field=common.fields.PpoiField(
                blank=True,
                max_length=50,
                null=True,
                source="building.commercial_plan",
                verbose_name="Точка на плане коммерции",
            ),
        ),
    ]
