# Generated by Django 3.0.10 on 2021-08-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0036_auto_20210719_1520"),
        ("buildings", "0036_building_sun_azimuth"),
    ]

    operations = []
