# Generated by Django 3.0.10 on 2021-08-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0038_section_total_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='total_floor',
            new_name='total_floors',
        ),
    ]
