# Generated by Django 3.0.10 on 2021-09-14 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0040_auto_20210812_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='fact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи по факту'),
        ),
        migrations.AlterField(
            model_name='building',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Высчитывается автоматически по полям "Дата старта строительства" и "Дата сдачи по факту"', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Текущий уровень готовности'),
        ),
        migrations.AlterField(
            model_name='building',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания строительства'),
        ),
        migrations.AlterField(
            model_name='building',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта строительства'),
        ),
    ]
