# Generated by Django 3.0.10 on 2021-11-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0041_auto_20210914_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Улица'),
        ),
    ]
