# Generated by Django 3.0.10 on 2021-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0042_building_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='window_view_hypo',
            field=models.ImageField(blank=True, upload_to='b/b/wvh', verbose_name='Изображение вида из окна (гипотеза)'),
        ),
    ]
