# Generated by Django 3.0.14 on 2021-11-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0043_building_window_view_hypo'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='compass_street_bottom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Нижняя улица на компасе'),
        ),
        migrations.AddField(
            model_name='building',
            name='compass_street_left',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Левая улица на компасе'),
        ),
        migrations.AddField(
            model_name='building',
            name='compass_street_right',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Правая улица на компасе'),
        ),
        migrations.AddField(
            model_name='building',
            name='compass_street_top',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Верхняя улица на компасе'),
        ),
    ]
