# Generated by Django 3.0.14 on 2021-12-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0044_auto_20211118_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingCommercialGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='b/bcg/i/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
            options={
                'verbose_name': 'Изображение для коммерческих помещений',
                'verbose_name_plural': 'Галерея для коммерческих помещений',
                'ordering': ('order',),
            },
        ),
    ]
