# Generated by Django 3.0.14 on 2021-12-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0045_buildingcommercialgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingCommercialGallery',
        ),
    ]
