# Generated by Django 3.0.14 on 2022-01-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0046_delete_buildingcommercialgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(default=30, verbose_name='Длительность бронирования')),
                ('price', models.PositiveIntegerField(default=5000, verbose_name='Стоимость бронирования')),
            ],
            options={
                'verbose_name': 'Тип бронирования у корпусов',
                'verbose_name_plural': 'Типы бронирований у корпусов',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='booking_types',
            field=models.ManyToManyField(blank=True, to='buildings.BuildingBookingType'),
        ),
    ]
