# Generated by Django 3.0.14 on 2022-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0047_auto_20220110_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='booking_types',
            field=models.ManyToManyField(blank=True, to='buildings.BuildingBookingType', verbose_name='Типы бронирования'),
        ),
    ]
