# Generated by Django 3.0.10 on 2022-02-05 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0048_auto_20220110_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='plan_night',
            field=models.ImageField(blank=True, height_field='plan_height', null=True, upload_to='b/b/pn', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg'))], verbose_name='Планировка (ночь)', width_field='plan_width'),
        ),
    ]
