# Generated by Django 3.0.10 on 2022-02-08 14:51

import ajaximage.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0049_building_plan_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsection',
            name='plan_night',
            field=ajaximage.fields.AjaxImageField(blank=True, validators=[django.core.validators.FileExtensionValidator(('png', 'svg'))], verbose_name='Планировка (ночь)'),
        ),
    ]
