# Generated by Django 3.0.14 on 2022-05-24 12:35

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0051_auto_20220504_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='plan_yard',
            field=common.fields.PolygonField(blank=True, source='project.plan', verbose_name='Полигоны на генплане'),
        ),
    ]
