# Generated by Django 3.0.14 on 2022-05-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0053_auto_20220525_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='yard_point',
        ),
    ]
