# Generated by Django 3.0.14 on 2022-05-25 12:50

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0054_remove_building_yard_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='yard_point1',
            field=common.fields.PpoiField(blank=True, max_length=50, null=True, source='project.plan', verbose_name='Точка дворов и парадной'),
        ),
    ]
