# Generated by Django 3.0.14 on 2022-05-25 12:51

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0055_building_yard_point1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='yard_point1',
        ),
        migrations.AddField(
            model_name='building',
            name='yard_point',
            field=common.fields.PpoiField(blank=True, default='0,0', max_length=50, null=True, source='project.plan', verbose_name='Точка дворов и парадной'),
        ),
    ]
