# Generated by Django 3.0.14 on 2022-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0056_auto_20220525_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='presentation_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для презентации'),
        ),
    ]
