# Generated by Django 3.0.14 on 2022-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0058_building_furnish_kitchen_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='show_furnish_kitchen',
            field=models.BooleanField(default=False, verbose_name='Показывать отделки кухни'),
        ),
    ]
