# Generated by Django 3.0.14 on 2022-09-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0061_buildingbookingtype_amocrm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, choices=[('panel', 'Панельный'), ('monolithic', 'Монолитный'), ('brick', 'Кирпичный'), ('brick_monolithic', 'Кирпично-монолитный'), ('frame_monolithic', 'Монолитно-каркасный ')], max_length=20, verbose_name='Тип'),
        ),
    ]
