# Generated by Django 3.0.14 on 2022-09-16 02:29

from django.db import migrations


def add_total_floors(apps, schema):
    """
    Добавим максимально имеющийся этаж в поле Количество этажей
    """

    Floor = apps.get_model('buildings', 'Floor')
    Section = apps.get_model('buildings', 'Section')

    for section in Section.objects.all():
        max_floor = Floor.objects.filter(section=section.id).order_by('-number').first()
        if max_floor:
            section.total_floors = abs(max_floor.number)
        else:
            section.total_floors = 1
        section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0062_auto_20220923_1324'),
    ]

    operations = [
        migrations.RunPython(add_total_floors, reverse_code=migrations.RunPython.noop),
    ]
