# Generated by Django 3.0.14 on 2022-10-17 11:31

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0064_auto_20220916_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='project_plan_hover',
            field=common.fields.PolygonField(blank=True, source='building.project.plan', verbose_name='Обводка на генплане ЖК'),
        ),
    ]
