# Generated by Django 3.0.14 on 2022-10-18 11:19

import buildings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0065_auto_20221017_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='panorama_file',
            field=models.FileField(blank=True, null=True, upload_to='buildings.models.archive_handler', verbose_name='файл с архивом панорамы'),
        ),
        migrations.AlterField(
            model_name='building',
            name='panorama_url',
            field=models.TextField(blank=True, help_text='устанавливается автоматически после распаковки и загрузки архива', verbose_name='URL на файл с панорамой'),
        ),
    ]
