# Generated by Django 3.0.14 on 2022-11-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0066_auto_20221018_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='panorama_file',
            field=models.FileField(blank=True, null=True, upload_to='b/p/p/', verbose_name='файл с архивом панорамы'),
        ),
    ]
