# Generated by Django 3.0.8 on 2020-09-28 08:19

import ajaximage.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "description",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "link_text",
                    models.CharField(blank=True, max_length=100, verbose_name="Текст ссылки"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("icon", ajaximage.fields.AjaxImageField(blank=True, verbose_name="Иконка"),),
            ],
            options={
                "verbose_name": "Способ покупки",
                "verbose_name_plural": "Способы покупки",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseTypeStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "purchase_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="purchase.PurchaseType",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг способа покупки",
                "verbose_name_plural": "Шаги способа покупки",
                "ordering": ("order",),
            },
        ),
    ]
