# Generated by Django 3.0.10 on 2020-10-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasetype",
            name="slug",
            field=models.SlugField(default=None, null=True, unique=True, verbose_name="Слаг"),
        ),
    ]
