# Generated by Django 3.0.10 on 2020-11-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0007_auto_20201102_1535"),
        ("purchase", "0002_purchasetype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasetype",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities.City",
                verbose_name="Город",
            ),
        ),
    ]
