# Generated by Django 3.0.10 on 2020-11-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_auto_20201105_0813"),
    ]

    operations = [
        migrations.RenameField(model_name="purchasetype", old_name="title", new_name="name",),
        migrations.AddField(
            model_name="purchasetype",
            name="title_1",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Заголовок 1"
            ),
        ),
        migrations.AddField(
            model_name="purchasetype",
            name="title_2",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Заголовок 2"
            ),
        ),
    ]
