# Generated by Django 3.0.10 on 2020-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_auto_20201106_0819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasetype",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
    ]
