# Generated by Django 3.0.10 on 2020-11-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0015_merge_20201118_0814"),
        ("purchase", "0006_auto_20201106_0820"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseTypeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Категория способов покупки",
                "verbose_name_plural": "Категории способов покупки",
                "ordering": ("order",),
            },
        ),
        migrations.AlterField(
            model_name="purchasetype",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="purchasetype",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase.PurchaseTypeCategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchasetype", unique_together={("city", "category")},
        ),
        migrations.RemoveField(model_name="purchasetype", name="slug",),
    ]
