# Generated by Django 3.0.10 on 2020-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_auto_20201118_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasetypecategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AddField(
            model_name="purchasetypecategory",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name="Слаг"),
        ),
    ]
