# Generated by Django 3.0.10 on 2020-12-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0008_auto_20201118_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasetypestep",
            name="purchase_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase.PurchaseType",
                verbose_name="Способ покупки",
            ),
        ),
    ]
