# Generated by Django 3.0.10 on 2021-03-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20201214_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetype',
            name='is_commercial',
            field=models.BooleanField(default=False, verbose_name='Для страницы коммерции'),
        ),
    ]
