# Generated by Django 3.0.14 on 2021-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20210427_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ по способу покупки',
                'verbose_name_plural': 'FAQ по способу покупки',
            },
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='faq',
            field=models.ManyToManyField(blank=True, to='purchase.PurchaseFAQ', verbose_name='FAQ'),
        ),
    ]
