# Generated by Django 3.0.14 on 2021-11-23 11:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20211112_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetype',
            name='description_document',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание для документов'),
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='purchase/image', verbose_name='Главная картинка'),
        ),
    ]
