# Generated by Django 3.0.14 on 2021-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20211123_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetype',
            name='show_calk',
            field=models.BooleanField(default=False, verbose_name='Отображать калькулятор'),
        ),
    ]
