# Generated by Django 3.0.14 on 2021-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_purchasetype_show_calk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseamountdescriptionblock',
            name='show_regional_block',
            field=models.BooleanField(default=False, verbose_name='Выводить в блоке региональный'),
        ),
        migrations.AddField(
            model_name='purchaseamountdescriptionblock',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок'),
        ),
    ]
