# Generated by Django 3.0.14 on 2022-01-10 08:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20211228_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetype',
            name='purchase_type_step_button',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст кнопки шагов покупки'),
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='purchase_type_step_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание шагов покупки'),
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='purchase_type_step_footer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Футер шагов покупки'),
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='purchase_type_step_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок шагов покупки'),
        ),
    ]
