# Generated by Django 3.0.10 on 2021-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_block', models.CharField(max_length=64, verbose_name='Блок IP-адресов')),
                ('start_ip', models.BigIntegerField(db_index=True, verbose_name='Начальный IP-адрес блока, преобразованный в число')),
                ('end_ip', models.BigIntegerField(db_index=True, verbose_name='Конечный IP-адрес блока, преобразованный в число')),
                ('city', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Город')),
                ('city_id', models.IntegerField(null=True, verbose_name='Ipgeobase Id Города')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Регион')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Округ')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота')),
                ('country', models.CharField(max_length=16, verbose_name='Страна')),
            ],
            options={
                'unique_together': {('start_ip', 'end_ip')},
                'index_together': {('start_ip', 'end_ip')},
            },
        ),
    ]
