# Generated by Django 3.0.14 on 2023-01-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0030_fill_city_amo_enums'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время создания/изменения записи')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='cities.City', verbose_name='город')),
            ],
            options={
                'verbose_name': 'Данные городов из DaData',
            },
        ),
        migrations.AddIndex(
            model_name='iplocation',
            index=models.Index(fields=['ip_address'], name='location_ip_idx'),
        ),
    ]
