# Generated by Django 3.0.10 on 2020-11-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0007_auto_20201102_1535"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmoCRMSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_id", models.TextField(blank=True, verbose_name="ID интеграции")),
                ("client_secret", models.TextField(blank=True, verbose_name="Секретный ключ")),
                ("access_token", models.TextField(blank=True, verbose_name="Access token")),
                ("refresh_token", models.TextField(blank=True, verbose_name="Refresh token")),
                ("redirect_uri", models.TextField(blank=True, verbose_name="URI редиректа")),
            ],
            options={"verbose_name": "Настройки AmoCRM",},
        ),
        migrations.CreateModel(
            name="AmoCRMManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("crm_id", models.CharField(max_length=20, verbose_name="ID менеджера из CRM")),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.City",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Менеджер из AmoCRM",
                "verbose_name_plural": "Менеджеры из AmoCRM",
                "ordering": ("city",),
            },
        ),
    ]
