# Generated by Django 3.0.10 on 2020-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amocrm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amocrmmanager",
            name="comm_pipeline_status_id",
            field=models.CharField(
                default="", max_length=20, verbose_name="ID статуса в воронке CRM для коммерции"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="amocrmmanager",
            name="pipeline_status_id",
            field=models.CharField(
                default="", max_length=20, verbose_name="ID статуса в воронке CRM"
            ),
            preserve_default=False,
        ),
    ]
