# Generated by Django 3.0.10 on 2020-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0002_auto_20201125_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmmanager',
            name='comm_pipeline_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID  воронки CRM'),
        ),
        migrations.AddField(
            model_name='amocrmmanager',
            name='pipeline_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID  воронки CRM'),
        ),
    ]
