# Generated by Django 3.0.10 on 2020-12-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0003_auto_20201209_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amocrmmanager',
            name='comm_pipeline_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID  воронки CRM для коммерции'),
        ),
    ]
