# Generated by Django 3.0.10 on 2021-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0004_auto_20201210_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmmanager',
            name='comm_crm_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID менеджера из CRM для коммерции'),
        ),
    ]
