# Generated by Django 3.0.10 on 2021-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0005_amocrmmanager_comm_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmmanager',
            name='is_default',
            field=models.BooleanField(
                default=False,
                help_text='Можно добавить только одного. Для всех заявок, кроме коммерции Тюмени, страницы коммеческой недвижимости и бронирования в ЛК.',
                verbose_name='Менеджер по умолчанию',
            ),
        ),
    ]
