# Generated by Django 3.0.10 on 2021-02-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20210122_1455'),
        ('amocrm', '0006_amocrmmanager_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amocrmmanager',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город'),
        ),
    ]
