# Generated by Django 3.0.14 on 2022-09-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_projectslide'),
        ('amocrm', '0007_auto_20210215_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmocrmPipelines',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID воронки из amocrm')),
                ('name', models.CharField(max_length=150, verbose_name='Имя воронки')),
                ('is_archive', models.BooleanField(default=False, verbose_name='В архиве')),
                ('is_main', models.BooleanField(default=False, verbose_name='Является ли воронка главной')),
                ('account_id', models.IntegerField(blank=True, null=True, verbose_name='ID аккаунта, в котором находится воронка')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='cities.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Воронка',
                'verbose_name_plural': 'Воронки',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='AmocrmStatuses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID сделки из amocrm')),
                ('name', models.CharField(max_length=150, verbose_name='Имя сделки')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('type', models.IntegerField(choices=[(1, 'Неразобранное'), (0, 'Обычный статус')], default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='amocrm.AmocrmPipelines', verbose_name='ID воронки из амо')),
            ],
            options={
                'verbose_name': 'Статус сделки',
                'verbose_name_plural': 'Статусы сделок',
                'ordering': ('sort',),
            },
        ),
    ]
