# Generated by Django 3.0.14 on 2022-07-12 14:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание поста')),
                ('shortcode', models.CharField(db_index=True, max_length=200, verbose_name='Код поста')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('timestamp', models.PositiveIntegerField(default=0, verbose_name='Таймстап поста')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать пост на сайте')),
                ('image', models.ImageField(blank=True, help_text='На обложке', upload_to='vk/image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Пост в vk',
                'verbose_name_plural': 'Посты в vk',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='VkPostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vk/s_image', verbose_name='Слайд поста')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Очередность')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk.VkPost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Слайд поста',
                'verbose_name_plural': 'Слайды поста',
                'ordering': ('order',),
            },
        ),
    ]
