# Generated by Django 3.0.14 on 2022-07-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_instagrampost_link'),
        ('vk', '0002_vkpostimages_id_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkAccount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('first', models.PositiveSmallIntegerField(default=12, verbose_name='Количество')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instagram/p_image', verbose_name='Изображение профиля')),
            ],
            options={
                'verbose_name': 'Аккаунт в вк',
                'verbose_name_plural': 'Аккаунты в вк',
            },
        ),
        migrations.AddField(
            model_name='vkpost',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.InstagramAccount', verbose_name='Аккаунт'),
        ),
    ]
