# Generated by Django 3.0.14 on 2022-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0003_auto_20220721_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkaccount',
            name='first',
        ),
    ]
