# Generated by Django 3.0.14 on 2022-07-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0004_remove_vkaccount_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkpost',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vk.VkAccount', verbose_name='Аккаунт'),
        ),
    ]
