# Generated by Django 3.0.14 on 2022-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0005_auto_20220721_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkaccount',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vk/p_image', verbose_name='Изображение профиля'),
        ),
    ]
