# Generated by Django 3.0.8 on 2020-07-30 10:40

import ajaximage.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("slug", models.SlugField(unique=True, verbose_name="Алиас")),
                (
                    "type",
                    models.CharField(
                        choices=[("news", "Новость"), ("action", "Акция")],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("intro", models.TextField(blank=True, verbose_name="Анонс")),
                (
                    "text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Текст"
                    ),
                ),
                ("image", ajaximage.fields.AjaxImageField(blank=True, verbose_name="Изображение"),),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Дата публикации",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Дата окончания",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Опубликовано"),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, to="projects.Project", verbose_name="Проекты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ("-start",),
            },
        ),
    ]
