# Generated by Django 3.0.10 on 2020-09-25 09:09

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Используется только для акций",
                null=True,
                verbose_name="Дата окончания",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="type",
            field=models.CharField(
                choices=[
                    ("news", "Новость"),
                    ("action", "Акция"),
                    ("progress", "Ход строительства"),
                    ("video", "Видео"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="VideoSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок"),),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("file", models.FileField(upload_to="news/videos", verbose_name="Видео"),),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Очередность"),),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.News",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео для слайдера",
                "verbose_name_plural": "Видео для слайдера",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="ImageSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок"),),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("image", ajaximage.fields.AjaxImageField(verbose_name="Изображение")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Очередность"),),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.News",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение для слайдера",
                "verbose_name_plural": "Изображения для слайдера",
                "ordering": ("order",),
            },
        ),
    ]
