# Generated by Django 3.0.10 on 2020-10-27 06:14

import ajaximage.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0007_auto_20201016_1502"),
        ("news", "0002_auto_20200925_0909"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 1440, выс. - 596",
                        null=True,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "preview",
                    ajaximage.fields.AjaxImageField(
                        blank=True,
                        help_text="шир. - 1920, выс. - 1080",
                        null=True,
                        verbose_name="Превью видео",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="news/videos", verbose_name="Видео"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Очередность")),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если изображение относится к ходу строительства, можно указать соответсвующий корпус",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.Building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайды",
                "verbose_name_plural": "Слайды",
                "ordering": ("order",),
            },
        ),
        migrations.RemoveField(model_name="videoslide", name="news",),
        migrations.AddField(
            model_name="news",
            name="card_image",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 480, выс. - 560",
                verbose_name="Изображение на карточке",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Используется для ходя строительства",
                null=True,
                verbose_name="Дата события",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=ajaximage.fields.AjaxImageField(
                blank=True,
                help_text="шир. - 766, выс. - 432",
                verbose_name="Изображение новости/акции",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Текст новости/акции"
            ),
        ),
        migrations.DeleteModel(name="ImageSlide",),
        migrations.DeleteModel(name="VideoSlide",),
        migrations.AddField(
            model_name="newsslide",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.News", verbose_name="Новость"
            ),
        ),
    ]
