# Generated by Django 3.0.10 on 2020-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_auto_20201027_0614"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="colored_title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Цветной заголовок"
            ),
        ),
    ]
