# Generated by Django 3.0.10 on 2020-11-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_colored_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='URL для изображения'),
        ),
        migrations.AddField(
            model_name='newsslide',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='URL для изображения'),
        ),
    ]
