# Generated by Django 3.0.10 on 2020-11-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201123_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='URL для видео'),
        ),
        migrations.AlterField(
            model_name='newsslide',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='URL для видео'),
        ),
    ]
