# Generated by Django 3.0.10 on 2020-12-05 12:20

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201123_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='card_image',
            field=models.ImageField(blank=True, help_text='шир. - 960, выс. - 1120', upload_to='news/images', verbose_name='Изображение на карточке'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='шир. - 1532, выс. - 864', upload_to='news/images', verbose_name='Изображение новости/акции'),
        ),
        migrations.AlterField(
            model_name='newsslide',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, help_text='шир. - 2880, выс. - 1192', null=True, verbose_name='Изображение'),
        ),
    ]
