# Generated by Django 3.0.10 on 2021-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210129_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='button_blank',
            field=models.BooleanField(default=False, verbose_name='Открывать ссылку кнопки в новой вкладке'),
        ),
        migrations.AlterField(
            model_name='news',
            name='button_name',
            field=models.CharField(blank=True, help_text='На странице новости', max_length=64, verbose_name='Название кнопки'),
        ),
    ]
