# Generated by Django 3.0.10 on 2021-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210201_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, help_text='Для камеры', null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('action', 'Акция'), ('progress', 'Ход строительства'), ('video', 'Видео'), ('stream', 'Онлайн трансляция')], max_length=20, verbose_name='Тип'),
        ),
    ]
