# Generated by Django 3.0.10 on 2021-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210217_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('order', '-start'), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
