# Generated by Django 3.0.10 on 2021-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210217_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='button_link',
            field=models.CharField(blank=True, help_text='Введите относительный путь. Пример: \n"/news" перенаправит на: https://strana.com/news \n"/" перенаправит на https://strana.com/', max_length=255, verbose_name='Относительная ссылка кнопки'),
        ),
    ]
