# Generated by Django 3.0.10 on 2021-02-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210218_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('order',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
