# Generated by Django 3.0.10 on 2021-02-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210218_0956'),
        ('news', '0012_btn_link_absolute_to_relative'),
    ]

    operations = [
    ]
