# Generated by Django 3.0.10 on 2021-02-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210224_1503'),
        ('news', '0012_btn_link_absolute_to_relative'),
    ]

    operations = [
    ]
