# Generated by Django 3.0.10 on 2021-02-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210224_1503'),
        ('news', '0013_merge_20210220_1308'),
    ]

    operations = [
    ]
