# Generated by Django 3.0.10 on 2021-02-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_merge_20210226_0731'),
        ('news', '0014_merge_20210224_1514'),
    ]

    operations = [
    ]
