# Generated by Django 3.0.10 on 2021-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_merge_20210226_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='button_link',
            field=models.CharField(blank=True, help_text='Введите относительный путь. Пример: <br>"/news" перенаправит на: https://strana.com/news <br>"/" перенаправит на https://strana.com/ <br>Если оставить пустое значение кнопка не отобразится', max_length=255, verbose_name='Относительная ссылка кнопки'),
        ),
    ]
