# Generated by Django 3.0.10 on 2021-04-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210226_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', models.FileField(blank=True, upload_to='news/mm', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='source_link',
            field=models.CharField(blank=True, help_text='Используется для СМИ о нас', max_length=264, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('action', 'Акция'), ('progress', 'Ход строительства'), ('video', 'Видео'), ('stream', 'Онлайн трансляция'), ('about_us', 'СМИ о нас')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='news',
            name='mass_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.MassMedia', verbose_name='СМИ'),
        ),
    ]
