# Generated by Django 3.0.10 on 2021-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210226_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('action', 'Акция'), ('progress', 'Ход строительства'), ('video', 'Видео'), ('stream', 'Онлайн трансляция'), ('action_landing', 'Промо-лендинг')], max_length=20, verbose_name='Тип'),
        ),
    ]
