# Generated by Django 3.0.10 on 2021-02-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210226_1301'),
        ('news', '0015_merge_20210226_1259'),
    ]

    operations = [
    ]
