# Generated by Django 3.0.10 on 2021-04-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210405_1537'),
        ('news', '0016_merge_20210226_1304'),
    ]

    operations = [
    ]
