# Generated by Django 3.0.10 on 2021-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210405_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='massmedia',
            name='is_display_name',
            field=models.BooleanField(default=True, verbose_name='Выводить название СМИ'),
        ),
    ]
