# Generated by Django 3.0.10 on 2021-04-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210311_1534'),
        ('news', '0017_massmedia_is_display_name'),
    ]

    operations = [
    ]
