# Generated by Django 3.0.10 on 2021-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_merge_20210406_0829'),
        ('news', '0017_massmedia_is_display_name'),
    ]

    operations = [
    ]
