# Generated by Django 3.0.10 on 2021-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_merge_20210413_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('action', 'Акция'), ('progress', 'Ход строительства'), ('video', 'Видео'), ('stream', 'Онлайн трансляция'), ('about_us', 'СМИ о нас'), ('action_landing', 'Промо-лендинг')], max_length=20, verbose_name='Тип'),
        ),
    ]
