# Generated by Django 3.0.10 on 2021-04-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20210413_1343'),
        ('news', '0018_merge_20210408_1259'),
    ]

    operations = [
    ]
