# Generated by Django 3.0.10 on 2021-05-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("news", "0020_merge_20210416_1435")]

    operations = [migrations.RemoveField(model_name="news", name="projects")]
