# Generated by Django 3.0.10 on 2021-06-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("news", "0022_news_projects")]

    operations = [
        migrations.CreateModel(
            name="NewsForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "button_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Название кнопки формы"
                    ),
                ),
                (
                    "yandex_metrics",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Яндекс метрика"
                    ),
                ),
                (
                    "google_event_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название ивента Google"
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма на странице новости",
                "verbose_name_plural": "Формы на странице новости",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="button_link",
            field=models.CharField(
                blank=True,
                help_text="Пример: /news/ -> strana.com/news/, для ссылки на внешний сайт, отметьте чекбокс ниже.",
                max_length=255,
                verbose_name="Ссылка кнопки",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.NewsForm",
                verbose_name="Форма",
            ),
        ),
    ]
