# Generated by Django 3.0.10 on 2021-06-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("news", "0023_auto_20210617_1506")]

    operations = [
        migrations.RenameField(
            model_name="newsform", old_name="button_name", new_name="button_text"
        ),
        migrations.RenameField(model_name="newsform", old_name="name", new_name="title"),
    ]
