# Generated by Django 3.0.10 on 2021-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0024_auto_20210618_1804")]

    operations = [
        migrations.RemoveField(model_name="newsform", name="button_text"),
        migrations.AlterField(
            model_name="news",
            name="button_name",
            field=models.CharField(
                blank=True,
                help_text="На странице новости. Для вывода ссылки заполните дополнительно ссылку, а для формы - форму.",
                max_length=64,
                verbose_name="Название кнопки",
            ),
        ),
    ]
