# Generated by Django 3.0.10 on 2021-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_news_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='card_image',
            field=models.ImageField(blank=True, help_text='шир. - 500, выс. - 425', upload_to='news/images', verbose_name='Изображение на карточке'),
        ),
    ]
