# Generated by Django 3.0.10 on 2021-08-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_news_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_display_flat_listing',
            field=models.BooleanField(default=False, verbose_name='Отображать в листинге квартир', help_text='Для акций'),
        ),
    ]
