# Generated by Django 3.0.10 on 2021-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_news_is_display_flat_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='card_description',
            field=models.TextField(blank=True, help_text='Для акции в листинге квартир', verbose_name='Описание на карточке'),
        ),
    ]
