# Generated by Django 3.0.10 on 2021-08-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20210819_1134'),
        ('news', '0028_news_card_description'),
    ]

    operations = [
    ]
